//! ÜRETİLMİŞ DOSYA — elle düzenlemeyin.
//!
//! Kaynak  : `spec-audit/spec_fields.json` (o da üretilmiş: `spec-audit/extract_fields.py`)
//! Üretim  : `python3 spec-audit/gen_translatable_fields.py`
//! Drift   : `python3 spec-audit/gen_translatable_fields.py --check`
//!
//! Spec'in `translations.txt::field_name` hakkındaki TEK hükmü tür eksenindedir
//! (`P7c7134fe`, soft): *"Fields with other types should not be translated."*
//! Çevrilebilir türler: Email, Phone number, Text, URL.
//!
//! ⚠️ Tabloda OLMAYAN bir alan hakkında bu dosya hüküm vermez. Uzantı alanları
//! (`jp_trip_desc_symbol` gibi) spec kataloğunda yoktur ve türleri bilinmez;
//! `spec_field_is_translatable` orada `None` döner ve çağıran SUSMALIDIR.

/// `translations.txt::table_name` için resmi GTFS tablo adları.
pub(crate) const SPEC_TRANSLATION_TABLES: &[&str] = &[
    "agency",
    "areas",
    "attributions",
    "booking_rules",
    "calendar",
    "calendar_dates",
    "fare_attributes",
    "fare_leg_join_rules",
    "fare_leg_rules",
    "fare_media",
    "fare_products",
    "fare_rules",
    "fare_transfer_rules",
    "feed_info",
    "frequencies",
    "levels",
    "location_group_stops",
    "location_groups",
    "networks",
    "pathways",
    "rider_categories",
    "route_networks",
    "routes",
    "shapes",
    "stop_areas",
    "stop_times",
    "stops",
    "timeframes",
    "transfers",
    "trips",
];

/// (tablo, alan, çevrilebilir tür mü) — (tablo, alan)'a göre SIRALI;
/// `binary_search_by` bunu varsayar.
pub(crate) const SPEC_TRANSLATION_FIELDS: &[(&str, &str, bool)] = &[
    ("agency", "agency_email", true),
    ("agency", "agency_fare_url", true),
    ("agency", "agency_id", false),
    ("agency", "agency_lang", false),
    ("agency", "agency_name", true),
    ("agency", "agency_phone", true),
    ("agency", "agency_timezone", false),
    ("agency", "agency_url", true),
    ("agency", "cemv_support", false),
    ("areas", "area_id", false),
    ("areas", "area_name", true),
    ("attributions", "agency_id", false),
    ("attributions", "attribution_email", true),
    ("attributions", "attribution_id", false),
    ("attributions", "attribution_phone", true),
    ("attributions", "attribution_url", true),
    ("attributions", "is_authority", false),
    ("attributions", "is_operator", false),
    ("attributions", "is_producer", false),
    ("attributions", "organization_name", true),
    ("attributions", "route_id", false),
    ("attributions", "trip_id", false),
    ("booking_rules", "booking_rule_id", false),
    ("booking_rules", "booking_type", false),
    ("booking_rules", "booking_url", true),
    ("booking_rules", "drop_off_message", true),
    ("booking_rules", "info_url", true),
    ("booking_rules", "message", true),
    ("booking_rules", "phone_number", true),
    ("booking_rules", "pickup_message", true),
    ("booking_rules", "prior_notice_duration_max", false),
    ("booking_rules", "prior_notice_duration_min", false),
    ("booking_rules", "prior_notice_last_day", false),
    ("booking_rules", "prior_notice_last_time", false),
    ("booking_rules", "prior_notice_service_id", false),
    ("booking_rules", "prior_notice_start_day", false),
    ("booking_rules", "prior_notice_start_time", false),
    ("calendar", "end_date", false),
    ("calendar", "friday", false),
    ("calendar", "monday", false),
    ("calendar", "saturday", false),
    ("calendar", "service_id", false),
    ("calendar", "start_date", false),
    ("calendar", "sunday", false),
    ("calendar", "thursday", false),
    ("calendar", "tuesday", false),
    ("calendar", "wednesday", false),
    ("calendar_dates", "date", false),
    ("calendar_dates", "exception_type", false),
    ("calendar_dates", "service_id", false),
    ("fare_attributes", "agency_id", false),
    ("fare_attributes", "currency_type", false),
    ("fare_attributes", "fare_id", false),
    ("fare_attributes", "payment_method", false),
    ("fare_attributes", "price", false),
    ("fare_attributes", "transfer_duration", false),
    ("fare_attributes", "transfers", false),
    ("fare_leg_join_rules", "from_network_id", false),
    ("fare_leg_join_rules", "from_stop_id", false),
    ("fare_leg_join_rules", "to_network_id", false),
    ("fare_leg_join_rules", "to_stop_id", false),
    ("fare_leg_rules", "fare_product_id", false),
    ("fare_leg_rules", "from_area_id", false),
    ("fare_leg_rules", "from_timeframe_group_id", false),
    ("fare_leg_rules", "leg_group_id", false),
    ("fare_leg_rules", "network_id", false),
    ("fare_leg_rules", "rule_priority", false),
    ("fare_leg_rules", "to_area_id", false),
    ("fare_leg_rules", "to_timeframe_group_id", false),
    ("fare_media", "fare_media_id", false),
    ("fare_media", "fare_media_name", true),
    ("fare_media", "fare_media_type", false),
    ("fare_products", "amount", false),
    ("fare_products", "currency", false),
    ("fare_products", "fare_media_id", false),
    ("fare_products", "fare_product_id", false),
    ("fare_products", "fare_product_name", true),
    ("fare_products", "rider_category_id", false),
    ("fare_rules", "contains_id", false),
    ("fare_rules", "destination_id", false),
    ("fare_rules", "fare_id", false),
    ("fare_rules", "origin_id", false),
    ("fare_rules", "route_id", false),
    ("fare_transfer_rules", "duration_limit", false),
    ("fare_transfer_rules", "duration_limit_type", false),
    ("fare_transfer_rules", "fare_product_id", false),
    ("fare_transfer_rules", "fare_transfer_type", false),
    ("fare_transfer_rules", "from_leg_group_id", false),
    ("fare_transfer_rules", "to_leg_group_id", false),
    ("fare_transfer_rules", "transfer_count", false),
    ("feed_info", "default_lang", false),
    ("feed_info", "feed_contact_email", true),
    ("feed_info", "feed_contact_url", true),
    ("feed_info", "feed_end_date", false),
    ("feed_info", "feed_lang", false),
    ("feed_info", "feed_publisher_name", true),
    ("feed_info", "feed_publisher_url", true),
    ("feed_info", "feed_start_date", false),
    ("feed_info", "feed_version", true),
    ("frequencies", "end_time", false),
    ("frequencies", "exact_times", false),
    ("frequencies", "headway_secs", false),
    ("frequencies", "start_time", false),
    ("frequencies", "trip_id", false),
    ("levels", "level_id", false),
    ("levels", "level_index", false),
    ("levels", "level_name", true),
    ("location_group_stops", "location_group_id", false),
    ("location_group_stops", "stop_id", false),
    ("location_groups", "location_group_id", false),
    ("location_groups", "location_group_name", true),
    ("networks", "network_id", false),
    ("networks", "network_name", true),
    ("pathways", "from_stop_id", false),
    ("pathways", "is_bidirectional", false),
    ("pathways", "length", false),
    ("pathways", "max_slope", false),
    ("pathways", "min_width", false),
    ("pathways", "pathway_id", false),
    ("pathways", "pathway_mode", false),
    ("pathways", "reversed_signposted_as", true),
    ("pathways", "signposted_as", true),
    ("pathways", "stair_count", false),
    ("pathways", "to_stop_id", false),
    ("pathways", "traversal_time", false),
    ("rider_categories", "eligibility_url", true),
    ("rider_categories", "is_default_fare_category", false),
    ("rider_categories", "rider_category_id", false),
    ("rider_categories", "rider_category_name", true),
    ("route_networks", "network_id", false),
    ("route_networks", "route_id", false),
    ("routes", "agency_id", false),
    ("routes", "cemv_support", false),
    ("routes", "continuous_drop_off", false),
    ("routes", "continuous_pickup", false),
    ("routes", "network_id", false),
    ("routes", "route_color", false),
    ("routes", "route_desc", true),
    ("routes", "route_id", false),
    ("routes", "route_long_name", true),
    ("routes", "route_short_name", true),
    ("routes", "route_sort_order", false),
    ("routes", "route_text_color", false),
    ("routes", "route_type", false),
    ("routes", "route_url", true),
    ("shapes", "shape_dist_traveled", false),
    ("shapes", "shape_id", false),
    ("shapes", "shape_pt_lat", false),
    ("shapes", "shape_pt_lon", false),
    ("shapes", "shape_pt_sequence", false),
    ("stop_areas", "area_id", false),
    ("stop_areas", "stop_id", false),
    ("stop_times", "arrival_time", false),
    ("stop_times", "continuous_drop_off", false),
    ("stop_times", "continuous_pickup", false),
    ("stop_times", "departure_time", false),
    ("stop_times", "drop_off_booking_rule_id", false),
    ("stop_times", "drop_off_type", false),
    ("stop_times", "end_pickup_drop_off_window", false),
    ("stop_times", "location_group_id", false),
    ("stop_times", "location_id", false),
    ("stop_times", "pickup_booking_rule_id", false),
    ("stop_times", "pickup_type", false),
    ("stop_times", "shape_dist_traveled", false),
    ("stop_times", "start_pickup_drop_off_window", false),
    ("stop_times", "stop_headsign", true),
    ("stop_times", "stop_id", false),
    ("stop_times", "stop_sequence", false),
    ("stop_times", "timepoint", false),
    ("stop_times", "trip_id", false),
    ("stops", "level_id", false),
    ("stops", "location_type", false),
    ("stops", "parent_station", false),
    ("stops", "platform_code", true),
    ("stops", "stop_access", false),
    ("stops", "stop_code", true),
    ("stops", "stop_desc", true),
    ("stops", "stop_id", false),
    ("stops", "stop_lat", false),
    ("stops", "stop_lon", false),
    ("stops", "stop_name", true),
    ("stops", "stop_timezone", false),
    ("stops", "stop_url", true),
    ("stops", "tts_stop_name", true),
    ("stops", "wheelchair_boarding", false),
    ("stops", "zone_id", false),
    ("timeframes", "end_time", false),
    ("timeframes", "service_id", false),
    ("timeframes", "start_time", false),
    ("timeframes", "timeframe_group_id", false),
    ("transfers", "from_route_id", false),
    ("transfers", "from_stop_id", false),
    ("transfers", "from_trip_id", false),
    ("transfers", "min_transfer_time", false),
    ("transfers", "to_route_id", false),
    ("transfers", "to_stop_id", false),
    ("transfers", "to_trip_id", false),
    ("transfers", "transfer_type", false),
    ("trips", "bikes_allowed", false),
    ("trips", "block_id", false),
    ("trips", "cars_allowed", false),
    ("trips", "direction_id", false),
    ("trips", "route_id", false),
    ("trips", "safe_duration_factor", false),
    ("trips", "safe_duration_offset", false),
    ("trips", "service_id", false),
    ("trips", "shape_id", false),
    ("trips", "trip_headsign", true),
    ("trips", "trip_id", false),
    ("trips", "trip_short_name", true),
    ("trips", "wheelchair_accessible", false),
];

/// `Some(true)` çevrilebilir tür · `Some(false)` bilinen ama çevrilemez tür ·
/// `None` spec kataloğunda yok (uzantı alanı) → hüküm verilemez.
pub(crate) fn spec_field_is_translatable(table: &str, field: &str) -> Option<bool> {
    SPEC_TRANSLATION_FIELDS
        .binary_search_by(|(t, f, _)| (*t, *f).cmp(&(table, field)))
        .ok()
        .map(|i| SPEC_TRANSLATION_FIELDS[i].2)
}

pub(crate) fn spec_translation_table_is_known(table: &str) -> bool {
    SPEC_TRANSLATION_TABLES.binary_search(&table).is_ok()
}
