// Generated by ui/scripts/gtfs-jp-coverage.mjs — do not edit by hand.

export const GTFS_JP_AUTOMATED_PROVISIONS = [
  {
    "provisionId": "V3-AGENCY-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_032"
    ],
    "source": "MLIT V3 s.11"
  },
  {
    "provisionId": "V3-AGENCY-JP-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_012"
    ],
    "source": "MLIT V3 agency_jp"
  },
  {
    "provisionId": "V3-AGENCY-JP-REFERENCE",
    "profile": "v3",
    "ruleIds": [
      "JPN_003"
    ],
    "source": "MLIT V3 agency_jp"
  },
  {
    "provisionId": "V3-AGENCY-ZIP",
    "profile": "v3",
    "ruleIds": [
      "JPN_013"
    ],
    "source": "MLIT V3 agency_jp"
  },
  {
    "provisionId": "V3-OFFICE-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_014"
    ],
    "source": "MLIT V3 office_jp"
  },
  {
    "provisionId": "V3-OFFICE-NAME",
    "profile": "v3",
    "ruleIds": [
      "JPN_005"
    ],
    "source": "MLIT V3 office_jp"
  },
  {
    "provisionId": "V3-OFFICE-CONTACT",
    "profile": "v3",
    "ruleIds": [
      "JPN_020"
    ],
    "source": "MLIT V3 office_jp"
  },
  {
    "provisionId": "V3-OFFICE-REFERENCE",
    "profile": "v3",
    "ruleIds": [
      "JPN_002"
    ],
    "source": "MLIT V3 office_jp"
  },
  {
    "provisionId": "V3-ROUTES-JP-ROUTE",
    "profile": "v3",
    "ruleIds": [
      "JPN_015"
    ],
    "source": "MLIT V3 routes_jp"
  },
  {
    "provisionId": "V3-ROUTES-JP-DATE",
    "profile": "v3",
    "ruleIds": [
      "JPN_016"
    ],
    "source": "MLIT V3 routes_jp"
  },
  {
    "provisionId": "V3-PATTERN-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_017"
    ],
    "source": "MLIT V3 pattern_jp"
  },
  {
    "provisionId": "V3-PATTERN-REF",
    "profile": "v3",
    "ruleIds": [
      "JPN_018"
    ],
    "source": "MLIT V3 trips/pattern_jp"
  },
  {
    "provisionId": "V3-TRANSLATIONS-FILE",
    "profile": "v3",
    "ruleIds": [
      "JPN_004"
    ],
    "source": "MLIT V3 translations"
  },
  {
    "provisionId": "V3-TRANSLATIONS-KANA",
    "profile": "v3",
    "ruleIds": [
      "JPN_001",
      "JPN_008",
      "JPN_009",
      "JPN_010",
      "JPN_028"
    ],
    "source": "MLIT V3 translations s.33"
  },
  {
    "provisionId": "V3-TRANSLATIONS-JA",
    "profile": "v3",
    "ruleIds": [
      "JPN_030"
    ],
    "source": "MLIT V3 translations s.33"
  },
  {
    "provisionId": "V3-TRANSLATIONS-RECORD",
    "profile": "v3",
    "ruleIds": [
      "JPN_019",
      "JPN_021"
    ],
    "source": "MLIT V3 translations"
  },
  {
    "provisionId": "V3-FEED-INFO",
    "profile": "v3",
    "ruleIds": [
      "JPN_007"
    ],
    "source": "MLIT V3 feed_info"
  },
  {
    "provisionId": "V3-AGENCY-REQUIRED",
    "profile": "v3",
    "ruleIds": [
      "JPN_011"
    ],
    "source": "MLIT V3 agency/routes"
  },
  {
    "provisionId": "V3-ROUTE-TYPE",
    "profile": "v3",
    "ruleIds": [
      "JPN_027"
    ],
    "source": "MLIT V3 routes.txt"
  },
  {
    "provisionId": "V3-ZONE-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_031"
    ],
    "source": "MLIT V3 fare/stop kapsamı"
  },
  {
    "provisionId": "SHARED-NAMESPACE",
    "profile": "v3,v4",
    "ruleIds": [
      "JPN_033"
    ],
    "source": "MLIT V3 s.10; V3→V4 farkı"
  },
  {
    "provisionId": "V4-FEED-LANG",
    "profile": "v4",
    "ruleIds": [
      "JPN_023"
    ],
    "source": "MLIT V4 s.29"
  },
  {
    "provisionId": "V4-AGENCY-LANG",
    "profile": "v4",
    "ruleIds": [
      "JPN_024"
    ],
    "source": "MLIT V4 s.35"
  },
  {
    "provisionId": "V4-AGENCY-TIMEZONE",
    "profile": "v4",
    "ruleIds": [
      "JPN_025"
    ],
    "source": "MLIT V4 s.35"
  },
  {
    "provisionId": "V4-FARE-CURRENCY",
    "profile": "v4",
    "ruleIds": [
      "JPN_026"
    ],
    "source": "MLIT V4 s.67"
  },
  {
    "provisionId": "V4-FARE-FILE",
    "profile": "v4",
    "ruleIds": [
      "JPN_006"
    ],
    "source": "MLIT V4 s.67"
  },
  {
    "provisionId": "V4-CORE-FIELDS",
    "profile": "v4",
    "ruleIds": [
      "JPN_022"
    ],
    "source": "MLIT V4 s.29,35,38,120"
  },
  {
    "provisionId": "V4-TRANSLATIONS-FILE",
    "profile": "v4",
    "ruleIds": [
      "JPN_004"
    ],
    "source": "MLIT V4 translations"
  },
  {
    "provisionId": "V4-TRANSLATIONS-KANA",
    "profile": "v4",
    "ruleIds": [
      "JPN_001",
      "JPN_008",
      "JPN_009",
      "JPN_010",
      "JPN_019",
      "JPN_021",
      "JPN_029"
    ],
    "source": "MLIT V4 s.75-77"
  },
  {
    "provisionId": "V4-FARE-AGENCY",
    "profile": "v4",
    "ruleIds": [
      "AGN_011"
    ],
    "source": "MLIT V4 farkı; GTFS Reference"
  },
  {
    "provisionId": "V4-LOCATION-HIERARCHY",
    "profile": "v4",
    "ruleIds": [
      "STP_009",
      "STP_010",
      "STP_011",
      "STP_012",
      "STP_021",
      "STP_032",
      "STP_036"
    ],
    "source": "MLIT V4 s.38,120; GTFS Reference"
  },
  {
    "provisionId": "V4-FLEX-STOP-TIMES",
    "profile": "v4",
    "ruleIds": [
      "STM_037",
      "STM_038",
      "STM_039",
      "STM_040",
      "STM_041",
      "STM_051",
      "STM_052",
      "STM_054",
      "STM_055",
      "STM_058"
    ],
    "source": "MLIT V4 farkı; GTFS Reference"
  },
  {
    "provisionId": "V4-CONTINUOUS-SHAPE",
    "profile": "v4",
    "ruleIds": [
      "TRP_019"
    ],
    "source": "MLIT V4 farkı; GTFS Reference"
  }
] as const;

export const GTFS_JP_AUTOMATED_COVERAGE_COMPLETE =
  GTFS_JP_AUTOMATED_PROVISIONS.length > 0 &&
  GTFS_JP_AUTOMATED_PROVISIONS.every((provision) => provision.ruleIds.length > 0);
