// Generated by ui/scripts/gtfs-jp-coverage.mjs — do not edit by hand.

export const GTFS_JP_AUTOMATED_PROVISIONS = [
  {
    "provisionId": "V3-AGENCY-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_032"
    ],
    "source": "MLIT V3 s.11",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.11 · agency.txt"
  },
  {
    "provisionId": "V3-AGENCY-JP-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_012"
    ],
    "source": "MLIT V3 agency_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "agency_jp.txt · agency_id"
  },
  {
    "provisionId": "V3-AGENCY-JP-REFERENCE",
    "profile": "v3",
    "ruleIds": [
      "JPN_003"
    ],
    "source": "MLIT V3 agency_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "agency_jp.txt · agency_id reference"
  },
  {
    "provisionId": "V3-AGENCY-ZIP",
    "profile": "v3",
    "ruleIds": [
      "JPN_013"
    ],
    "source": "MLIT V3 agency_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "agency_jp.txt · agency_zip_number"
  },
  {
    "provisionId": "V3-OFFICE-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_014"
    ],
    "source": "MLIT V3 office_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "office_jp.txt · office_id"
  },
  {
    "provisionId": "V3-OFFICE-NAME",
    "profile": "v3",
    "ruleIds": [
      "JPN_005"
    ],
    "source": "MLIT V3 office_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "office_jp.txt · office_name"
  },
  {
    "provisionId": "V3-OFFICE-CONTACT",
    "profile": "v3",
    "ruleIds": [
      "JPN_020"
    ],
    "source": "MLIT V3 office_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "office_jp.txt · office_url/office_phone"
  },
  {
    "provisionId": "V3-OFFICE-REFERENCE",
    "profile": "v3",
    "ruleIds": [
      "JPN_002"
    ],
    "source": "MLIT V3 office_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "office_jp.txt · jp_office_id"
  },
  {
    "provisionId": "V3-PATTERN-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_017"
    ],
    "source": "MLIT V3 pattern_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "pattern_jp.txt · jp_pattern_id"
  },
  {
    "provisionId": "V3-PATTERN-REF",
    "profile": "v3",
    "ruleIds": [
      "JPN_018"
    ],
    "source": "MLIT V3 trips/pattern_jp",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "pattern_jp.txt / trips.txt · jp_pattern_id"
  },
  {
    "provisionId": "V3-TRANSLATIONS-FILE",
    "profile": "v3",
    "ruleIds": [
      "JPN_004"
    ],
    "source": "MLIT V3 translations",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "translations.txt"
  },
  {
    "provisionId": "V3-TRANSLATIONS-KANA",
    "profile": "v3",
    "ruleIds": [
      "JPN_001",
      "JPN_008",
      "JPN_009",
      "JPN_010",
      "JPN_028"
    ],
    "source": "MLIT V3 translations s.33",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.33 · translations.txt"
  },
  {
    "provisionId": "V3-TRANSLATIONS-JA",
    "profile": "v3",
    "ruleIds": [
      "JPN_030"
    ],
    "source": "MLIT V3 translations s.33",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.33 · translations.txt · language=ja"
  },
  {
    "provisionId": "V3-TRANSLATIONS-RECORD",
    "profile": "v3",
    "ruleIds": [
      "JPN_019",
      "JPN_021"
    ],
    "source": "MLIT V3 translations",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "translations.txt · record_id/field_value"
  },
  {
    "provisionId": "V3-FEED-INFO",
    "profile": "v3",
    "ruleIds": [
      "JPN_007"
    ],
    "source": "MLIT V3 feed_info",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "feed_info.txt"
  },
  {
    "provisionId": "V3-AGENCY-REQUIRED",
    "profile": "v3",
    "ruleIds": [
      "JPN_011"
    ],
    "source": "MLIT V3 agency/routes",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "agency.txt / routes.txt · agency_id"
  },
  {
    "provisionId": "V3-ROUTE-TYPE",
    "profile": "v3",
    "ruleIds": [
      "JPN_027"
    ],
    "source": "MLIT V3 routes.txt",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "routes.txt · route_type (2-4)"
  },
  {
    "provisionId": "V3-ZONE-ID",
    "profile": "v3",
    "ruleIds": [
      "JPN_031"
    ],
    "source": "MLIT V3 fare/stop kapsamı",
    "sourceDocument": "MLIT GTFS-JP V3 final",
    "sourceVersion": "2021-07 final",
    "auditedOn": "2026-09-16",
    "pageAnchor": "stops.txt / fare_rules.txt"
  },
  {
    "provisionId": "SHARED-NAMESPACE",
    "profile": "v3,v4",
    "ruleIds": [
      "JPN_033"
    ],
    "source": "MLIT V3 s.10; V3→V4 farkı",
    "sourceDocument": "MLIT GTFS-JP V3 final; MLIT GTFS-JP V4 change document",
    "sourceVersion": "V3 final 2021-07; V4 change ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "V3 s.10; V4 change document · custom names"
  },
  {
    "provisionId": "V4-FEED-LANG",
    "profile": "v4",
    "ruleIds": [
      "JPN_023"
    ],
    "source": "MLIT V4 s.29",
    "sourceDocument": "MLIT GTFS-JP V4 specification",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.29 · feed_info.txt"
  },
  {
    "provisionId": "V4-AGENCY-LANG",
    "profile": "v4",
    "ruleIds": [
      "JPN_024"
    ],
    "source": "MLIT V4 s.35",
    "sourceDocument": "MLIT GTFS-JP V4 specification",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.35 · agency.txt"
  },
  {
    "provisionId": "V4-AGENCY-TIMEZONE",
    "profile": "v4",
    "ruleIds": [
      "JPN_025"
    ],
    "source": "MLIT V4 s.35",
    "sourceDocument": "MLIT GTFS-JP V4 specification",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.35 · agency.txt"
  },
  {
    "provisionId": "V4-FARE-CURRENCY",
    "profile": "v4",
    "ruleIds": [
      "JPN_026"
    ],
    "source": "MLIT V4 s.67",
    "sourceDocument": "MLIT GTFS-JP V4 specification",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.67 · fare_attributes.txt"
  },
  {
    "provisionId": "V4-FARE-RULES",
    "profile": "v4",
    "ruleIds": [
      "JPN_006"
    ],
    "source": "MLIT V4 s.67",
    "sourceDocument": "MLIT GTFS-JP V4 specification",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.67 · fare_rules.txt conditional branch"
  },
  {
    "provisionId": "V4-CORE-FIELDS",
    "profile": "v4",
    "ruleIds": [
      "JPN_022"
    ],
    "source": "MLIT V4 s.29,35,38,120",
    "sourceDocument": "MLIT GTFS-JP V4 specification",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.29, 35, 38, 120"
  },
  {
    "provisionId": "V4-TRANSLATIONS-FILE",
    "profile": "v4",
    "ruleIds": [
      "JPN_004"
    ],
    "source": "MLIT V4 translations",
    "sourceDocument": "MLIT GTFS-JP V4 specification",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "translations.txt"
  },
  {
    "provisionId": "V4-TRANSLATIONS-KANA",
    "profile": "v4",
    "ruleIds": [
      "JPN_001",
      "JPN_008",
      "JPN_009",
      "JPN_010",
      "JPN_019",
      "JPN_021",
      "JPN_029"
    ],
    "source": "MLIT V4 s.75-77",
    "sourceDocument": "MLIT GTFS-JP V4 specification",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.75-77 · translations.txt"
  },
  {
    "provisionId": "V4-FARE-AGENCY",
    "profile": "v4",
    "ruleIds": [
      "AGN_011"
    ],
    "source": "MLIT V4 farkı; GTFS Reference",
    "sourceDocument": "MLIT GTFS-JP V4 specification; GTFS Schedule Reference",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "V4 change · fare_attributes.txt agency_id"
  },
  {
    "provisionId": "V4-LOCATION-HIERARCHY",
    "profile": "v4",
    "ruleIds": [
      "STP_009",
      "STP_010",
      "STP_011",
      "STP_012",
      "STP_021",
      "STP_032",
      "STP_036"
    ],
    "source": "MLIT V4 s.38,120; GTFS Reference",
    "sourceDocument": "MLIT GTFS-JP V4 specification; GTFS Schedule Reference",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "s.38, 120 · stops.txt hierarchy"
  },
  {
    "provisionId": "V4-FLEX-STOP-TIMES",
    "profile": "v4",
    "ruleIds": [
      "STM_037",
      "STM_038",
      "STM_039",
      "STM_040",
      "STM_041",
      "STM_051",
      "STM_052",
      "STM_054",
      "STM_055",
      "STM_058"
    ],
    "source": "MLIT V4 farkı; GTFS Reference",
    "sourceDocument": "MLIT GTFS-JP V4 specification; GTFS Schedule Reference",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "V4 change · routes.txt/stop_times.txt flex fields"
  },
  {
    "provisionId": "V4-CONTINUOUS-SHAPE",
    "profile": "v4",
    "ruleIds": [
      "TRP_019"
    ],
    "source": "MLIT V4 farkı; GTFS Reference",
    "sourceDocument": "MLIT GTFS-JP V4 specification; GTFS Schedule Reference",
    "sourceVersion": "2026-03 ver.01",
    "auditedOn": "2026-09-16",
    "pageAnchor": "V4 change · routes.txt/trips.txt continuous service"
  }
] as const;

export const GTFS_JP_UNMATCHED_MACHINE_PROVISIONS = [] as const;

export const GTFS_JP_AUTOMATED_COVERAGE_COMPLETE =
  GTFS_JP_AUTOMATED_PROVISIONS.length > 0 &&
  GTFS_JP_UNMATCHED_MACHINE_PROVISIONS.length === 0 &&
  GTFS_JP_AUTOMATED_PROVISIONS.every((provision) => provision.ruleIds.length > 0);
