export const RULE_TITLES: Record<string, { tr: string; en: string }> = {
  // ARC
  'ARC_001': { tr: 'ZIP arşivi açılamadı', en: 'ZIP archive could not be opened' },
  'ARC_002': { tr: 'Dosya UTF-8 ile okunamıyor', en: 'File cannot be read as UTF-8' },
  'ARC_003': { tr: 'İsteğe bağlı dosyada UTF-8 kodlama hatası', en: 'UTF-8 encoding error in optional file' },
  'ARC_004': { tr: 'Zorunlu dosya eksik', en: 'Required file missing' },
  'ARC_006': { tr: 'İsteğe bağlı GTFS dosyası mevcut', en: 'Optional GTFS file present' },
  'ARC_007': { tr: 'GTFS dışı tanınmayan dosya', en: 'Unrecognized non-GTFS file' },
  'ARC_008': { tr: 'Takvim dosyası eksik (calendar.txt ve calendar_dates.txt)', en: 'Calendar file missing (calendar.txt and calendar_dates.txt)' },
  'ARC_009': { tr: 'Dosyada veri satırı yok', en: 'File has no data rows' },
  'ARC_010': { tr: 'Dosya UTF-8 BOM içeriyor', en: 'File contains UTF-8 BOM' },
  'ARC_011': { tr: 'Dosya boyutu (bilgi)', en: 'File size (info)' },
  'ARC_012': { tr: 'Satır sütun sayısı başlıkla uyuşmuyor', en: 'Row column count does not match header' },
  'ARC_013': { tr: 'CSV ayrıştırma hatası', en: 'CSV parse error' },
  'ARC_014': { tr: 'Başlıkta baştaki/sondaki boşluk', en: 'Leading/trailing whitespace in header' },
  'ARC_015': { tr: 'Yinelenen başlık sütunu', en: 'Duplicate header column' },
  'ARC_016': { tr: 'Zorunlu alan boş veya eksik', en: 'Required field empty or missing' },
  'ARC_017': { tr: 'Bilinmeyen sütun (GTFS spesifikasyonunda tanımlı değil)', en: 'Unknown column (not defined in GTFS specification)' },
  'ARC_018': { tr: 'Boş veri satırı', en: 'Empty data row' },
  'ARC_019': { tr: 'Başlıkta boş sütun adı', en: 'Empty column name in header' },
  'ARC_020': { tr: 'Önerilen GTFS dosyası eksik (shapes.txt veya feed_info.txt)', en: 'Recommended GTFS file missing (shapes.txt or feed_info.txt)' },
  'ARC_021': { tr: 'Alanda ASCII dışı veya yazdırılamaz karakter', en: 'Non-ASCII or non-printable character in field' },
  'ARC_022': { tr: 'Dosya satır sayısı 1.000.000 sınırını aşıyor', en: 'File row count exceeds 1,000,000 limit' },

  // BKR
  'BKR_001': { tr: 'Önceki gün rezervasyon alanı yasak bağlamda dolu', en: 'Prior-day booking field set in prohibited context' },
  'BKR_002': { tr: 'prior_notice_start_day yalnızca prior_notice_last_day ile kullanılabilir', en: 'prior_notice_start_day only valid with prior_notice_last_day' },
  'BKR_003': { tr: 'prior_notice_start_time yalnızca prior_notice_start_day ile kullanılabilir', en: 'prior_notice_start_time only valid with prior_notice_start_day' },
  'BKR_004': { tr: 'Anlık rezervasyonda prior_notice alanları yasak', en: 'prior_notice fields prohibited for real-time booking' },
  'BKR_005': { tr: 'prior_notice_duration_max yalnızca booking_type=1 ile kullanılabilir', en: 'prior_notice_duration_max only valid with booking_type=1' },
  'BKR_006': { tr: 'prior_notice_duration_min geçersiz (≤ 0 veya sayısal değil)', en: 'prior_notice_duration_min invalid (≤ 0 or non-numeric)' },
  'BKR_007': { tr: 'booking_type=1 için prior_notice_duration_min zorunlu', en: 'prior_notice_duration_min required for booking_type=1' },
  'BKR_008': { tr: 'booking_type=2 için prior_notice_last_day zorunlu', en: 'prior_notice_last_day required for booking_type=2' },
  'BKR_009': { tr: 'booking_type=2 için prior_notice_last_time zorunlu', en: 'prior_notice_last_time required for booking_type=2' },
  'BKR_010': { tr: 'prior_notice_start_day belirtilmişse prior_notice_start_time zorunlu', en: 'prior_notice_start_time required when prior_notice_start_day is set' },
  'BKR_011': { tr: 'prior_notice_last_day > prior_notice_start_day: rezervasyon penceresi geçersiz', en: 'prior_notice_last_day > prior_notice_start_day: invalid booking window' },

  // AGN
  'AGN_001': { tr: 'agency.txt dosyası eksik', en: 'agency.txt file missing' },
  'AGN_002': { tr: 'agency_name eksik', en: 'agency_name missing' },
  'AGN_003': { tr: 'agency_url eksik veya geçersiz', en: 'agency_url missing or invalid' },
  'AGN_004': { tr: 'agency_timezone eksik veya geçersiz', en: 'agency_timezone missing or invalid' },
  'AGN_005': { tr: 'Kuruluşlar arası saat dilimi tutarsızlığı', en: 'Timezone inconsistency across agencies' },
  'AGN_006': { tr: 'agency_lang geçersiz', en: 'agency_lang invalid' },
  'AGN_007': { tr: 'agency_phone geçersiz', en: 'agency_phone invalid' },
  'AGN_008': { tr: 'agency_fare_url geçersiz', en: 'agency_fare_url invalid' },
  'AGN_009': { tr: 'agency_email geçersiz', en: 'agency_email invalid' },
  'AGN_010': { tr: 'agency_id yineleniyor', en: 'Duplicate agency_id' },
  'AGN_011': { tr: 'Birden fazla kuruluşta agency_id yok', en: 'Multiple agencies with no agency_id' },
  'AGN_012': { tr: 'agency_cemv_support geçersiz', en: 'agency_cemv_support invalid' },
  'AGN_013': { tr: 'Feed dili ve ajans dili uyuşmuyor', en: 'Feed language and agency language mismatch' },

  // STP
  'STP_001': { tr: 'stop_id yineleniyor', en: 'Duplicate stop_id' },
  'STP_002': { tr: 'stop_id boş', en: 'stop_id is empty' },
  'STP_003': { tr: 'stop_name eksik veya stop_lat aralık dışı', en: 'stop_name missing or stop_lat out of range' },
  'STP_004': { tr: 'stop_lat sayısal değil', en: 'stop_lat is not numeric' },
  'STP_005': { tr: 'stop_lon geçersiz veya aralık dışı', en: 'stop_lon invalid or out of range' },
  'STP_006': { tr: 'stop_lat eksik', en: 'stop_lat missing' },
  'STP_007': { tr: 'stop_lon eksik', en: 'stop_lon missing' },
  'STP_008': { tr: 'location_type geçersiz', en: 'location_type invalid' },
  'STP_009': { tr: 'parent_station bulunamadı', en: 'parent_station not found' },
  'STP_010': { tr: 'parent_station location_type=1 değil', en: 'parent_station is not location_type=1' },
  'STP_011': { tr: 'Giriş/çıkış/boarding için parent_station zorunlu', en: 'parent_station required for entrance/exit/boarding area' },
  'STP_012': { tr: "stop_times'ta istasyon veya giriş kullanılmış", en: 'Station or entrance used in stop_times' },
  'STP_013': { tr: 'wheelchair_boarding geçersiz', en: 'wheelchair_boarding invalid' },
  'STP_014': { tr: 'stop_timezone geçersiz', en: 'stop_timezone invalid' },
  'STP_015': { tr: 'level_id bulunamadı', en: 'level_id not found' },
  'STP_016': { tr: 'İki durak tam aynı koordinatta', en: 'Two stops at identical coordinates' },
  'STP_017': { tr: 'İki durak birbirine çok yakın', en: 'Two stops too close together' },
  'STP_018': { tr: 'Hiç durak yok', en: 'No stops found' },
  'STP_019': { tr: 'stop_name çok uzun', en: 'stop_name too long' },
  'STP_020': { tr: 'Hiç sefer geçmeyen durak', en: 'Stop with no trips' },
  'STP_021': { tr: 'Alt durak istasyon dışında', en: 'Child stop outside parent station' },
  'STP_022': { tr: 'stop_code eksik', en: 'stop_code missing' },
  'STP_023': { tr: 'tts_stop_name geçersiz', en: 'tts_stop_name invalid' },
  'STP_024': { tr: 'stop_access geçersiz', en: 'stop_access invalid' },
  'STP_025': { tr: 'stop_name baştaki veya sondaki boşluk içeriyor', en: 'stop_name has leading or trailing whitespace' },
  'STP_026': { tr: 'stop_access geçersiz değer', en: 'stop_access invalid value' },
  'STP_027': { tr: "Pathway istasyonunda stop_access belirtilmemiş", en: 'stop_access not set on pathway station' },
  'STP_028': { tr: 'stop_code çok uzun', en: 'stop_code too long' },
  'STP_029': { tr: 'Durak istasyon içinde ama koordinat çok uzakta', en: 'Stop inside station but coordinate too far' },
  'STP_030': { tr: 'Üst istasyonun alt durağı yok', en: 'Parent station has no child stops' },
  'STP_031': { tr: 'Durak adı ve açıklaması aynı', en: 'Stop name and description are identical' },
  'STP_032': { tr: 'Pathway bağlantılı platform için parent_station eksik', en: 'parent_station missing for pathway-connected platform' },
  'STP_033': { tr: 'Durak zone_id eksik (ücret hesabı için gerekli)', en: 'Stop zone_id missing (required for fare calculation)' },
  'STP_034': { tr: "stop_url acente URL'siyle aynı", en: 'stop_url matches agency URL' },
  'STP_035': { tr: "stop_url hat URL'siyle aynı", en: 'stop_url matches route URL' },

  // RTS
  'RTS_001': { tr: 'route_id yineleniyor', en: 'Duplicate route_id' },
  'RTS_002': { tr: 'agency_id bulunamadı', en: 'agency_id not found' },
  'RTS_003': { tr: 'route_short_name ve route_long_name ikisi de eksik', en: 'Both route_short_name and route_long_name missing' },
  'RTS_004': { tr: 'route_type eksik veya geçersiz', en: 'route_type missing or invalid' },
  'RTS_005': { tr: 'route_url geçersiz', en: 'route_url invalid' },
  'RTS_006': { tr: 'route_color geçersiz hex renk', en: 'route_color invalid hex color' },
  'RTS_007': { tr: 'route_text_color geçersiz hex renk', en: 'route_text_color invalid hex color' },
  'RTS_008': { tr: 'Hat rengi ve metin rengi kontrast düşük', en: 'Route color and text color have low contrast' },
  'RTS_009': { tr: 'route_short_name ve route_long_name birbirinin aynısı', en: 'route_short_name and route_long_name are identical' },
  'RTS_010': { tr: 'route_short_name çok uzun', en: 'route_short_name too long' },
  'RTS_011': { tr: 'route_long_name çok uzun', en: 'route_long_name too long' },
  'RTS_012': { tr: 'Seferi olmayan hat', en: 'Route with no trips' },
  'RTS_013': { tr: 'continuous_pickup geçersiz', en: 'continuous_pickup invalid' },
  'RTS_014': { tr: 'route_long_name değerleri tekrar ediyor', en: 'Duplicate route_long_name values' },
  'RTS_016': { tr: 'Hiçbir aktif servis günü olmayan hat', en: 'Route with no active service days' },
  'RTS_017': { tr: 'Shape tanımlı olmayan hat', en: 'Route with no shape defined' },
  'RTS_018': { tr: 'continuous_drop_off geçersiz', en: 'continuous_drop_off invalid' },
  'RTS_019': { tr: 'Yinelenen hat adı', en: 'Duplicate route name' },
  'RTS_020': { tr: "Hat ve acente aynı URL'yi paylaşıyor", en: 'Route and agency share the same URL' },
  'RTS_021': { tr: 'Kısa hat adı Google Transit eşiğini (6 karakter) aşıyor', en: 'route_short_name exceeds Google Transit limit (6 characters)' },
  'RTS_022': { tr: 'Uzun hat adı kısa adı içeriyor', en: 'route_long_name contains route_short_name' },
  'RTS_023': { tr: 'Uzun hat adı ve açıklaması aynı', en: 'route_long_name and description are identical' },

  // TRP
  'TRP_001': { tr: 'trip_id eksik veya yineleniyor', en: 'trip_id missing or duplicate' },
  'TRP_002': { tr: 'route_id bulunamadı', en: 'route_id not found' },
  'TRP_003': { tr: 'service_id bulunamadı', en: 'service_id not found' },
  'TRP_004': { tr: 'shape_id bulunamadı', en: 'shape_id not found' },
  'TRP_005': { tr: 'direction_id geçersiz', en: 'direction_id invalid' },
  'TRP_006': { tr: 'wheelchair_accessible geçersiz', en: 'wheelchair_accessible invalid' },
  'TRP_007': { tr: 'bikes_allowed geçersiz', en: 'bikes_allowed invalid' },
  'TRP_009': { tr: 'Seferde zaman damgalı durak yok', en: 'Trip has no time-stamped stops' },
  'TRP_011': { tr: 'Sefer yön adı girilmemiş', en: 'Trip headsign not set' },
  'TRP_012': { tr: 'Çift yönlü rotada direction_id eksik', en: 'direction_id missing on bidirectional route' },
  'TRP_013': { tr: 'Hat tek seferlik', en: 'Route has only one trip' },
  'TRP_014': { tr: 'trip_short_name çok uzun', en: 'trip_short_name too long' },
  'TRP_015': { tr: 'block_id grubunda tek sefer', en: 'Single trip in block_id group' },
  'TRP_017': { tr: "Frekans tabanlı sefer stop_times'ta eksik", en: 'Frequency-based trip missing from stop_times' },
  'TRP_019': { tr: 'Continuous servis aktifken shape_id eksik', en: 'shape_id missing with continuous service active' },
  'TRP_020': { tr: 'trip_headsign ara durak adıyla eşleşiyor', en: 'trip_headsign matches intermediate stop name' },
  'TRP_021': { tr: 'Bisiklet izni (bikes_allowed) belirtilmemiş', en: 'Bicycle allowance (bikes_allowed) not specified' },
  'TRP_022': { tr: 'Block içinde çakışan sefer saatleri', en: 'Overlapping trip times within block' },
  'TRP_023': { tr: 'Önümüzdeki 7 günde aktif sefer yok', en: 'No active trips in the next 7 days' },
  'TRP_024': { tr: 'Block içinde tutarsız rota tipi', en: 'Inconsistent route type within block' },
  'TRP_025': { tr: 'Tekerlekli sandalye erişilebilirlik bilgisi eksik seferlerin oranı yüksek', en: 'High proportion of trips without wheelchair accessibility information' },
  'TRP_026': { tr: 'Hiçbir zaman çalışmayacak sefer (geçersiz service_id)', en: 'Trip that will never operate (invalid service_id)' },
  'TRP_028': { tr: 'Bazı seferler tekerlekli sandalye erişilebilirliği işaretlememiş', en: 'Some trips have not set wheelchair accessibility' },
  'TRP_029': { tr: 'Hiçbir sefer tekerlekli sandalye erişilebilirliği bildirmemiş', en: 'No trips report wheelchair accessibility' },

  // STM
  'STM_001': { tr: 'trip_id bulunamadı', en: 'trip_id not found' },
  'STM_002': { tr: 'stop_id bulunamadı', en: 'stop_id not found' },
  'STM_003': { tr: 'arrival_time geçersiz format', en: 'arrival_time invalid format' },
  'STM_004': { tr: 'departure_time geçersiz format', en: 'departure_time invalid format' },
  'STM_005': { tr: 'stop_sequence eksik veya geçersiz', en: 'stop_sequence missing or invalid' },
  'STM_006': { tr: 'stop_id eksik (stop_times)', en: 'stop_id missing (stop_times)' },
  'STM_007': { tr: 'Varış saati kalkış saatinden sonra', en: 'Arrival time after departure time' },
  'STM_008': { tr: 'Duraklar arası zaman geriye gidiyor', en: 'Time decreases between stops' },
  'STM_009': { tr: 'pickup_type geçersiz', en: 'pickup_type invalid' },
  'STM_010': { tr: 'drop_off_type geçersiz', en: 'drop_off_type invalid' },
  'STM_012': { tr: "Duraklar arası hız gerçekçi değil", en: 'Unrealistic speed between stops' },
  'STM_013': { tr: 'Karışık varış/kalkış zamanları', en: 'Mixed arrival/departure times' },
  'STM_014': { tr: 'Segmentte aşırı hız', en: 'Excessive speed in segment' },
  'STM_015': { tr: 'İlk duraklama noktası yok', en: 'Missing first timepoint' },
  'STM_016': { tr: 'Son duraklama noktası yok', en: 'Missing last timepoint' },
  'STM_017': { tr: 'Sefer saatlerinde güzergah mesafesi eksik', en: 'Shape distance missing in stop times' },
  'STM_018': { tr: 'continuous_pickup geçersiz (stop_times)', en: 'continuous_pickup invalid (stop_times)' },
  'STM_019': { tr: 'continuous_drop_off geçersiz (stop_times)', en: 'continuous_drop_off invalid (stop_times)' },
  'STM_020': { tr: 'Sıfır geçiş süresi (mesafe > 200m)', en: 'Zero travel time (distance > 200m)' },
  'STM_021': { tr: 'Duraklar arası mesafe sıfır veya negatif', en: 'Distance between stops is zero or negative' },
  'STM_022': { tr: 'timepoint geçersiz', en: 'timepoint invalid' },
  'STM_023': { tr: 'stop_times satır sıralaması bozuk', en: 'stop_times row ordering corrupted' },
  'STM_024': { tr: 'shape_dist_traveled birim tutarsızlığı', en: 'shape_dist_traveled unit inconsistency' },
  'STM_025': { tr: 'Seyahat süresi çok kısa', en: 'Travel time too short' },
  'STM_026': { tr: 'Durak arası mesafe aşırı uzun', en: 'Excessive distance between stops' },
  'STM_027': { tr: 'shape_dist_traveled monoton artmıyor', en: 'shape_dist_traveled not monotonically increasing' },
  'STM_028': { tr: 'Sefer süresi çok uzun', en: 'Trip duration too long' },
  'STM_029': { tr: 'Sefer süresi çok kısa', en: 'Trip duration too short' },
  'STM_030': { tr: 'shape_dist_traveled negatif', en: 'shape_dist_traveled is negative' },
  'STM_032': { tr: 'stop_times yinelenen satır', en: 'Duplicate stop_times row' },
  'STM_033': { tr: 'Tek duraklı sefer (kullanılamaz)', en: 'Single-stop trip (unusable)' },
  'STM_034': { tr: 'Varış veya kalkış zamanından yalnızca biri tanımlı', en: 'Only one of arrival or departure time defined' },
  'STM_035': { tr: 'Aynı durak ardışık iki kez ziyaret ediliyor (terminal/döngü)', en: 'Same stop visited twice consecutively (terminal/loop)' },
  'STM_036': { tr: 'stop_sequence değerleri sırasız (unsorted_stop_times)', en: 'stop_sequence values out of order (unsorted_stop_times)' },
  'STM_037': { tr: 'Flex penceresinde arrival_time/departure_time yasak', en: 'arrival_time/departure_time prohibited in Flex window' },
  'STM_038': { tr: 'start_pickup_drop_off_window > end_pickup_drop_off_window', en: 'start_pickup_drop_off_window > end_pickup_drop_off_window' },
  'STM_039': { tr: 'Flex bağlamında pickup/drop_off penceresi eksik', en: 'Pickup/drop-off window missing in Flex context' },
  'STM_040': { tr: "Flex stop_times'ta pickup/drop_off_booking_rule_id eksik", en: 'pickup/drop_off_booking_rule_id missing in Flex stop_times' },
  'STM_041': { tr: 'stop_id ile location_id/group_id aynı anda kullanılamaz', en: 'stop_id and location_id/group_id cannot be used together' },
  'STM_042': { tr: 'stop_headsign Google Transit tarafından desteklenmeyen karakter içeriyor', en: 'stop_headsign contains characters unsupported by Google Transit' },

  // PDW
  'PDW_006': { tr: "Aynı trip+zone'da örtüşen pickup/drop-off penceresi", en: 'Overlapping pickup/drop-off window for same trip+zone' },

  // LOC
  'LOC_001': { tr: "locations.geojson'da bilinmeyen veya geçersiz geometri tipi", en: 'Unknown or invalid geometry type in locations.geojson' },

  // CAL
  'CAL_001': { tr: 'service_id yineleniyor', en: 'Duplicate service_id' },
  'CAL_002': { tr: 'Takvim gün alanı geçersiz değer', en: 'Calendar day field invalid value' },
  'CAL_003': { tr: 'start_date geçersiz', en: 'start_date invalid' },
  'CAL_004': { tr: 'end_date geçersiz', en: 'end_date invalid' },
  'CAL_005': { tr: "start_date end_date'den sonra", en: 'start_date is after end_date' },
  'CAL_006': { tr: 'Serviste aktif gün yok', en: 'Service has no active days' },
  'CAL_007': { tr: 'Servis döneminde boşluk', en: 'Gap in service period' },
  'CAL_008': { tr: 'Servis tarihi yakında sona eriyor', en: 'Service expires soon' },
  'CAL_009': { tr: 'Aktif servisi olmayan sefer', en: 'Trip with no active service' },
  'CAL_010': { tr: 'Servis dönemi çok kısa', en: 'Service period too short' },
  'CAL_011': { tr: 'Kullanılmayan servis', en: 'Unused service' },
  'CAL_012': { tr: 'Yakın gelecekte aktif servis yok', en: 'No active service in the near future' },
  'CAL_013': { tr: 'Geçmiş tarihli servis dönemi', en: 'Expired service period' },
  'CAL_014': { tr: 'Servis tarihleri feed_info geçerlilik aralığı dışında', en: 'Service dates outside feed_info validity range' },
  'CAL_015': { tr: 'Tüm takvim tarihleri gelecekte (bugün aktif sefer yok)', en: 'All calendar dates in the future (no active trips today)' },
  'CAL_016': { tr: 'Servis çok uzak bir gelecek tarihine kadar uzanıyor', en: 'Service extends to a very distant future date' },
  'CAL_017': { tr: 'Takvim henüz başlamamış (tüm aktif tarihler gelecekte)', en: 'Calendar has not yet started (all active dates in the future)' },
  'CAL_018': { tr: 'Servisin aktif haftanın günü yok (tüm günler 0, calendar_dates ile geçersiz kılınan yok)', en: 'Service has no active weekdays (all days 0, none overridden by calendar_dates)' },

  // CLD
  'CLD_001': { tr: 'service_id eksik', en: 'service_id missing' },
  'CLD_002': { tr: 'date geçersiz format', en: 'date invalid format' },
  'CLD_003': { tr: 'exception_type eksik veya geçersiz', en: 'exception_type missing or invalid' },
  'CLD_004': { tr: 'Aynı tarihte çelişen kayıt', en: 'Conflicting record on same date' },
  'CLD_005': { tr: 'Tarih aralık dışında', en: 'Date out of range' },
  'CLD_006': { tr: 'Çok fazla istisna günü', en: 'Too many exception days' },
  'CLD_007': { tr: 'Aşırı takvim istisnası', en: 'Excessive calendar exceptions' },

  // SHP
  'SHP_001': { tr: 'shape_id eksik', en: 'shape_id missing' },
  'SHP_002': { tr: 'shape_pt_lat eksik veya geçersiz', en: 'shape_pt_lat missing or invalid' },
  'SHP_003': { tr: 'shape_pt_lon eksik veya geçersiz', en: 'shape_pt_lon missing or invalid' },
  'SHP_004': { tr: 'shape_pt_sequence eksik veya geçersiz', en: 'shape_pt_sequence missing or invalid' },
  'SHP_005': { tr: 'shape_dist_traveled geriye gidiyor', en: 'shape_dist_traveled decreases' },
  'SHP_006': { tr: 'Güzergah şekli yalnızca tek noktadan oluşuyor', en: 'Shape consists of a single point only' },
  'SHP_007': { tr: 'Güzergah şekli çok az nokta içeriyor', en: 'Shape contains too few points' },
  'SHP_008': { tr: 'shape_pt_sequence yineleniyor', en: 'Duplicate shape_pt_sequence' },
  'SHP_009': { tr: 'Güzergah şekli kendisiyle kesişiyor', en: 'Shape self-intersects' },
  'SHP_010': { tr: 'Tekrarlanan shape noktası (ardışık özdeş koordinat)', en: 'Repeated shape point (consecutive identical coordinates)' },
  'SHP_011': { tr: 'Güzergah şeklinde büyük boşluk', en: 'Large gap in shape' },
  'SHP_012': { tr: 'Güzergah şekli sefer duraklarından çok uzak', en: 'Shape too far from trip stops' },
  'SHP_014': { tr: 'İlk veya son durak güzergah ucundan uzakta', en: 'First or last stop far from shape endpoint' },
  'SHP_015': { tr: 'Güzergah şekli istatistiksel olarak çok az nokta', en: 'Shape has statistically too few points' },
  'SHP_016': { tr: 'Güzergah şekli yön bilgisiyle uyumsuz', en: 'Shape direction inconsistent with trip direction' },
  'SHP_017': { tr: 'Durak sırası güzergah şekliyle çelişiyor', en: 'Stop sequence conflicts with shape' },
  'SHP_018': { tr: 'Güzergah şekli sefer tarafından referanslanmıyor', en: 'Shape not referenced by any trip' },
  'SHP_019': { tr: 'Güzergah şeklinin seferleri durak zamanı içermiyor', en: "Shape's trips have no stop times" },
  'SHP_020': { tr: 'Güzergah şeklinde tekrarlayan nokta', en: 'Repeated point in shape' },
  'SHP_021': { tr: 'shape_dist_traveled negatif değer', en: 'shape_dist_traveled negative value' },
  'SHP_022': { tr: 'Durak güzergah şeklinde belirsiz konumda', en: 'Stop position ambiguous on shape' },
  'SHP_023': { tr: 'shape_dist_traveled aynı değere sahip art arda iki nokta aynı koordinatta', en: 'Consecutive points with same shape_dist_traveled at same coordinates' },
  'SHP_024': { tr: 'Duraktan şekle mesafe shape_dist_traveled ile tutarsız', en: 'Stop-to-shape distance inconsistent with shape_dist_traveled' },
  'SHP_025': { tr: 'Sefer stop_times mesafesi şeklin toplam mesafesini aşıyor', en: 'Trip stop_times distance exceeds total shape distance' },

  // FRQ
  'FRQ_001': { tr: 'trip_id bulunamadı', en: 'trip_id not found' },
  'FRQ_002': { tr: 'start_time geçersiz', en: 'start_time invalid' },
  'FRQ_003': { tr: 'end_time geçersiz', en: 'end_time invalid' },
  'FRQ_004': { tr: 'headway_secs eksik veya geçersiz', en: 'headway_secs missing or invalid' },
  'FRQ_005': { tr: "end_time start_time'dan önce", en: 'end_time is before start_time' },
  'FRQ_006': { tr: 'headway_secs çok uzun', en: 'headway_secs too long' },
  'FRQ_007': { tr: 'exact_times geçersiz', en: 'exact_times invalid' },
  'FRQ_008': { tr: 'headway_secs sıfır (geçersiz frekans)', en: 'headway_secs is zero (invalid frequency)' },
  'FRQ_009': { tr: 'Frekans aralığı çok kısa', en: 'Frequency interval too short' },
  'FRQ_010': { tr: 'Çok sık frekans (sıkışma riski)', en: 'Very high frequency (bunching risk)' },

  // TRF
  'TRF_001': { tr: 'from_stop_id eksik', en: 'from_stop_id missing' },
  'TRF_002': { tr: 'to_stop_id eksik', en: 'to_stop_id missing' },
  'TRF_003': { tr: 'from_stop_id veya to_stop_id bulunamadı', en: 'from_stop_id or to_stop_id not found' },
  'TRF_004': { tr: 'transfer_type geçersiz', en: 'transfer_type invalid' },
  'TRF_005': { tr: 'min_transfer_time eksik', en: 'min_transfer_time missing' },
  'TRF_006': { tr: 'from_trip_id bulunamadı', en: 'from_trip_id not found' },
  'TRF_007': { tr: 'to_trip_id bulunamadı', en: 'to_trip_id not found' },
  'TRF_008': { tr: 'from_route_id bulunamadı', en: 'from_route_id not found' },
  'TRF_009': { tr: 'to_route_id bulunamadı', en: 'to_route_id not found' },
  'TRF_010': { tr: 'Aktarma süresi çok uzun', en: 'Transfer time too long' },
  'TRF_011': { tr: 'Aktarma tanımlandı ama mesafe uzak', en: 'Transfer defined but distance is far' },
  'TRF_012': { tr: 'Yinelenen aktarma kaydı', en: 'Duplicate transfer record' },
  'TRF_013': { tr: 'Aktarma türü bağlamla uyumsuz', en: 'Transfer type inconsistent with context' },
  'TRF_014': { tr: 'in-seat aktarma için sefer yok', en: 'No trip for in-seat transfer' },
  'TRF_015': { tr: 'in-seat aktarma geçersiz', en: 'in-seat transfer invalid' },
  'TRF_016': { tr: 'Aktarma koşulu çelişkili', en: 'Transfer condition conflicting' },
  'TRF_017': { tr: 'Sefer aktarması yanlış hat', en: 'Trip transfer on wrong route' },
  'TRF_018': { tr: 'Sefer aktarması aynı seferi gösteriyor', en: 'Trip transfer references the same trip' },
  'TRF_019': { tr: 'In-seat aktarmada farklı route_type', en: 'Different route_type in in-seat transfer' },

  // GGL
  'GGL_001': { tr: 'transfer_type=4/5 Google Transit tarafından desteklenmiyor', en: 'transfer_type=4/5 not supported by Google Transit' },
  'GGL_002': { tr: 'ic_price (Google-özel) geçersiz değer', en: 'ic_price (Google-specific) invalid value' },

  // FAR
  'FAR_001': { tr: 'fare_id yineleniyor', en: 'Duplicate fare_id' },
  'FAR_002': { tr: 'price eksik veya geçersiz', en: 'price missing or invalid' },
  'FAR_003': { tr: 'currency_type eksik', en: 'currency_type missing' },
  'FAR_004': { tr: 'payment_method geçersiz', en: 'payment_method invalid' },
  'FAR_005': { tr: 'transfers geçersiz', en: 'transfers invalid' },
  'FAR_006': { tr: 'transfer_duration geçersiz', en: 'transfer_duration invalid' },
  'FAR_008': { tr: 'agency_id bulunamadı', en: 'agency_id not found' },
  'FAR_009': { tr: 'Ücrete ait hat kuralı yok', en: 'Fare has no route rules' },
  'FAR_010': { tr: 'Çakışan ücret kuralları', en: 'Overlapping fare rules' },

  // FRL
  'FRL_001': { tr: 'fare_id bulunamadı', en: 'fare_id not found' },
  'FRL_002': { tr: 'route_id bulunamadı', en: 'route_id not found' },
  'FRL_003': { tr: 'origin_id geçersiz', en: 'origin_id invalid' },
  'FRL_004': { tr: 'destination_id geçersiz', en: 'destination_id invalid' },
  'FRL_005': { tr: 'contains_id geçersiz', en: 'contains_id invalid' },
  'FRL_006': { tr: 'Ücret kuralı tanımlı değil', en: 'No fare rules defined' },
  'FRL_007': { tr: 'Ücret kuralı mantıksal tutarsızlık', en: 'Fare rule logical inconsistency' },
  'FRL_008': { tr: 'Tüm hatlar için ücret tanımlı değil', en: 'No fare defined for all routes' },

  // RCT
  'RCT_001': { tr: 'rider_category_id yineleniyor', en: 'Duplicate rider_category_id' },
  'RCT_002': { tr: 'rider_category_name eksik', en: 'rider_category_name missing' },
  'RCT_003': { tr: 'is_default_fare_category geçersiz', en: 'is_default_fare_category invalid' },
  'RCT_004': { tr: 'min_age veya max_age geçersiz', en: 'min_age or max_age invalid' },
  'RCT_005': { tr: "max_age min_age'den küçük", en: 'max_age less than min_age' },
  'RCT_006': { tr: 'fare_product başına birden fazla varsayılan yolcu kategorisi', en: 'Multiple default rider categories per fare_product' },

  // FMD
  'FMD_001': { tr: 'fare_media_id yineleniyor', en: 'Duplicate fare_media_id' },
  'FMD_002': { tr: 'fare_media_type eksik veya geçersiz', en: 'fare_media_type missing or invalid' },
  'FMD_003': { tr: 'TransitCard/MobileApp için fare_media_name tavsiye edilir', en: 'fare_media_name recommended for TransitCard/MobileApp' },

  // FPD
  'FPD_001': { tr: 'fare_product_id yineleniyor', en: 'Duplicate fare_product_id' },
  'FPD_002': { tr: 'amount eksik veya negatif', en: 'amount missing or negative' },
  'FPD_003': { tr: 'currency geçersiz ISO 4217 kodu', en: 'currency invalid ISO 4217 code' },
  'FPD_004': { tr: 'fare_media_id bulunamadı', en: 'fare_media_id not found' },
  'FPD_005': { tr: 'rider_category_id bulunamadı', en: 'rider_category_id not found' },
  'FPD_006': { tr: 'Bir fare_product için birden fazla varsayılan rider category', en: 'Multiple default rider categories for one fare_product' },

  // FLG
  'FLG_001': { tr: 'fare_product_id bulunamadı', en: 'fare_product_id not found' },
  'FLG_002': { tr: 'network_id bulunamadı', en: 'network_id not found' },
  'FLG_003': { tr: 'from_area_id bulunamadı', en: 'from_area_id not found' },
  'FLG_004': { tr: 'to_area_id bulunamadı', en: 'to_area_id not found' },
  'FLG_005': { tr: 'from_timeframe_group_id bulunamadı', en: 'from_timeframe_group_id not found' },
  'FLG_006': { tr: 'to_timeframe_group_id bulunamadı', en: 'to_timeframe_group_id not found' },
  'FLG_007': { tr: 'rule_priority geçersiz', en: 'rule_priority invalid' },

  // FTR
  'FTR_001': { tr: 'fare_transfer_type eksik veya geçersiz', en: 'fare_transfer_type missing or invalid' },
  'FTR_002': { tr: 'from_leg_group_id bulunamadı', en: 'from_leg_group_id not found' },
  'FTR_003': { tr: 'to_leg_group_id bulunamadı', en: 'to_leg_group_id not found' },
  'FTR_004': { tr: 'fare_product_id bulunamadı', en: 'fare_product_id not found' },
  'FTR_005': { tr: 'duration_limit_type geçersiz', en: 'duration_limit_type invalid' },
  'FTR_006': { tr: 'duration_limit geçersiz', en: 'duration_limit invalid' },
  'FTR_007': { tr: 'duration_limit_type duration_limit olmadan tanımlı', en: 'duration_limit_type defined without duration_limit' },
  'FTR_008': { tr: 'transfer_count geçersiz', en: 'transfer_count invalid' },

  // ARS
  'ARS_001': { tr: 'area_id yineleniyor', en: 'Duplicate area_id' },

  // SAR
  'SAR_001': { tr: 'area_id bulunamadı', en: 'area_id not found' },
  'SAR_002': { tr: 'stop_id bulunamadı', en: 'stop_id not found' },

  // NET
  'NET_001': { tr: 'network_id yineleniyor', en: 'Duplicate network_id' },

  // TFR
  'TFR_001': { tr: 'timeframe_group_id eksik', en: 'timeframe_group_id missing' },
  'TFR_002': { tr: 'service_id bulunamadı', en: 'service_id not found' },
  'TFR_003': { tr: 'start_time veya end_time format hatası', en: 'start_time or end_time format error' },
  'TFR_004': { tr: "end_time start_time'dan küçük", en: 'end_time less than start_time' },
  'TFR_005': { tr: 'Aynı grup ve service_id içinde örtüşen zaman aralıkları', en: 'Overlapping time ranges within same group and service_id' },

  // PTH
  'PTH_001': { tr: 'pathway_id yineleniyor', en: 'Duplicate pathway_id' },
  'PTH_002': { tr: 'from_stop_id bulunamadı', en: 'from_stop_id not found' },
  'PTH_003': { tr: 'to_stop_id bulunamadı', en: 'to_stop_id not found' },
  'PTH_004': { tr: 'pathway_mode eksik veya geçersiz', en: 'pathway_mode missing or invalid' },
  'PTH_005': { tr: 'is_bidirectional eksik', en: 'is_bidirectional missing' },
  'PTH_006': { tr: 'length geçersiz', en: 'length invalid' },
  'PTH_007': { tr: 'traversal_time geçersiz', en: 'traversal_time invalid' },
  'PTH_008': { tr: 'stair_count eksik', en: 'stair_count missing' },
  'PTH_009': { tr: 'max_slope eksik', en: 'max_slope missing' },
  'PTH_010': { tr: 'min_width geçersiz', en: 'min_width invalid' },
  'PTH_011': { tr: 'Geçit döngü oluşturuyor', en: 'Pathway forms a loop' },
  'PTH_012': { tr: 'İstasyona erişilebilir yol yok', en: 'No accessible pathway to station' },
  'PTH_013': { tr: 'Erişilebilir yol analizi', en: 'Accessible pathway analysis' },
  'PTH_014': { tr: 'Geçit istasyon sınırını aşıyor', en: 'Pathway crosses station boundary' },
  'PTH_015': { tr: 'Geçit hedefi erişilemeyen durakta', en: 'Pathway leads to an unreachable stop' },
  'PTH_016': { tr: 'Çıkış kapısı çift yönlü tanımlanmış', en: 'Exit defined as bidirectional' },
  'PTH_017': { tr: 'max_slope geçersiz bağlam', en: 'max_slope invalid context' },
  'PTH_018': { tr: 'signposted_as çok uzun', en: 'signposted_as too long' },
  'PTH_019': { tr: "Generic node tek pathway'e bağlı (dead-end)", en: 'Generic node connected to single pathway (dead-end)' },

  // LVL
  'LVL_001': { tr: 'level_id yineleniyor', en: 'Duplicate level_id' },
  'LVL_002': { tr: 'level_index geçersiz', en: 'level_index invalid' },
  'LVL_003': { tr: 'level_name eksik', en: 'level_name missing' },
  'LVL_004': { tr: 'Kullanılmayan level', en: 'Unused level' },
  'LVL_005': { tr: 'level_name çok uzun', en: 'level_name too long' },
  'LVL_006': { tr: 'Asansör bağlantısındaki durakta level_id eksik', en: 'level_id missing on elevator-connected stop' },

  // FIN
  'FIN_001': { tr: 'feed_publisher_name eksik', en: 'feed_publisher_name missing' },
  'FIN_002': { tr: 'feed_publisher_url eksik veya geçersiz', en: 'feed_publisher_url missing or invalid' },
  'FIN_003': { tr: 'feed_lang eksik', en: 'feed_lang missing' },
  'FIN_004': { tr: 'default_lang geçersiz', en: 'default_lang invalid' },
  'FIN_005': { tr: 'feed_start_date geçersiz', en: 'feed_start_date invalid' },
  'FIN_006': { tr: 'feed_end_date geçersiz veya geçmiş tarihli', en: 'feed_end_date invalid or past' },
  'FIN_007': { tr: 'feed_version eksik', en: 'feed_version missing' },
  'FIN_008': { tr: 'feed_contact_email geçersiz', en: 'feed_contact_email invalid' },
  'FIN_009': { tr: 'feed_contact_url geçersiz', en: 'feed_contact_url invalid' },
  'FIN_010': { tr: 'Feed geçerlilik süresi dolmuş', en: 'Feed validity expired' },
  'FIN_012': { tr: "feed_start_date feed_end_date'den sonra", en: 'feed_start_date is after feed_end_date' },
  'FIN_013': { tr: 'fare_attributes.agency_id önerilen ama eksik', en: 'fare_attributes.agency_id recommended but missing' },
  'FIN_014': { tr: 'Feed geçerlilik tarihleri (feed_start_date/feed_end_date) eksik', en: 'Feed validity dates (feed_start_date/feed_end_date) missing' },
  'FIN_015': { tr: 'Birden fazla feed_info kaydı', en: 'Multiple feed_info records' },
  'FIN_016': { tr: 'feed_start_date gelecekte (feed henüz aktif değil)', en: 'feed_start_date in the future (feed not yet active)' },
  'FIN_017': { tr: 'Feed çok uzak gelecekte sona eriyor', en: 'Feed expires in the very distant future' },
  'FIN_018': { tr: 'feed_contact_email ve feed_contact_url ikisi de eksik', en: 'Both feed_contact_email and feed_contact_url missing' },
  'FIN_019': { tr: "Feed'in geçerlilik süresi 7 gün içinde dolacak", en: 'Feed validity expires within 7 days' },

  // TRN
  'TRN_001': { tr: 'table_name geçersiz değer', en: 'table_name invalid value' },
  'TRN_002': { tr: 'field_name bu tablo için geçersiz', en: 'field_name invalid for this table' },
  'TRN_003': { tr: 'language geçersiz', en: 'language invalid' },
  'TRN_004': { tr: 'record_id bulunamadı', en: 'record_id not found' },
  'TRN_005': { tr: 'Çeviri yineleniyor', en: 'Duplicate translation' },
  'TRN_006': { tr: 'Çeviri kaydı çelişkili', en: 'Translation record conflicting' },
  'TRN_007': { tr: 'Çeviri feed_lang ile aynı dilde', en: 'Translation in same language as feed_lang' },
  'TRN_008': { tr: 'translation değeri boş', en: 'translation value is empty' },
  'TRN_009': { tr: 'record_id ve field_value aynı anda kullanılamaz', en: 'record_id and field_value cannot be used together' },
  'TRN_010': { tr: 'record_sub_id geçersiz', en: 'record_sub_id invalid' },
  'TRN_011': { tr: 'field_name çevrilebilir değil', en: 'field_name is not translatable' },
  'TRN_013': { tr: "feed_info çevirisinde kimlik alanı kullanılamaz", en: 'Identity field cannot be used in feed_info translation' },
  'TRN_014': { tr: 'record_sub_id yalnızca stop_times için geçerli', en: 'record_sub_id only valid for stop_times' },

  // ATR
  'ATR_001': { tr: 'attribution_id eksik', en: 'attribution_id missing' },
  'ATR_002': { tr: 'organization_name eksik', en: 'organization_name missing' },
  'ATR_003': { tr: 'Attribution rolü tanımlanmamış', en: 'Attribution role not defined' },
  'ATR_004': { tr: 'is_producer geçersiz', en: 'is_producer invalid' },
  'ATR_005': { tr: 'is_operator geçersiz', en: 'is_operator invalid' },
  'ATR_006': { tr: 'is_authority geçersiz', en: 'is_authority invalid' },
  'ATR_007': { tr: 'attribution_url geçersiz', en: 'attribution_url invalid' },
  'ATR_008': { tr: 'attribution_email geçersiz', en: 'attribution_email invalid' },
  'ATR_009': { tr: 'attribution_phone geçersiz', en: 'attribution_phone invalid' },
  'ATR_010': { tr: 'agency_id bulunamadı', en: 'agency_id not found' },

  // XFL
  'XFL_001': { tr: "calendar ve calendar_dates'te service_id yok", en: 'service_id missing from both calendar and calendar_dates' },
  'XFL_002': { tr: 'Seferin stop_times kaydı yok', en: 'Trip has no stop_times records' },
  'XFL_003': { tr: 'shape_id tanımsız', en: 'shape_id undefined' },
  'XFL_004': { tr: "fare_rules'ta tanımsız route_id", en: 'Undefined route_id in fare_rules' },
  'XFL_005': { tr: "stop_times'ta tanımsız stop_id", en: 'Undefined stop_id in stop_times' },
  'XFL_006': { tr: 'service_id yalnızca iptal istisnası içeriyor (aktif gün yok)', en: 'service_id contains only cancellation exceptions (no active days)' },
  'XFL_007': { tr: 'agency_id bulunamadı', en: 'agency_id not found' },
  'XFL_009': { tr: 'level_id geçersiz', en: 'level_id invalid' },
  'XFL_010': { tr: "frequencies'te tanımsız trip_id", en: 'Undefined trip_id in frequencies' },
  'XFL_011': { tr: 'Takvim tarihleri feed_info aralığı dışında', en: 'Calendar dates outside feed_info range' },
  'XFL_012': { tr: 'Hat hiç kullanılmıyor', en: 'Route never used' },
  'XFL_013': { tr: 'shape_id birden fazla yönde kullanılıyor', en: 'shape_id used in multiple directions' },
  'XFL_014': { tr: 'Geçersiz çeviri referansı (kaynak kayıt bulunamadı)', en: 'Invalid translation reference (source record not found)' },
  'XFL_015': { tr: "Attribution'da geçersiz referans", en: 'Invalid reference in attribution' },
  'XFL_016': { tr: "Çeviri feed_info'ya referans veriyor ama feed_info.txt eksik", en: 'Translation references feed_info but feed_info.txt is missing' },
  'XFL_017': { tr: 'route_cemv_support ile agency_cemv_support çelişiyor', en: 'route_cemv_support conflicts with agency_cemv_support' },
  'XFL_018': { tr: 'feed_info.txt eksik', en: 'feed_info.txt missing' },
  'XFL_019': { tr: 'Ağ tanımı iki ayrı dosyada (routes.network_id + route_networks.txt)', en: 'Network defined in two separate files (routes.network_id + route_networks.txt)' },
  'XFL_020': { tr: "Transfers'de geçersiz (from_trip_id/to_trip_id, route_id) çifti", en: 'Invalid (from_trip_id/to_trip_id, route_id) pair in transfers' },
  'XFL_021': { tr: "Transfers'de geçersiz (from_trip_id/to_trip_id, stop_id) çifti", en: 'Invalid (from_trip_id/to_trip_id, stop_id) pair in transfers' },

  // OPR
  'OPR_001': { tr: 'Hat sefer sıklığı düşük', en: 'Route headway too long' },
  'OPR_003': { tr: 'Sefer sıkışması (minimum aralık çok küçük)', en: 'Trip bunching (minimum headway too small)' },
  'OPR_004': { tr: 'Hafta sonu sefer yok', en: 'No weekend service' },
  'OPR_005': { tr: 'Rota ortalama sefer aralığı', en: 'Route average headway' },
  'OPR_006': { tr: 'Seferde çok az durak (işlevsel değil)', en: 'Trip has too few stops (not functional)' },
  'OPR_007': { tr: 'Sefer içinde tekrarlayan durak', en: 'Repeated stop within trip' },
  'OPR_008': { tr: 'Birden fazla segmentte aşırı hız', en: 'Excessive speed in multiple segments' },
  'OPR_009': { tr: 'Gece seferi başlangıç saati çok geç', en: 'Night trip start time too late' },
  'OPR_010': { tr: 'Hatta erişilebilirlik veya bisiklet politikası çelişiyor', en: 'Route accessibility or bicycle policy conflicts' },
  'OPR_011': { tr: 'Serviste aktif gün yok', en: 'Service has no active days' },
  'OPR_012': { tr: 'Servis boşluğu', en: 'Service gap' },
  'OPR_013': { tr: 'Hat tek yönde işliyor (karşı yön tanımlı değil)', en: 'Route operates in one direction only (no return direction)' },
  'OPR_014': { tr: 'Ortalama aktarma süresi uzun', en: 'Average transfer time too long' },
  'OPR_015': { tr: 'Hat yalnızca tek güzergahla işliyor', en: 'Route operates with a single shape only' },
  'OPR_016': { tr: 'Feed genelinde aktif servis yok', en: 'No active service across the entire feed' },
  'OPR_017': { tr: 'Sefer çok kısa mesafe', en: 'Trip distance too short' },
  'OPR_018': { tr: 'Servis dönemi çok kısa', en: 'Service period too short' },
  'OPR_019': { tr: 'Rota takvim çakışması (aynı günde birden fazla servis)', en: 'Route calendar overlap (multiple services on same day)' },
  'OPR_020': { tr: 'Rota exception günü çakışması', en: 'Route exception day overlap' },
  'OPR_021': { tr: 'Takvim override çakışması: override ve base eş zamanlı aktif', en: 'Calendar override conflict: override and base simultaneously active' },
  'OPR_022': { tr: 'Takvim override uygulanmamış: override gününde base servis çalışıyor', en: 'Calendar override not applied: base service running on override day' },
  'OPR_023': { tr: 'Takvim override boşluğu: pencere içinde hiçbir servis aktif değil', en: 'Calendar override gap: no service active within window' },

  // GEO
  'GEO_002': { tr: 'Durak feed medianından çok uzakta', en: 'Stop too far from feed median' },
  'GEO_006': { tr: 'Güzergah şeklinde büyük atlama', en: 'Large jump in shape' },
  'GEO_007': { tr: 'Güzergah şeklinde kritik atlama (3× eşik)', en: 'Critical jump in shape (3× threshold)' },
  'GEO_009': { tr: 'Durak shape güzergahından çok uzakta', en: 'Stop too far from shape route' },
  'GEO_012': { tr: 'Duraksallar kümelenmesi (çok yakın duraklar)', en: 'Stop cluster (stops too close together)' },
  'GEO_013': { tr: 'Feed coğrafi kapsam özeti', en: 'Feed geographic coverage summary' },
  'GEO_014': { tr: 'Feed coğrafi kapsamı çok geniş', en: 'Feed geographic coverage too wide' },

  // DQ
  'DQ_001':  { tr: 'Feed adı eksik', en: 'Feed name missing' },
  'DQ_002':  { tr: 'feed_publisher_url eksik', en: 'feed_publisher_url missing' },
  'DQ_003':  { tr: 'Hat açıklaması eksik', en: 'Route description missing' },
  'DQ_004':  { tr: "Hat URL'si eksik", en: 'Route URL missing' },
  'DQ_005':  { tr: 'Geçerli servis dönemi yok', en: 'No valid service period' },
  'DQ_005b': { tr: 'Hiçbir seferin durak zamanı yok', en: 'No trip has stop times' },
  'DQ_005c': { tr: 'Koordinatsız durak oranı çok yüksek', en: 'High proportion of stops without coordinates' },
  'DQ_006':  { tr: 'Şekil olmayan sefer oranı çok yüksek', en: 'High proportion of trips without shapes' },
  'DQ_009':  { tr: 'Seferlerde durak zamanı yok', en: 'No stop times in trips' },
  'DQ_010':  { tr: 'Acente hiçbir hatta kullanılmıyor', en: 'Agency not used by any route' },
  'DQ_011':  { tr: 'Yalnızca bir durak var', en: 'Only one stop exists' },
  'DQ_012':  { tr: 'Çok fazla acente, agency_id kullanılmıyor', en: 'Too many agencies, agency_id not used' },
  'DQ_013':  { tr: 'Çok az sefer', en: 'Too few trips' },
  'DQ_016':  { tr: 'Değerde fazladan boşluk karakteri', en: 'Extra whitespace in field value' },
  'DQ_017':  { tr: 'Şüpheli koordinat değeri', en: 'Suspicious coordinate value' },
  'DQ_018':  { tr: 'Önerilen alanda tamamen büyük harf (all-caps)', en: 'All-caps value in recommended field' },
  'DQ_019':  { tr: 'Önerilen alanda tamamen küçük harf (all-lowercase)', en: 'All-lowercase value in recommended field' },
  'DQ_020':  { tr: 'Önerilen alan eksik veya boş', en: 'Recommended field missing or empty' },
  'DQ_021':  { tr: 'Birincil anahtar yineleniyor (duplicate_key)', en: 'Primary key duplicate (duplicate_key)' },

  // VAT
  'VAT_001': { tr: 'Hat güzergah benzerliği (muhtemel kopya hat)', en: 'Route shape similarity (likely duplicate route)' },
  'VAT_002': { tr: 'Aktarma merkezi tanımsız — çok sayıda hat geçiyor ama aktarma yok', en: 'Transfer hub undefined — many routes pass but no transfers defined' },
  'VAT_003': { tr: 'Sefer süresi istatistiksel aykırı değer', en: 'Trip duration statistical outlier' },
  'VAT_004': { tr: 'Hat hizmet asimetrisi — hat yalnızca hafta içi çalışıyor', en: 'Route service asymmetry — route only operates on weekdays' },
  'VAT_005': { tr: 'İzole durak kümesi — ağ grafiğinde ana bileşenden kopuk duraklar', en: 'Isolated stop cluster — stops disconnected from main network component' },
  'VAT_006': { tr: 'Hizmet yoğunluğu dengesizliği — tek hat feed sefer sayısının büyük bölümünü oluşturuyor', en: 'Service density imbalance — single route accounts for large proportion of feed trips' },
  'VAT_007': { tr: 'Terminus aktarma eksikliği — terminal durağa başka hat geliyor ama aktarma tanımlı değil', en: 'Terminal transfer missing — another route serves the terminus but no transfer defined' },
};

export function getRuleTitle(ruleId: string, locale: string): string {
  const entry = RULE_TITLES[ruleId];
  if (!entry) return ruleId;
  return (entry as Record<string, string>)[locale] ?? entry.tr;
}
