[package]
name = "gtfs-cli"
version = "0.7.0"
edition = "2021"
license.workspace = true

[[bin]]
name = "gtfs-analyzer"
path = "src/main.rs"

[dependencies]
gtfs-core = { path = "../core" }
gtfs-pipeline = { path = "../pipeline" }
gtfs-config = { path = "../config" }
gtfs-rules = { path = "../rules" }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"] }
chrono = "0.4"

[dev-dependencies]
zip = { workspace = true }
