use gtfs_core::DedupLevel::{Entity, Feed, Field, File, Row};
use gtfs_core::ReportId::{R1, R2, R3, R4, R5, R7, R8, R9};
use gtfs_core::RuleClass::{Analytics, Interop, Quality, Spec};
use gtfs_core::Severity::{Bilgi, Dusuk, Kritik, Orta, Yuksek};
use gtfs_core::AuthoritySource::{
    GtfsBestPractice, GtfsSpec, MobilitydataParity, ProjectAnalytics, ProjectQuality,
    RegionalProfile,
};
use gtfs_core::{AuthoritySource, DedupLevel, ReportId, RuleClass, Severity};

// ── Statik rapor görünüm kümeleri ────────────────────────────────────────────
//
// R1 → blocker/conditional_blocker: KRİTİK+(Spec|Interop) veya YÜKSEK+Interop
// R2 → tüm notice'lar (filtrelenebilir)
// R3 → ANALYTICS sınıfı
// R4 → GEO ailesi + SHP_014/016 (coğrafi doğruluk)
// R5 → genel skor (tüm sınıflar; Spec×40%+Interop×30%+Quality×20%+Analytics×10%)
// R7 → erişilebilirlik (wheelchair_*, stop_access, PTH_012/013)
// R8 → yalnızca INTEROP sınıfı
// R9 → remediation queue (tüm sınıflar dahil ANALYTICS)

/// Spec + KRİTİK → Blocker → R1
const VS_K: &[ReportId] = &[R1, R2, R5, R9];
/// Spec veya Quality, non-blocker
const VS: &[ReportId] = &[R2, R5, R9];
/// Interop + KRİTİK veya YÜKSEK → Blocker/ConditionalBlocker → R1 + R8
const VI_K: &[ReportId] = &[R1, R2, R5, R8, R9];
/// Interop + düşük severity (ORTA/DÜŞÜK/BİLGİ) → R8, no R1
const VI: &[ReportId] = &[R2, R5, R8, R9];
/// Analytics → R3 (operasyonel kalite) + R9 (tüm notice'lar)
const VA: &[ReportId] = &[R2, R3, R5, R9];

// Coğrafi ek (R4)
/// Interop + (KRİTİK|YÜKSEK) + Geo → R1+R4+R8
const VI_K_GEO: &[ReportId] = &[R1, R2, R4, R5, R8, R9];
/// Analytics + Geo → R3+R4+R9
const VA_GEO: &[ReportId] = &[R2, R3, R4, R5, R9];

// Erişilebilirlik eki (R7)
/// Interop + (KRİTİK|YÜKSEK) + Accessibility → R1+R7+R8
const VI_K_ACC: &[ReportId] = &[R1, R2, R5, R7, R8, R9];
/// Analytics + Accessibility → R3+R7+R9
const VA_ACC: &[ReportId] = &[R2, R3, R5, R7, R9];
/// Spec/Quality + Accessibility → R7
const VS_ACC: &[ReportId] = &[R2, R5, R7, R9];

pub struct RuleMeta {
    pub id: &'static str,
    pub severity: Severity,
    pub rule_class: RuleClass,
    pub base_effort: u8,
    /// Canonical rule ID'leri — GEO_008/010/011 gibi rapor görünüm ID'leri içermez.
    pub blocks: &'static [&'static str],
    /// Notice üretiminde scope_key'e atanacak GTFS alanı.
    /// Bileşik anahtar gerektiğinde pipe-separated (ör. "from_stop_id|to_stop_id").
    pub scope_key_field: Option<&'static str>,
    /// Bu kuralın notice'larının hangi raporlarda göründüğü.
    pub report_views: &'static [ReportId],
    /// Notice dedup granülaritesi (architecture Bölüm K1).
    pub dedup_level: DedupLevel,
    /// Kural için kısa genel Türkçe başlık — UI'da gösterilir.
    pub title: &'static str,
}

macro_rules! r {
    ($id:expr, $sev:expr, $cls:expr, $effort:expr, $blocks:expr, $scope:expr, $views:expr, $dedup:expr, $title:expr) => {
        RuleMeta {
            id: $id,
            severity: $sev,
            rule_class: $cls,
            base_effort: $effort,
            blocks: $blocks,
            scope_key_field: $scope,
            report_views: $views,
            dedup_level: $dedup,
            title: $title,
        }
    };
}

/// Tüm canonical kuralların statik metadata tablosu.
///
/// Kapsam dışı (registry'de YOK):
/// - GEO_008/010/011 — rapor görünüm ID'leri (R4 projeksiyonu, notice üretmez)
/// - GEO_META — ön işlem adımı, kural değil
/// - STM_011 → STM_008, TRP_010 → OPR_007, GEO_001 → GEO_META,
///   GEO_005 → STP_017, DQ_007 → MET_001, DQ_008 → MET_002, DQ_015 → RTS_007
pub static RULES: &[RuleMeta] = &[
    // ── ARC: Arşiv / Dosya Seviyesi ────────────────────────────────────────────
    r!("ARC_001", Kritik, Spec, 1, &[], None, VS_K, Feed,
        "ZIP arşivi açılamadı"),
    r!("ARC_002", Kritik, Quality, 1,
        &["ARC_010","AGN_003","AGN_009","RTS_009","FIN_008","ATR_010","STP_022","DQ_016"],
        None, VS, File,
        "Dosya UTF-8 ile okunamıyor"),
    r!("ARC_003", Orta,   Quality, 1, &[], None, VS, File,
        "İsteğe bağlı dosyada UTF-8 kodlama hatası"),
    r!("ARC_004", Kritik, Spec, 1,
        &["XFL_007","XFL_005","XFL_002","DQ_005","DQ_005b"],
        None, VS_K, Feed,
        "Zorunlu dosya eksik"),
    r!("ARC_006", Bilgi,  Quality, 1, &[], None, VS, File,
        "İsteğe bağlı GTFS dosyası mevcut"),
    r!("ARC_007", Bilgi,  Quality, 1, &[], None, VS, File,
        "GTFS dışı tanınmayan dosya"),
    r!("ARC_008", Kritik, Spec,    1, &[], None, VS_K, Feed,
        "Takvim dosyası eksik (calendar.txt ve calendar_dates.txt)"),
    r!("ARC_009", Kritik, Quality, 1, &[], None, VS, File,
        "Dosyada veri satırı yok"),
    r!("ARC_010", Orta,   Interop, 1, &[], None, VI, File,
        "Dosya UTF-8 BOM içeriyor"),
    r!("ARC_011", Bilgi,  Analytics, 1, &[], None, VA, File,
        "Dosya boyutu (bilgi)"),
    r!("ARC_012", Kritik, Spec,    1, &["ARC_015"], None, VS_K, Row,
        "Satır sütun sayısı başlıkla uyuşmuyor"),
    r!("ARC_013", Kritik, Spec,    1,
        &["AGN_003","RTS_005","STM_005","STM_006"],
        None, VS_K, File,
        "CSV ayrıştırma hatası"),
    r!("ARC_014", Orta,   Quality, 1, &[], None, VS, Field,
        "Başlıkta baştaki/sondaki boşluk"),
    r!("ARC_015", Kritik, Quality, 1, &[], None, VS, Field,
        "Yinelenen başlık sütunu"),
    r!("ARC_025", Kritik, Spec,    1, &[], None, VS_K, Field,
        "Zorunlu sütun başlıkta hiç yok (header'da eksik)"),
    r!("ARC_017", Bilgi,  Quality, 1, &[], None, VS, Field,
        "Bilinmeyen sütun (GTFS spesifikasyonunda tanımlı değil)"),
    r!("ARC_018", Orta,   Quality, 1, &[], None, VS, Row,
        "Boş veri satırı"),
    r!("ARC_019", Yuksek, Quality, 1, &[], None, VS, File,
        "Başlıkta boş sütun adı"),
    r!("ARC_020", Dusuk,  Quality, 1, &[], None, VS, Feed,
        "Önerilen GTFS dosyası eksik (shapes.txt veya feed_info.txt)"),
    r!("ARC_021", Dusuk,  Quality, 1, &[], None, VS, File,
        "Alanda yazdırılamaz veya sorunlu karakter"),
    r!("ARC_022", Dusuk,  Quality, 1, &[], None, VS, File,
        "Dosya satır sayısı 1.000.000 sınırını aşıyor"),
    r!("ARC_023", Orta,   Quality, 2, &[], None, VS, File,
        "ZIP içinde nested ZIP dosyası — GTFS formatında desteklenmez"),
    r!("ARC_024", Orta,   Spec,    2, &[], None, VS, File,
        "GTFS .txt dosyası ZIP içinde alt dizinde — standart parser'lar tarafından atlanır"),
    r!("ARC_026", Orta, Interop, 1, &[], None, VI, File,
        "Dosyada hatalı satır sonu karakteri"),
    r!("ARC_027", Bilgi, Interop, 1, &[], None, VI, File,
        "ZIP girdisinde kullanıcı okuma izni yok"),
    r!("ARC_028", Dusuk, Quality, 1, &[], None, VS, Feed,
        "GTFS yayın URL'si .zip dosya adıyla bitmiyor"),
    r!("ARC_029", Kritik, Spec, 1, &[], None, VS_K, File,
        "Sıkıştırma koruması: arşiv zip-bomb sınırını aştı"),

    // ── BKR: Booking Rules ─────────────────────────────────────────────────────
    r!("BKR_001", Yuksek, Spec, 1, &[], Some("booking_rule_id"), VS, Entity,
        "Önceki gün rezervasyon alanı yasak bağlamda dolu"),
    r!("BKR_002", Yuksek, Spec, 1, &[], Some("booking_rule_id"), VS, Entity,
        "prior_notice_start_day yalnızca prior_notice_last_day ile kullanılabilir"),
    r!("BKR_003", Yuksek, Spec, 1, &[], Some("booking_rule_id"), VS, Entity,
        "prior_notice_start_time yalnızca prior_notice_start_day ile kullanılabilir"),
    r!("BKR_004", Yuksek, Spec, 1, &[], Some("booking_rule_id"), VS, Entity,
        "Anlık rezervasyonda prior_notice alanları yasak"),
    r!("BKR_005", Orta,   Spec, 1, &[], Some("booking_rule_id"), VS, Entity,
        "prior_notice_duration_max yalnızca booking_type=1 ile geçerli (booking_type=0/2 ile yasak)"),
    r!("BKR_006", Yuksek, Spec, 1, &[], Some("booking_rule_id"), VS, Entity,
        "prior_notice_duration_min geçersiz (≤ 0 veya sayısal değil)"),
    r!("BKR_007", Kritik, Spec, 1, &[], Some("booking_rule_id"), VS_K, Entity,
        "booking_type=1 için prior_notice_duration_min zorunlu"),
    r!("BKR_008", Kritik, Spec, 1, &[], Some("booking_rule_id"), VS_K, Entity,
        "booking_type=2 için prior_notice_last_day zorunlu"),
    r!("BKR_009", Kritik, Spec, 1, &[], Some("booking_rule_id"), VS_K, Entity,
        "booking_type=2 için prior_notice_last_time zorunlu"),
    r!("BKR_010", Yuksek, Spec, 1, &[], Some("booking_rule_id"), VS, Entity,
        "prior_notice_start_day belirtilmişse prior_notice_start_time zorunlu"),
    r!("BKR_011", Yuksek, Interop, 1, &[], Some("booking_rule_id"), VI, Entity,
        "prior_notice_last_day > prior_notice_start_day: rezervasyon penceresi geçersiz"),

    // ── AGN: Agency ────────────────────────────────────────────────────────────
    r!("AGN_001", Kritik, Spec, 1,
        &["RTS_002","XFL_007"], None, VS_K, Feed,
        "agency.txt dosyası eksik"),
    r!("AGN_002", Kritik, Spec, 1, &[], Some("agency_id"), VS_K, Entity,
        "agency_name eksik"),
    r!("AGN_003", Kritik, Spec, 1, &[], Some("agency_id"), VS_K, Entity,
        "agency_url eksik veya geçersiz"),
    r!("AGN_004", Kritik, Spec, 1, &[], Some("agency_id"), VS_K, Entity,
        "agency_timezone eksik veya geçersiz"),
    r!("AGN_005", Orta,   Quality, 1, &[], None, VS, Feed,
        "Kuruluşlar arası saat dilimi tutarsızlığı"),
    r!("AGN_006", Dusuk,  Spec, 1, &[], Some("agency_id"), VS, Entity,
        "agency_lang geçersiz"),
    r!("AGN_007", Dusuk,  Quality, 1, &[], Some("agency_id"), VS, Entity,
        "agency_phone geçersiz"),
    r!("AGN_008", Dusuk,  Spec, 1, &[], Some("agency_id"), VS, Entity,
        "agency_fare_url geçersiz"),
    r!("AGN_009", Dusuk,  Spec, 1, &[], Some("agency_id"), VS, Entity,
        "agency_email geçersiz"),
    r!("AGN_010", Kritik, Spec, 1, &[], Some("agency_id"), VS_K, Entity,
        "agency_id yineleniyor"),
    r!("AGN_011", Kritik, Spec, 1, &[], None, VS_K, Feed,
        "Birden fazla kuruluşta agency_id yok"),
    r!("AGN_012", Dusuk,  Quality, 1, &[], Some("agency_id"), VS, Entity,
        "agency_cemv_support geçersiz"),
    r!("AGN_013", Dusuk,  Interop, 1, &[], None, VI, Feed,
        "Feed dili ve ajans dili uyuşmuyor"),
    r!("AGN_014", Kritik, Spec, 1, &[], None, VS_K, Entity,
        "Birden fazla kuruluş var ama agency.txt'de agency_id eksik"),
    r!("AGN_015", Bilgi,  Quality, 1, &[], Some("agency_url"), VS, Entity,
        "agency_url güvensiz http kullanıyor (https önerilir)"),
    r!("AGN_016", Bilgi,  Quality, 1, &[], Some("agency_phone"), VS, Entity,
        "agency_phone bilinen yer-tutucu/şüpheli numara"),
    r!("AGN_017", Dusuk,  Interop, 1, &[], None, VI, Feed,
        "Birden çok agency farklı agency_lang taşıyor — diller arası tutarsızlık"),

    // ── STP: Stops ─────────────────────────────────────────────────────────────
    r!("STP_001", Kritik, Spec, 1,
        &["STP_009","STM_002","XFL_005","PTH_002","PTH_003","GEO_002"],
        Some("stop_id"), VS_K, Entity,
        "stop_id yineleniyor"),
    r!("STP_002", Kritik, Spec, 1, &[], Some("stop_id"), VS_K, Entity,
        "stop_id boş"),
    r!("STP_003", Kritik, Spec, 2,
        &["STP_021","GEO_002","GEO_009","GEO_012","STP_016","STP_017"],
        Some("stop_id"), VS_K, Entity,
        "stop_name eksik veya stop_lat/stop_lon aralık dışı (aynı ID altında iki ayrı koşul)"),
    r!("STP_004", Kritik, Spec, 2,
        &["STP_021","GEO_002","GEO_009","GEO_012","STP_016","STP_017"],
        Some("stop_id"), VS_K, Entity,
        "stop_lat sayısal değil"),
    r!("STP_005", Kritik, Quality, 2, &[], Some("stop_id"), VS, Entity,
        "stop_lon geçersiz veya aralık dışı"),
    r!("STP_006", Kritik, Spec, 2,
        &["GEO_002","GEO_009","GEO_012","STP_016","STP_017"],
        Some("stop_id"), VS_K, Entity,
        "stop_lat eksik"),
    r!("STP_007", Kritik, Spec, 2,
        &["GEO_002","GEO_009","GEO_012","STP_016","STP_017"],
        Some("stop_id"), VS_K, Entity,
        "stop_lon eksik"),
    r!("STP_008", Yuksek, Spec, 1,
        &["STP_010","STP_011","STP_012","TRF_015"],
        Some("stop_id"), VS, Entity,
        "location_type geçersiz"),
    r!("STP_009", Kritik, Spec, 1,
        &["STP_010","STP_011","PTH_002","PTH_003","PTH_012"],
        Some("stop_id"), VS_K, Entity,
        "parent_station bulunamadı"),
    r!("STP_010", Yuksek, Spec, 1, &[], Some("stop_id"), VS, Entity,
        "parent_station location_type=1 değil"),
    r!("STP_011", Kritik, Spec, 1, &[], Some("stop_id"), VS_K, Entity,
        "Giriş/çıkış/boarding için parent_station zorunlu"),
    r!("STP_012", Kritik, Spec, 1, &[], Some("stop_id"), VS_K, Entity,
        "stop_times'ta istasyon veya giriş kullanılmış"),
    r!("STP_013", Dusuk,  Spec, 1, &[], Some("stop_id"), VS_ACC, Entity,
        "wheelchair_boarding geçersiz"),
    r!("STP_014", Orta,   Spec, 1, &[], Some("stop_id"), VS, Entity,
        "stop_timezone geçersiz"),
    r!("STP_015", Orta,   Spec, 1, &[], Some("stop_id"), VS, Entity,
        "level_id bulunamadı"),
    r!("STP_016", Orta,   Quality, 2, &[], Some("stop_id"), VS, Entity,
        "İki durak tam aynı koordinatta"),
    r!("STP_017", Dusuk,  Quality, 1, &[], Some("stop_id"), VS, Entity,
        "İki durak birbirine çok yakın"),
    r!("STP_018", Kritik, Spec, 1, &[], None, VS_K, Feed,
        "Hiç durak yok"),
    r!("STP_019", Dusuk,  Quality, 1, &[], Some("stop_id"), VS, Entity,
        "stop_name çok uzun"),
    r!("STP_020", Orta,   Analytics, 2, &[], Some("stop_id"), VA, Entity,
        "Hiç sefer geçmeyen durak"),
    r!("STP_021", Yuksek, Quality, 2, &[], Some("stop_id"), VS, Entity,
        "Boarding area parent'ı platform değil"),
    r!("STP_022", Orta,   Quality, 1, &[], Some("stop_id"), VS, Entity,
        "stop_code eksik"),
    r!("STP_023", Dusuk,  Quality, 1, &[], Some("stop_id"), VS, Entity,
        "tts_stop_name geçersiz"),
    r!("STP_024", Bilgi,  Quality, 1, &["STP_026"], Some("stop_id"), VS, Entity,
        "stop_access enum aralığı dışında değer (K2 ham alan kontrolü)"),
    r!("STP_025", Orta,   Quality, 1, &[], Some("stop_id"), VS, Entity,
        "stop_name baştaki veya sondaki boşluk içeriyor"),
    r!("STP_026", Dusuk,  Spec, 1,
        &["STP_027","PTH_012"],
        Some("stop_id"), VS_ACC, Entity,
        "stop_access geçersiz değer"),
    r!("STP_027", Orta,   Quality, 1,
        &["PTH_012","PTH_013"],
        Some("stop_id"), VS_ACC, Entity,
        "Pathway istasyonunda stop_access belirtilmemiş"),
    r!("STP_028", Bilgi,  Quality, 1, &[], Some("stop_id"), VS, Entity,
        "stop_code çok uzun"),
    r!("STP_029", Orta, Quality, 2, &[], Some("stop_id"), VS, Entity,
        "Durak istasyon içinde ama koordinat çok uzakta"),
    r!("STP_030", Orta,   Quality, 1, &[], Some("stop_id"), VS, Entity,
        "Üst istasyonun alt durağı yok"),
    r!("STP_031", Bilgi,  Quality, 1, &[], Some("stop_id"), VS, Entity,
        "Durak adı ve açıklaması aynı"),
    r!("STP_032", Orta,   Quality, 2, &[], Some("stop_id"), VS, Entity,
        "Pathway bağlantılı platform için parent_station eksik"),
    r!("STP_033", Bilgi,  Quality, 1, &[], Some("stop_id"), VS, Entity,
        "Durak zone_id eksik (ücret hesabı için gerekli)"),
    r!("STP_034", Bilgi,  Quality, 1, &[], Some("stop_id"), VS, Entity,
        "stop_url acente URL'siyle aynı"),
    r!("STP_035", Bilgi,  Quality, 1, &[], Some("stop_id"), VS, Entity,
        "stop_url hat URL'siyle aynı"),
    r!("STP_036", Dusuk,  Spec, 1, &[], Some("stop_id"), VS, Entity,
        "İstasyonun (location_type=1) parent_station'ı var"),
    r!("STP_037", Orta,   Quality, 1, &[], None, VS_ACC, Feed,
        "Bazı duraklar tekerlekli sandalye erişilebilirliği (wheelchair_boarding) bildirmemiş"),
    r!("STP_038", Bilgi,  Quality, 1, &[], None, VS_ACC, Feed,
        "Hiçbir durak tekerlekli sandalye erişilebilirliği (wheelchair_boarding) bildirmemiş"),
    r!("STP_039", Dusuk, Quality, 1, &[], Some("stop_code"), VS, Entity,
        "stop_code birden fazla durakta kullanılıyor"),
    r!("STP_040", Dusuk, Quality, 1, &[], Some("stop_id"), VS, Entity,
        "Durak adı gereksiz genel stop/station sözcüğü içeriyor"),
    r!("STP_041", Dusuk, Quality, 1, &[], Some("stop_id"), VS, Entity,
        "Alt durak adı üst istasyon adını içermiyor"),

    // ── RTS: Routes ────────────────────────────────────────────────────────────
    r!("RTS_001", Kritik, Spec, 1,
        &["TRP_002","XFL_007","FRL_002","ATR_006"],
        Some("route_id"), VS_K, Entity,
        "route_id yineleniyor"),
    r!("RTS_002", Kritik, Spec, 1,
        &["XFL_007"],
        Some("route_id"), VS_K, Entity,
        "agency_id bulunamadı"),
    r!("RTS_003", Kritik, Spec, 1,
        &["TRP_015","DQ_003"],
        Some("route_id"), VS_K, Entity,
        "route_short_name ve route_long_name ikisi de eksik"),
    r!("RTS_004", Kritik, Spec, 1, &[], Some("route_id"), VS_K, Entity,
        "route_type eksik veya geçersiz"),
    r!("RTS_005", Orta,   Spec, 1, &[], Some("route_id"), VS, Entity,
        "route_url geçersiz"),
    r!("RTS_006", Orta,   Spec, 1, &[], Some("route_id"), VS, Entity,
        "route_color geçersiz hex renk"),
    r!("RTS_007", Dusuk,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "route_text_color geçersiz hex renk"),
    r!("RTS_008", Orta,   Quality, 1, &[], Some("route_id"), VS, Entity,
        "Hat rengi ve metin rengi kontrast düşük"),
    r!("RTS_009", Dusuk,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "route_short_name ve route_long_name birbirinin aynısı"),
    r!("RTS_010", Dusuk,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "route_short_name çok uzun"),
    r!("RTS_011", Dusuk,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "route_long_name çok uzun"),
    r!("RTS_012", Orta,   Quality, 1, &[], Some("route_id"), VS, Entity,
        "Seferi olmayan hat"),
    r!("RTS_013", Dusuk,  Spec, 1, &[], Some("route_id"), VS, Entity,
        "continuous_pickup geçersiz"),
    r!("RTS_016", Dusuk,  Quality, 2, &[], Some("route_id"), VS, Entity,
        "Hiçbir aktif servis günü olmayan hat"),
    r!("RTS_017", Bilgi,  Quality, 2, &[], Some("route_id"), VS, Entity,
        "Shape tanımlı olmayan hat"),
    r!("RTS_018", Dusuk,  Spec, 1, &[], Some("route_id"), VS, Entity,
        "continuous_drop_off geçersiz"),
    r!("RTS_019", Orta,   Quality, 1, &[], Some("route_id"), VS, Row,
        "Yinelenen hat adı"),
    r!("RTS_020", Bilgi,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "Hat ve acente aynı URL'yi paylaşıyor"),
    r!("RTS_021", Dusuk, Interop, 1, &[], Some("route_id"), VI, Entity,
        "Kısa hat adı Google Transit eşiğini (6 karakter) aşıyor"),
    r!("RTS_022", Dusuk,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "Uzun hat adı kısa adı içeriyor"),
    r!("RTS_023", Bilgi,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "Uzun hat adı ve açıklaması aynı"),
    r!("RTS_024", Dusuk,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "route_cemv_support geçersiz"),
    r!("RTS_025", Bilgi,  Quality, 1, &[], Some("agency_id"), VS, Entity,
        "routes.txt'te agency_id boş (önerilen alan)"),
    r!("RTS_026", Bilgi,  Quality, 1, &[], Some("route_id"), VS, Row,
        "Yinelenen kısa hat adı"),
    r!("RTS_027", Bilgi,  Quality, 1, &[], Some("route_id"), VS, Row,
        "Yinelenen uzun hat adı"),

    // ── TRP: Trips ─────────────────────────────────────────────────────────────
    r!("TRP_001", Kritik, Spec, 1,
        &["STM_001","FRQ_001","XFL_002","XFL_010","OPR_006","OPR_007"],
        Some("trip_id"), VS_K, Entity,
        "trip_id eksik veya yineleniyor"),
    r!("TRP_002", Kritik, Spec, 1, &[], Some("trip_id"), VS_K, Entity,
        "route_id bulunamadı"),
    r!("TRP_003", Kritik, Spec, 1,
        &["DQ_005","DQ_005b","CAL_009","CAL_012","OPR_011"],
        Some("trip_id"), VS_K, Entity,
        "service_id bulunamadı"),
    r!("TRP_004", Yuksek, Spec, 1,
        &["XFL_003","SHP_014","SHP_016","SHP_017","STM_015","STM_016","STM_027"],
        Some("shape_id"), VS, Entity,
        "shape_id bulunamadı"),
    r!("TRP_005", Orta,   Spec, 1, &[], Some("trip_id"), VS, Entity,
        "direction_id geçersiz"),
    r!("TRP_006", Dusuk,  Spec, 1, &[], Some("trip_id"), VS, Entity,
        "wheelchair_accessible geçersiz"),
    r!("TRP_007", Dusuk,  Spec, 1, &[], Some("trip_id"), VS, Entity,
        "bikes_allowed geçersiz"),
    r!("TRP_032", Dusuk,  Spec, 1, &[], Some("trip_id"), VS, Entity,
        "cars_allowed geçersiz"),
    r!("TRP_009", Yuksek, Quality, 2,
        &["OPR_006","OPR_007"],
        Some("trip_id"), VS, Entity,
        "Seferde zaman damgalı durak yok"),
    r!("TRP_011", Yuksek, Quality, 3, &[], Some("trip_id"), VS, Entity,
        "Sefer yön adı girilmemiş"),
    r!("TRP_012", Dusuk,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "Çift yönlü rotada direction_id eksik"),
    r!("TRP_013", Dusuk,  Quality, 1, &[], Some("route_id"), VS, Entity,
        "Hat tek seferlik"),
    r!("TRP_014", Bilgi,  Quality, 1, &[], Some("trip_id"), VS, Entity,
        "trip_short_name çok uzun"),
    r!("TRP_015", Dusuk,  Quality, 1, &[], Some("trip_id"), VS, Entity,
        "block_id grubunda tek sefer"),
    r!("TRP_017", Orta,   Spec, 1, &[], Some("trip_id"), VS, Entity,
        "Frekans tabanlı sefer stop_times'ta eksik"),
    r!("TRP_019", Yuksek, Quality, 1, &[], Some("trip_id"), VS, Entity,
        "Continuous servis aktifken shape_id eksik"),
    r!("TRP_020", Bilgi,  Analytics, 1, &[], Some("trip_id"), VA, Entity,
        "trip_headsign ara durak adıyla eşleşiyor"),
    r!("TRP_021", Bilgi,  Quality, 1, &[], Some("trip_id"), VS, Entity,
        "Bisiklet izni (bikes_allowed) belirtilmemiş"),
    r!("TRP_022", Yuksek, Interop, 3, &[], Some("trip_id"), VI, Entity,
        "Block içinde çakışan sefer saatleri"),
    // Feed genelinde 7 günde hiç aktif sefer yoksa TRP_023 (feed-level, None scope)
    // tek kök mesajdır ve her sefer için tekrar eden TRP_030 spam'ini bastırır.
    // (Eski yön TRP_030→TRP_023 scope uyumsuzluğundan etkisizdi.)
    r!("TRP_023", Dusuk,  Quality, 1, &["CAL_024"], None, VS, Feed,
        "Önümüzdeki 7 günde aktif sefer yok"),
    r!("TRP_024", Dusuk,  Interop, 1, &[], Some("trip_id"), VI, Entity,
        "Block içinde tutarsız rota tipi"),
    r!("TRP_025", Bilgi,  Quality, 1, &[], None, VS, Feed,
        "Tekerlekli sandalye erişilebilirlik bilgisi eksik seferlerin oranı yüksek"),
    r!("TRP_026", Orta, Analytics, 2, &[], Some("trip_id"), VA, Entity,
        "Aktif tarihi olmayan sefer (service_id geçerli ama aktif gün seti boş)"),
    r!("TRP_028", Orta,  Quality, 1, &[], None, VS, Feed,
        "Bazı seferler tekerlekli sandalye erişilebilirliği işaretlememiş"),
    r!("TRP_029", Bilgi, Quality, 1, &[], None, VS, Feed,
        "Hiçbir sefer tekerlekli sandalye erişilebilirliği bildirmemiş"),
    r!("TRP_031", Kritik, Spec, 1, &[], Some("route_id"), VS_K, Entity,
        "route_id eksik"),

    // ── STM: Stop Times ────────────────────────────────────────────────────────
    r!("STM_001", Kritik, Spec, 1,
        &["STM_008","STM_013","STM_014","STM_027","OPR_001","OPR_008"],
        Some("trip_id"), VS_K, Row,
        "trip_id bulunamadı"),
    r!("STM_002", Kritik, Spec, 1,
        &["STM_007","STM_012","GEO_002","OPR_014"],
        Some("stop_id"), VS_K, Row,
        "stop_id bulunamadı"),
    r!("STM_003", Kritik, Spec, 1,
        &["STM_004","STM_008","STM_027","SHP_014"],
        Some("trip_id"), VS_K, Row,
        "arrival_time geçersiz format"),
    r!("STM_004", Kritik, Spec, 1,
        &["STM_008","STM_012","STM_027"],
        Some("trip_id"), VS_K, Row,
        "departure_time geçersiz format"),
    r!("STM_005", Kritik, Spec, 2,
        &["STM_008","STM_012","STM_013","STM_014","STM_028","STM_029","OPR_008","OPR_010"],
        Some("trip_id"), VS_K, Row,
        "stop_sequence eksik veya geçersiz"),
    r!("STM_006", Kritik, Spec, 2,
        &["STM_007","STM_008","STM_012","STM_013","STM_014","STM_028","STM_029","OPR_008"],
        Some("trip_id"), VS_K, Row,
        "stop_id eksik (stop_times)"),
    r!("STM_007", Yuksek, Interop, 2, &[], Some("trip_id"), VI, Row,
        "Kalkış saati varış saatinden önce (departure_time < arrival_time)"),
    r!("STM_008", Kritik, Interop, 2, &[], Some("trip_id"), VI, Row,
        "Duraklar arası zaman geriye gidiyor"),
    r!("STM_009", Yuksek, Spec, 1, &[], Some("trip_id"), VS, Row,
        "pickup_type geçersiz"),
    r!("STM_010", Yuksek, Spec, 1, &[], Some("trip_id"), VS, Row,
        "drop_off_type geçersiz"),
    r!("STM_012", Yuksek, Interop, 2, &[], Some("trip_id"), VI_K, Row,
        "Duraklar arası hız gerçekçi değil"),
    r!("STM_013", Yuksek, Quality, 2, &[], Some("trip_id"), VS, Row,
        "Karışık varış/kalkış zamanları"),
    r!("STM_014", Yuksek, Analytics, 3, &[], Some("trip_id"), VA, Row,
        "Segmentte aşırı hız"),
    r!("STM_015", Kritik, Spec, 2,
        &["STM_016","STM_017","XFL_013","SHP_017"],
        Some("trip_id"), VS_K, Row,
        "İlk duraklama noktası yok"),
    r!("STM_016", Kritik, Spec, 2, &[], Some("trip_id"), VS_K, Row,
        "Son duraklama noktası yok"),
    r!("STM_017", Orta,   Interop, 3, &[], Some("trip_id"), VI, Row,
        "Sefer saatlerinde güzergah mesafesi eksik"),
    r!("STM_018", Orta,   Spec, 1, &[], Some("trip_id"), VS, Row,
        "continuous_pickup geçersiz (stop_times)"),
    r!("STM_019", Orta,   Spec, 1, &[], Some("trip_id"), VS, Row,
        "continuous_drop_off geçersiz (stop_times)"),
    r!("STM_020", Yuksek, Quality, 3, &[], Some("trip_id"), VS, Row,
        "Sıfır geçiş süresi (mesafe > 200m)"),
    r!("STM_021", Yuksek, Quality, 3, &[], Some("trip_id"), VS, Row,
        "Duraklar arası mesafe sıfır veya negatif"),
    r!("STM_022", Orta,   Spec, 1, &[], Some("trip_id"), VS, Row,
        "timepoint geçersiz"),
    r!("STM_023", Dusuk, Quality, 3, &[], Some("trip_id"), VS, Row,
        "stop_times satır sıralaması bozuk"),
    r!("STM_024", Bilgi,  Quality, 2, &[], Some("trip_id"), VS, Row,
        "shape_dist_traveled birim tutarsızlığı"),
    r!("STM_025", Bilgi,  Analytics, 2, &[], Some("trip_id"), VA, Row,
        "Kısa segment zamanlaması"),
    r!("STM_026", Yuksek, Quality, 2, &[], Some("trip_id"), VS, Row,
        "Durak arası mesafe aşırı uzun"),
    r!("STM_027", Yuksek, Interop, 3, &[], Some("trip_id"), VI_K, Row,
        "shape_dist_traveled monoton artmıyor"),
    r!("STM_028", Yuksek, Analytics, 2, &[], Some("trip_id"), VA, Row,
        "Sefer süresi çok uzun"),
    r!("STM_029", Orta,   Analytics, 2, &[], Some("trip_id"), VA, Row,
        "Sefer süresi çok kısa"),
    r!("STM_030", Dusuk,  Spec, 1, &[], Some("trip_id"), VS, Row,
        "shape_dist_traveled negatif"),
    r!("STM_032", Dusuk,  Quality, 1, &[], Some("trip_id"), VS, Row,
        "Aynı seferde yinelenen stop_sequence değeri"),
    r!("STM_033", Yuksek, Spec, 2, &[], Some("trip_id"), VS, Entity,
        "Tek duraklı sefer (kullanılamaz)"),
    r!("STM_034", Orta,   Interop, 2, &[], Some("trip_id"), VI, Row,
        "Varış veya kalkış zamanından yalnızca biri tanımlı"),
    r!("STM_035", Bilgi,  Analytics, 1, &[], Some("trip_id"), VS, Row,
        "Aynı durak ardışık iki kez ziyaret ediliyor (terminal/döngü)"),
    r!("STM_036", Bilgi,  Quality,   2, &[], Some("trip_id"), VS, Entity,
        "stop_times trip_id + stop_sequence'a göre sıralı değil (unsorted_stop_times)"),
    r!("STM_037", Yuksek, Spec, 1, &[], Some("trip_id"), VS, Entity,
        "Flex penceresinde arrival_time/departure_time yasak"),
    r!("STM_038", Yuksek, Interop, 1, &[], Some("trip_id"), VI, Entity,
        "start_pickup_drop_off_window > end_pickup_drop_off_window"),
    r!("STM_039", Kritik, Spec, 1, &[], Some("trip_id"), VS_K, Entity,
        "Flex bağlamında pickup/drop_off penceresi eksik"),
    r!("STM_040", Kritik, Spec, 1, &[], Some("trip_id"), VS_K, Entity,
        "Flex stop_times'ta pickup/drop_off_booking_rule_id eksik"),
    r!("STM_041", Yuksek, Spec, 1, &[], Some("trip_id"), VS, Entity,
        "stop_id ile location_id/group_id aynı anda kullanılamaz"),
    r!("STM_042", Dusuk, Interop, 1, &[], Some("trip_id"), VI, Row,
        "stop_headsign Google Transit tarafından desteklenmeyen karakter içeriyor"),
    r!("STM_043", Bilgi,  Analytics, 1, &[], Some("trip_id"), VA, Entity,
        "Sefer aşırı fazla durağa sahip (>200) — olası veri birleştirme hatası"),
    r!("STM_044", Bilgi,  Analytics, 1, &[], None, VA, Feed,
        "Feed stop_times satır sayısı 2 milyonu aşıyor — WASM bellek/performans uyarısı"),
    r!("STM_045", Orta,   Quality,   1, &[], Some("trip_id"), VS, Entity,
        "Seferin hareket saati servis günü penceresini aşıyor — olası veri anomalisi"),
    r!("STM_046", Kritik, Spec, 1, &[], Some("trip_id"), VS_K, Row,
        "trip_id eksik"),
    r!("STM_047", Kritik, Spec, 1, &[], Some("trip_id"), VS_K, Row,
        "Kesin zaman noktasında (timepoint=1) arrival_time/departure_time eksik"),
    r!("STM_048", Bilgi, Quality, 1, &[], Some("departure_time"), VS, Feed,
        "Gece yarısı sonrası saatler 00:xx yazılmış (24:xx önerilir, duraklar arası)"),
    r!("STM_049", Bilgi, Quality, 1, &[], Some("departure_time"), VS, Feed,
        "Gece yarısı sonrası kalkış 00:xx yazılmış (24:xx önerilir, aynı satır)"),
    r!("STM_050", Dusuk, Quality, 1, &[], None, VS, Feed,
        "timepoint sütunu mevcut ama satırda boş — değer açıkça belirtilmeli (0 yaklaşık / 1 kesin)"),
    r!("STM_051", Yuksek, Spec, 1, &[], Some("trip_id"), VS, Entity,
        "Flex penceresi tanımlıyken pickup_type=0/3 yasak (talep-üzerine değerler gerekli)"),
    r!("STM_052", Yuksek, Spec, 1, &[], Some("trip_id"), VS, Entity,
        "Flex penceresi tanımlıyken drop_off_type=0 yasak (talep-üzerine değer gerekli)"),
    r!("STM_053", Orta, Quality, 2, &[], Some("trip_id"), VS, Entity,
        "Çok sayıda ardışık durakta aynı zaman"),

    // ── PDW: Pickup/Drop-off Window ──────────────────────────────────────────
    r!("PDW_006", Orta, Analytics, 2, &[], Some("trip_id"), VA, Entity,
        "Aynı trip+zone'da örtüşen pickup/drop-off penceresi"),

    // ── LOC: locations.geojson ───────────────────────────────────────────────
    r!("LOC_001", Yuksek, Spec, 2, &[], None, VS, File,
        "locations.geojson'da bilinmeyen veya geçersiz geometri tipi"),
    r!("LOC_002", Kritik, Spec, 2, &[], None, VS_K, File,
        "Feature'da geometry null veya eksik — GTFS Flex gerektiriyor"),
    r!("LOC_003", Kritik, Spec, 2, &[], None, VS_K, File,
        "Feature'da 'id' property eksik — stop_times çapraz referansı için zorunlu"),
    r!("LOC_004", Orta,   Spec, 2, &[], None, VS, File,
        "Polygon ring kapalı değil (ilk != son nokta)"),
    r!("LOC_005", Dusuk,  Quality, 1, &[], None, VS, File,
        "FeatureCollection boş — hiç feature yok"),
    r!("LOC_006", Orta,   Quality, 1, &[], None, VS, File,
        "Polygon yaklaşık kapsamı 500km²'yi aşıyor — gerçekçi olmayan Flex bölge (bounding-box tahmini)"),
    r!("LOC_007", Orta,   Spec,    2, &[], None, VS, File,
        "FeatureCollection içinde yinelenen 'id' değeri — Flex referansı belirsizleşir"),

    // ── CAL: Calendar ──────────────────────────────────────────────────────────
    r!("CAL_001", Kritik, Spec, 1,
        &["TRP_003","XFL_001","CAL_009","DQ_005"],
        Some("service_id"), VS_K, Entity,
        "service_id yineleniyor"),
    r!("CAL_002", Kritik, Spec, 1,
        &["CAL_006","CAL_009","CAL_012","OPR_011","OPR_016","OPR_018"],
        Some("service_id"), VS_K, Entity,
        "Takvim gün alanı geçersiz değer"),
    r!("CAL_003", Kritik, Spec, 2,
        &["CAL_005","CAL_007","CAL_008","CAL_009","CAL_012","DQ_006"],
        Some("service_id"), VS_K, Entity,
        "start_date eksik veya geçersiz format"),
    r!("CAL_004", Kritik, Spec, 2,
        &["CAL_005","CAL_008","CAL_009","CAL_010","CAL_012","FIN_010","DQ_006"],
        Some("service_id"), VS_K, Entity,
        "end_date eksik veya geçersiz format"),
    r!("CAL_005", Kritik, Interop, 2, &[], Some("service_id"), VI, Entity,
        "start_date end_date'den sonra"),
    r!("CAL_006", Bilgi,  Quality, 2, &[], Some("service_id"), VS, Entity,
        "Haftalık bazda tüm günler pasif (calendar_dates ile override mümkün)"),
    r!("CAL_007", Orta,   Analytics, 2, &[], Some("service_id"), VA, Entity,
        "Servis döneminde boşluk"),
    r!("CAL_008", Yuksek, Analytics, 2, &[], Some("service_id"), VA, Entity,
        "Servis tarihi yakında sona eriyor"),
    r!("CAL_009", Kritik, Interop, 2, &[], Some("service_id"), VI_K, Entity,
        "Feed'deki tüm takvim dönemleri sona ermiş"),
    r!("CAL_010", Orta,   Analytics, 2, &[], Some("service_id"), VA, Entity,
        "Serviste aktif gün sayısı çok az"),
    r!("CAL_011", Dusuk,  Quality, 1, &[], Some("service_id"), VS, Entity,
        "Kullanılmayan servis"),
    r!("CAL_012", Bilgi,  Analytics, 2, &[], Some("service_id"), VA, Entity,
        "Yakın gelecekte servis boşluğu var"),
    r!("CAL_013", Bilgi,  Analytics, 1, &[], Some("service_id"), VA, Entity,
        "Geçmiş tarihli servis dönemi"),
    r!("CAL_014", Dusuk,  Quality,   1, &[], Some("service_id"), VS, Entity,
        "Servis tarihleri feed_info geçerlilik aralığı dışında"),
    r!("CAL_015", Dusuk,  Quality,   1, &[], None, VS, Feed,
        "Tüm takvim tarihleri gelecekte (bugün aktif sefer yok)"),
    r!("CAL_016", Bilgi,  Quality,   1, &[], None, VS, Feed,
        "Servis çok uzak bir gelecek tarihine kadar uzanıyor"),
    r!("CAL_017", Dusuk,  Quality,   1, &[], Some("service_id"), VS, Entity,
        "Takvim henüz başlamamış (tüm aktif tarihler gelecekte)"),
    r!("CAL_018", Dusuk,  Quality,   1, &[], Some("service_id"), VS, Entity,
        "Servisin aktif haftanın günü yok (tüm günler 0, calendar_dates ile geçersiz kılınan yok)"),
    r!("CAL_019", Dusuk,  Quality,   1, &[], Some("service_id"), VS, Entity,
        "Ham takvim aralığı feed_info geçerlilik penceresini aşıyor"),
    r!("CAL_020", Dusuk,  Quality,   1, &[], None, VS, Feed,
        "Feed geçerlilik penceresi 5 yılı aşıyor — gerçekçi olmayan zaman dilimi"),
    r!("CAL_021", Bilgi,  Analytics, 1, &[], Some("service_id"), VA, Entity,
        "Servis bugünü kapsıyor ama yakın günlerde aktif sefer yok"),
    r!("CAL_022", Kritik, Spec, 1, &[], Some("service_id"), VS_K, Row,
        "service_id eksik"),
    r!("CAL_023", Orta, Quality, 2, &[], Some("service_id"), VA, Entity,
        "end_date çok ileri (şüpheli uzak-gelecek tarih)"),
    // CAL_024: eski TRP_030 (takvim odaklı olduğu için #23 ile CAL grubuna taşındı).
    r!("CAL_024", Dusuk, Quality, 1, &[], Some("service_id"), VS, Entity,
        "Takvim önümüzdeki 7 günde aktif değil"),

    // ── CLD: Calendar Dates ────────────────────────────────────────────────────
    r!("CLD_001", Kritik, Spec, 1, &[], Some("service_id"), VS_K, Row,
        "service_id eksik"),
    r!("CLD_002", Kritik, Spec, 2, &[], Some("service_id"), VS_K, Row,
        "date eksik veya geçersiz format"),
    r!("CLD_003", Kritik, Spec, 1,
        &["CLD_005","CLD_006","CLD_007"],
        Some("service_id"), VS_K, Row,
        "exception_type eksik veya geçersiz"),
    r!("CLD_004", Yuksek, Interop, 2, &[], Some("service_id"), VI_K, Row,
        "calendar_dates-only serviste aktif gün (exception_type=1) tanımlı değil"),
    r!("CLD_005", Kritik, Quality, 2, &[], Some("service_id"), VS, Row,
        "Tarih makul yıl aralığı dışında"),
    r!("CLD_006", Orta,   Quality, 1, &[], Some("service_id"), VS, Row,
        "Çok fazla istisna günü"),
    r!("CLD_007", Bilgi,  Analytics, 1, &[], Some("service_id"), VA, Row,
        "Aşırı takvim istisnası"),

    // ── SHP: Shapes ────────────────────────────────────────────────────────────
    r!("SHP_001", Kritik, Spec, 1, &[], Some("shape_id"), VS_K, Entity,
        "shape_id eksik"),
    r!("SHP_002", Kritik, Spec, 1,
        &["SHP_003","SHP_014","SHP_016","SHP_017"],
        Some("shape_id"), VS_K, Entity,
        "shape_pt_lat eksik veya geçersiz"),
    r!("SHP_003", Kritik, Spec, 1, &[], Some("shape_id"), VS_K, Entity,
        "shape_pt_lon eksik veya geçersiz"),
    r!("SHP_004", Kritik, Spec, 2,
        &["SHP_009","SHP_011","SHP_012","GEO_006","GEO_007"],
        Some("shape_id"), VS_K, Row,
        "shape_pt_sequence eksik veya geçersiz"),
    r!("SHP_005", Kritik, Spec, 2,
        &["SHP_009","SHP_011","SHP_012","GEO_006","GEO_007"],
        Some("shape_id"), VS_K, Row,
        "shape_dist_traveled geriye gidiyor"),
    r!("SHP_006", Orta,   Quality, 2,
        &["SHP_017","STM_015","STM_016"],
        Some("shape_id"), VS, Entity,
        "Güzergah şekli yalnızca tek noktadan oluşuyor"),
    r!("SHP_008", Kritik, Spec, 3, &[], Some("shape_id"), VS_K, Entity,
        "shape_pt_sequence yineleniyor"),
    r!("SHP_009", Bilgi,  Analytics, 3, &[], Some("shape_id"), VA, Entity,
        "Güzergah şekli kendisiyle kesişiyor"),
    r!("SHP_010", Dusuk,  Quality, 1, &[], Some("shape_id"), VS, Entity,
        "Tekrarlanan shape noktası (ardışık özdeş koordinat)"),
    r!("SHP_011", Orta,   Analytics, 2, &[], Some("shape_id"), VA, Entity,
        "Güzergah şeklinde büyük boşluk"),
    r!("SHP_012", Yuksek, Analytics, 3, &[], Some("shape_id"), VA, Entity,
        "Güzergah şekli sefer duraklarından çok uzak"),
    r!("SHP_014", Bilgi,  Analytics, 3, &[], Some("shape_id"), VA_GEO, Entity,
        "İlk veya son durak güzergah ucundan uzakta"),
    r!("SHP_015", Orta,   Quality, 2, &[], Some("shape_id"), VS, Entity,
        "Güzergah şekli istatistiksel olarak çok az nokta"),
    r!("SHP_016", Yuksek, Interop, 2, &[], Some("shape_id"), VI_K_GEO, Entity,
        "Güzergah şekli yön bilgisiyle uyumsuz"),
    r!("SHP_017", Bilgi,  Analytics, 3, &[], Some("shape_id"), VA_GEO, Entity,
        "Durak sırası güzergah şekliyle çelişiyor"),
    r!("SHP_018", Dusuk,  Quality, 1, &[], Some("shape_id"), VS, Entity,
        "Güzergah şekli sefer tarafından referanslanmıyor"),
    r!("SHP_019", Orta,   Quality, 2, &[], Some("shape_id"), VS, Entity,
        "Güzergah şeklinin seferleri durak zamanı içermiyor"),
    r!("SHP_020", Bilgi,  Analytics, 3, &[], Some("shape_id"), VA, Entity,
        "Güzergah şeklinde tekrarlayan nokta"),
    r!("SHP_021", Dusuk,  Quality, 1, &[], Some("shape_id"), VS, Entity,
        "shape_dist_traveled negatif değer"),
    r!("SHP_022", Yuksek, Interop, 2, &[], Some("stop_id"), VI_K, Entity,
        "Durak güzergah şeklinde belirsiz konumda"),
    r!("SHP_023", Orta,   Quality, 2, &[], Some("shape_id"), VS, Entity,
        "shape_dist_traveled aynı değere sahip art arda iki nokta aynı koordinatta"),
    r!("SHP_024", Orta,   Quality, 2, &[], Some("stop_id"), VS, Entity,
        "Duraktan şekle mesafe shape_dist_traveled ile tutarsız"),
    r!("SHP_025", Orta,   Quality, 2, &[], Some("trip_id"), VS, Entity,
        "Sefer stop_times mesafesi şeklin toplam mesafesini aşıyor"),
    r!("SHP_026", Bilgi,  Analytics, 1, &[], Some("shape_id"), VA_GEO, Entity,
        "Shape aşırı fazla noktaya sahip (>5000) — tüketici render performansını etkiler"),
    r!("SHP_027", Bilgi,  Analytics, 1, &[], Some("shape_id"), VA_GEO, Entity,
        "Shape birden fazla durak desenine atanmış — olası yanlış shape ataması"),
    r!("SHP_028", Yuksek, Quality, 2, &[], Some("shape_id"), VS, Entity,
        "Ardışık iki shape noktası aynı shape_dist_traveled ama farklı koordinat (mesafe artmadan konum değişmiş)"),
    r!("SHP_029", Bilgi,  Quality, 2, &[], Some("shape_id"), VS, Entity,
        "Aynı shape_dist_traveled, farklı ama çok yakın koordinatlı ardışık shape noktaları (eşik altı)"),

    // ── FRQ: Frequencies ───────────────────────────────────────────────────────
    r!("FRQ_001", Kritik, Spec, 1, &[], Some("trip_id"), VS_K, Row,
        "trip_id bulunamadı"),
    r!("FRQ_002", Kritik, Spec, 2, &[], Some("trip_id"), VS_K, Row,
        "start_time geçersiz"),
    r!("FRQ_003", Kritik, Spec, 2, &[], Some("trip_id"), VS_K, Row,
        "end_time geçersiz"),
    r!("FRQ_004", Kritik, Spec, 2, &[], Some("trip_id"), VS_K, Row,
        "headway_secs eksik veya geçersiz"),
    r!("FRQ_005", Kritik, Quality, 2, &[], Some("trip_id"), VS, Row,
        "end_time start_time'dan önce"),
    r!("FRQ_006", Orta,   Analytics, 2, &[], Some("trip_id"), VA, Row,
        "headway_secs çok uzun"),
    r!("FRQ_007", Orta,   Spec, 1, &[], Some("trip_id"), VS, Row,
        "exact_times geçersiz"),
    r!("FRQ_008", Kritik, Spec, 3, &[], Some("trip_id"), VS_K, Row,
        "headway_secs sıfır (geçersiz frekans)"),
    r!("FRQ_009", Orta,   Quality, 3, &[], Some("trip_id"), VS, Row,
        "Frekans aralığı çok kısa"),
    r!("FRQ_010", Bilgi,  Analytics, 1, &[], Some("trip_id"), VA, Row,
        "Çok sık frekans (sıkışma riski)"),
    r!("FRQ_011", Yuksek, Interop, 2, &[], Some("trip_id"), VI, Row,
        "Aynı trip için frequencies dönemleri zaman aralığı çakışıyor"),

    // ── TRF: Transfers ─────────────────────────────────────────────────────────
    r!("TRF_001", Kritik, Spec, 1, &[], None, VS_K, Row,
        "from_stop_id eksik"),
    r!("TRF_002", Kritik, Spec, 1, &[], None, VS_K, Row,
        "to_stop_id eksik"),
    r!("TRF_003", Kritik, Spec, 1,
        &["TRF_004","TRF_010","TRF_011","TRF_013","TRF_014","TRF_015","TRF_016"],
        Some("from_stop_id|to_stop_id"), VS_K, Row,
        "from_stop_id veya to_stop_id bulunamadı"),
    r!("TRF_004", Yuksek, Spec, 2, &[], Some("from_stop_id|to_stop_id"), VS, Row,
        "transfer_type geçersiz"),
    r!("TRF_005", Kritik, Spec, 2, &[], Some("from_stop_id|to_stop_id"), VS_K, Row,
        "min_transfer_time eksik"),
    r!("TRF_006", Kritik, Spec, 1,
        &["TRF_013","TRF_014","TRF_015","TRF_017","TRF_018","OPR_007"],
        Some("from_trip_id"), VS_K, Row,
        "from_trip_id bulunamadı"),
    r!("TRF_007", Kritik, Spec, 1,
        &["TRF_013","TRF_014","TRF_015","TRF_017","TRF_018","OPR_007"],
        Some("to_trip_id"), VS_K, Row,
        "to_trip_id bulunamadı"),
    r!("TRF_008", Kritik, Spec, 1, &[], Some("from_route_id"), VS_K, Row,
        "from_route_id bulunamadı"),
    r!("TRF_009", Kritik, Spec, 1, &[], Some("to_route_id"), VS_K, Row,
        "to_route_id bulunamadı"),
    r!("TRF_010", Orta,   Analytics, 2, &[], Some("from_stop_id|to_stop_id"), VA, Row,
        "Aktarma süresi çok uzun"),
    r!("TRF_011", Bilgi,  Quality, 2, &[], Some("from_stop_id|to_stop_id"), VS, Row,
        "Aktarma tanımlandı ama mesafe uzak"),
    r!("TRF_012", Orta,   Quality, 1, &[], None, VS, Row,
        "Yinelenen aktarma kaydı"),
    r!("TRF_013", Kritik, Spec, 2, &[], None, VS_K, Row,
        "Aktarma türü bağlamla uyumsuz"),
    r!("TRF_014", Yuksek, Spec, 2, &[], None, VS, Row,
        "in-seat aktarma için sefer yok"),
    r!("TRF_015", Yuksek, Spec, 2, &[], None, VS, Row,
        "in-seat aktarma geçersiz"),
    r!("TRF_016", Orta,   Spec, 2, &[], None, VS, Row,
        "Aktarma koşulu çelişkili"),
    // XFL_020 aynı (trip, route) uyumsuzluğunu kontrol eder; çift raporlamayı
    // önlemek için TRF_017 kök kuraldır ve XFL_020'yi semptom olarak bastırır.
    r!("TRF_017", Yuksek, Spec, 2, &["XFL_020"], None, VS, Row,
        "Sefer aktarması yanlış hat"),
    r!("TRF_018", Orta,   Quality, 2, &[], None, VS, Row,
        "Sefer aktarması aynı seferi gösteriyor"),
    r!("TRF_019", Orta, Spec, 2, &[], None, VS, Row,
        "In-seat aktarmada farklı route_type"),
    r!("TRF_020", Orta, Quality, 2, &[], Some("from_stop_id|to_stop_id"), VS, Row,
        "Aktarma için gereken yürüme hızı çok yüksek"),

    // ── GGL: Google Transit Uyumluluk Kuralları ───────────────────────────────
    r!("GGL_001", Dusuk, Interop, 1, &[], None, VI, Row,
        "transfer_type=4/5 Google Transit tarafından desteklenmiyor"),
    r!("GGL_002", Dusuk, Interop, 1, &[], None, VI, Row,
        "ic_price (Google-özel) geçersiz değer"),

    // ── FAR: Fare Attributes ───────────────────────────────────────────────────
    r!("FAR_001", Kritik, Spec, 1,
        &["FRL_001","FAR_009"],
        Some("fare_id"), VS_K, Entity,
        "fare_id yineleniyor"),
    r!("FAR_002", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Entity,
        "price eksik veya geçersiz"),
    r!("FAR_003", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Entity,
        "currency_type eksik"),
    r!("FAR_004", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Entity,
        "payment_method geçersiz"),
    r!("FAR_005", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Entity,
        "transfers geçersiz"),
    r!("FAR_006", Orta,   Spec, 1, &[], Some("fare_id"), VS, Entity,
        "transfer_duration geçersiz"),
    r!("FAR_008", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Entity,
        "agency_id bulunamadı"),
    r!("FAR_009", Dusuk,  Quality, 3, &[], Some("fare_id"), VS, Entity,
        "Ücrete ait hat kuralı yok"),
    r!("FAR_010", Orta,   Quality, 2, &[], None, VS, Feed,
        "Çakışan ücret kuralları"),
    r!("FAR_011", Kritik, Spec, 1, &[], Some("payment_method"), VS_K, Entity,
        "payment_method eksik"),
    r!("FAR_012", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Entity,
        "fare_id eksik"),

    // ── FRL: Fare Rules ────────────────────────────────────────────────────────
    r!("FRL_001", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Row,
        "fare_id bulunamadı"),
    r!("FRL_002", Kritik, Spec, 1, &[], Some("route_id"), VS_K, Row,
        "route_id bulunamadı"),
    r!("FRL_003", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Row,
        "origin_id geçersiz"),
    r!("FRL_004", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Row,
        "destination_id geçersiz"),
    r!("FRL_005", Kritik, Spec, 1, &[], Some("fare_id"), VS_K, Row,
        "contains_id geçersiz"),
    r!("FRL_006", Bilgi,  Quality, 1, &[], None, VS, Feed,
        "Ücret kuralı tanımlı değil"),
    r!("FRL_007", Orta,   Quality, 3, &[], Some("fare_id"), VS, Row,
        "Ücret kuralı mantıksal tutarsızlık"),
    r!("FRL_008", Bilgi,  Quality, 3, &[], None, VS, Feed,
        "Tüm hatlar için ücret tanımlı değil"),

    // ── RCT: Rider Categories (Fares v2) ──────────────────────────────────────
    r!("RCT_001", Kritik, Spec, 1, &["FPD_005"],
        Some("rider_category_id"), VS_K, Row,
        "rider_category_id yineleniyor"),
    r!("RCT_002", Kritik, Spec, 1, &[], Some("rider_category_id"), VS_K, Row,
        "rider_category_name eksik"),
    r!("RCT_003", Kritik, Spec, 1, &[], Some("rider_category_id"), VS_K, Row,
        "is_default_fare_category geçersiz"),
    r!("RCT_004", Orta,   Spec, 1, &[], Some("rider_category_id"), VS, Row,
        "min_age veya max_age geçersiz"),
    r!("RCT_005", Orta,   Quality, 1, &[], Some("rider_category_id"), VS, Row,
        "max_age min_age'den küçük"),
    r!("RCT_006", Orta,   Spec, 2, &[], Some("fare_product_id"), VS, Entity,
        "fare_product başına birden fazla varsayılan yolcu kategorisi"),

    // ── FMD: Fare Media (Fares v2) ────────────────────────────────────────────
    r!("FMD_001", Kritik, Spec, 1, &["FPD_004"],
        Some("fare_media_id"), VS_K, Row,
        "fare_media_id yineleniyor"),
    r!("FMD_002", Kritik, Spec, 1, &[], Some("fare_media_id"), VS_K, Row,
        "fare_media_type eksik veya geçersiz"),
    r!("FMD_003", Dusuk, Quality, 1, &[], Some("fare_media_id"), VS, Row,
        "TransitCard/MobileApp için fare_media_name tavsiye edilir"),

    // ── FPD: Fare Products (Fares v2) ─────────────────────────────────────────
    r!("FPD_001", Kritik, Spec, 1, &["FLG_001","FTR_004"],
        Some("fare_product_id"), VS_K, Row,
        "fare_product_id yineleniyor"),
    r!("FPD_002", Kritik, Spec, 1, &[], Some("fare_product_id"), VS_K, Row,
        "amount eksik veya negatif"),
    r!("FPD_003", Kritik, Spec, 1, &[], Some("fare_product_id"), VS_K, Row,
        "currency geçersiz ISO 4217 kodu"),
    r!("FPD_004", Kritik, Spec, 1, &[], Some("fare_product_id"), VS_K, Row,
        "fare_media_id bulunamadı"),
    r!("FPD_005", Kritik, Spec, 1, &[], Some("fare_product_id"), VS_K, Row,
        "rider_category_id bulunamadı"),
    r!("FPD_006", Orta, Spec, 1, &[], Some("fare_product_id"), VS, Entity,
        "Bir fare_product için birden fazla varsayılan rider category"),

    // ── FLG: Fare Leg Rules (Fares v2) ────────────────────────────────────────
    r!("FLG_001", Kritik, Spec, 1, &[], Some("fare_product_id"), VS_K, Row,
        "fare_product_id bulunamadı"),
    r!("FLG_002", Kritik, Spec, 1, &[], Some("network_id"), VS_K, Row,
        "network_id bulunamadı"),
    r!("FLG_003", Kritik, Spec, 1, &[], Some("from_area_id"), VS_K, Row,
        "from_area_id bulunamadı"),
    r!("FLG_004", Kritik, Spec, 1, &[], Some("to_area_id"), VS_K, Row,
        "to_area_id bulunamadı"),
    r!("FLG_005", Kritik, Spec, 1, &[], Some("from_timeframe_group_id"), VS_K, Row,
        "from_timeframe_group_id bulunamadı"),
    r!("FLG_006", Kritik, Spec, 1, &[], Some("to_timeframe_group_id"), VS_K, Row,
        "to_timeframe_group_id bulunamadı"),
    r!("FLG_007", Orta,   Spec, 1, &[], Some("leg_group_id"), VS, Row,
        "rule_priority geçersiz"),

    // ── FTR: Fare Transfer Rules (Fares v2) ───────────────────────────────────
    r!("FTR_001", Kritik, Spec, 1, &[], None, VS_K, Row,
        "fare_transfer_type eksik veya geçersiz"),
    r!("FTR_002", Kritik, Spec, 1, &[], Some("from_leg_group_id"), VS_K, Row,
        "from_leg_group_id bulunamadı"),
    r!("FTR_003", Kritik, Spec, 1, &[], Some("to_leg_group_id"), VS_K, Row,
        "to_leg_group_id bulunamadı"),
    r!("FTR_004", Kritik, Spec, 1, &[], Some("fare_product_id"), VS_K, Row,
        "fare_product_id bulunamadı"),
    r!("FTR_005", Kritik, Spec, 1, &[], None, VS_K, Row,
        "duration_limit_type geçersiz"),
    r!("FTR_006", Orta,   Spec, 1, &[], None, VS, Row,
        "duration_limit geçersiz"),
    r!("FTR_007", Orta,   Spec, 1, &[], None, VS, Row,
        "duration_limit_type duration_limit olmadan tanımlı"),
    r!("FTR_008", Orta,   Spec, 1, &[], None, VS, Row,
        "transfer_count geçersiz"),
    r!("FTR_009", Orta,   Spec, 1, &[], None, VS, Row,
        "leg grupları aynıyken transfer_count zorunlu"),
    r!("FTR_010", Orta,   Spec, 1, &[], None, VS, Row,
        "leg grupları farklıyken transfer_count tanımlanamaz"),
    r!("FTR_011", Orta,   Spec, 1, &[], None, VS, Row,
        "duration_limit tanımlı ama duration_limit_type eksik"),

    // ── ARS: Areas (Fares v2) ─────────────────────────────────────────────────
    r!("ARS_001", Kritik, Spec, 1, &["SAR_001","FLG_003","FLG_004"],
        Some("area_id"), VS_K, Row,
        "area_id yineleniyor"),

    // ── SAR: Stop Areas (Fares v2) ────────────────────────────────────────────
    r!("SAR_001", Kritik, Spec, 1, &[], Some("area_id"), VS_K, Row,
        "area_id bulunamadı"),
    r!("SAR_002", Kritik, Spec, 1, &[], Some("stop_id"), VS_K, Row,
        "stop_id bulunamadı"),

    // ── NET: Networks (Fares v2) ──────────────────────────────────────────────
    r!("NET_001", Kritik, Spec, 1, &["FLG_002"],
        Some("network_id"), VS_K, Row,
        "network_id yineleniyor"),

    // ── TFR: Timeframes (Fares v2) ────────────────────────────────────────────
    r!("TFR_001", Kritik, Spec, 1, &[], Some("timeframe_group_id"), VS_K, Row,
        "timeframe_group_id eksik"),
    r!("TFR_002", Kritik, Spec, 1, &[], Some("timeframe_group_id"), VS_K, Row,
        "service_id bulunamadı"),
    r!("TFR_003", Yuksek, Spec, 1, &[], Some("timeframe_group_id"), VS, Row,
        "start_time veya end_time format hatası"),
    r!("TFR_004", Orta,   Quality, 1, &[], Some("timeframe_group_id"), VS, Row,
        "end_time start_time'dan küçük"),
    r!("TFR_005", Orta,   Interop, 1, &[], Some("timeframe_group_id"), VI, Row,
        "Aynı grup ve service_id içinde örtüşen zaman aralıkları"),

    // ── PTH: Pathways ──────────────────────────────────────────────────────────
    r!("PTH_001", Kritik, Spec, 1, &[], Some("pathway_id"), VS_K, Entity,
        "pathway_id yineleniyor"),
    r!("PTH_002", Kritik, Spec, 1,
        &["PTH_011","PTH_012","PTH_013","PTH_015"],
        Some("pathway_id"), VS_K, Entity,
        "from_stop_id bulunamadı"),
    r!("PTH_003", Kritik, Spec, 1,
        &["PTH_011","PTH_012","PTH_013","PTH_015"],
        Some("pathway_id"), VS_K, Entity,
        "to_stop_id bulunamadı"),
    r!("PTH_004", Kritik, Spec, 1,
        // PTH_008/009 feed-seviyesi özet oldu (#15) → per-pathway suppression'a uymaz, çıkarıldı.
        &["PTH_016","PTH_017","PTH_018"],
        Some("pathway_id"), VS_K, Entity,
        "pathway_mode eksik veya geçersiz"),
    r!("PTH_005", Kritik, Spec, 1,
        &["PTH_012","PTH_016"],
        Some("pathway_id"), VS_K, Entity,
        "is_bidirectional eksik"),
    r!("PTH_006", Orta,   Spec, 1, &[], Some("pathway_id"), VS, Entity,
        "length geçersiz"),
    r!("PTH_007", Orta,   Spec, 1, &[], Some("pathway_id"), VS, Entity,
        "traversal_time geçersiz"),
    r!("PTH_008", Dusuk,  Quality, 2, &[], None, VS, Feed,
        "stair_count eksik"),
    r!("PTH_009", Dusuk,  Quality, 2, &[], None, VS, Feed,
        "max_slope eksik"),
    r!("PTH_010", Dusuk,  Spec, 1, &[], Some("pathway_id"), VS, Entity,
        "min_width geçersiz"),
    r!("PTH_011", Yuksek, Quality, 3, &[], Some("pathway_id"), VS, Entity,
        "Geçit döngü oluşturuyor"),
    r!("PTH_012", Yuksek, Interop, 3,
        &["PTH_013"],
        Some("stop_id"), VI_K_ACC, Entity,
        "İstasyona erişilebilir yol yok"),
    r!("PTH_013", Bilgi,  Analytics, 3, &[], Some("stop_id"), VA_ACC, Entity,
        "Erişilebilir yol analizi"),
    r!("PTH_014", Kritik, Quality, 1, &[], Some("pathway_id"), VS, Entity,
        "Geçit istasyon sınırını aşıyor"),
    r!("PTH_015", Orta,   Analytics, 2, &[], Some("pathway_id"), VA, Entity,
        "Geçit hedefi erişilemeyen durakta"),
    r!("PTH_016", Yuksek, Spec, 3, &[], Some("pathway_id"), VS, Entity,
        "Çıkış kapısı çift yönlü tanımlanmış"),
    r!("PTH_017", Orta,   Spec, 2, &[], Some("pathway_id"), VS, Entity,
        "max_slope geçersiz bağlam"),
    r!("PTH_018", Dusuk,  Quality, 1, &[], Some("pathway_id"), VS, Entity,
        "signposted_as çok uzun"),
    r!("PTH_019", Orta,   Quality, 2, &[], Some("stop_id"), VS, Entity,
        "Generic node tek pathway'e bağlı (dead-end)"),
    r!("PTH_020", Kritik, Spec, 1, &[], Some("pathway_id"), VS_K, Entity,
        "pathway_id eksik"),
    r!("PTH_021", Kritik, Spec, 1, &[], Some("from_stop_id"), VS_K, Entity,
        "from_stop_id eksik"),
    r!("PTH_022", Kritik, Spec, 1, &[], Some("to_stop_id"), VS_K, Entity,
        "to_stop_id eksik"),
    r!("PTH_023", Kritik, Spec, 1, &[], Some("pathway_mode"), VS_K, Entity,
        "pathway_mode eksik"),
    r!("PTH_024", Kritik, Spec, 1, &[], Some("is_bidirectional"), VS_K, Entity,
        "is_bidirectional eksik"),
    r!("PTH_025", Dusuk, Quality, 1, &[], None, VS, Feed,
        "Önerilen pathway length bilgisi eksik"),

    // ── LVL: Levels ────────────────────────────────────────────────────────────
    r!("LVL_001", Kritik, Spec, 1,
        &["STP_015","XFL_009"],
        Some("level_id"), VS_K, Entity,
        "level_id yineleniyor"),
    r!("LVL_002", Kritik, Spec, 1, &[], Some("level_id"), VS_K, Entity,
        "level_index geçersiz"),
    r!("LVL_003", Dusuk,  Quality, 1, &[], Some("level_id"), VS, Entity,
        "level_name eksik"),
    r!("LVL_004", Dusuk,  Quality, 1, &[], Some("level_id"), VS, Entity,
        "Kullanılmayan level"),
    r!("LVL_005", Orta,   Quality, 1, &[], Some("level_id"), VS, Entity,
        "level_name çok uzun"),
    r!("LVL_006", Orta,   Quality, 2, &[], Some("stop_id"), VS, Entity,
        "Asansör bağlantısındaki durakta level_id eksik"),
    r!("LVL_007", Kritik, Spec, 1, &[], Some("level_index"), VS_K, Row,
        "level_index eksik"),
    r!("LVL_008", Kritik, Spec, 1, &[], Some("level_id"), VS_K, Entity,
        "level_id eksik"),

    // ── FIN: Feed Info ─────────────────────────────────────────────────────────
    r!("FIN_001", Kritik, Spec, 1, &[], None, VS_K, Feed,
        "feed_publisher_name eksik"),
    r!("FIN_002", Kritik, Spec, 1, &[], None, VS_K, Feed,
        "feed_publisher_url eksik veya geçersiz"),
    r!("FIN_003", Kritik, Spec, 1,
        &["TRN_007"],
        None, VS_K, Feed,
        "feed_lang eksik"),
    r!("FIN_004", Orta,   Spec, 1, &[], None, VS, Feed,
        "default_lang geçersiz"),
    r!("FIN_005", Orta,   Spec, 1, &[], None, VS, Feed,
        "feed_start_date geçersiz"),
    r!("FIN_006", Yuksek, Spec, 2, &[], None, VS, Feed,
        "feed_end_date geçersiz format (geçmiş tarih için FIN_010 kullanın)"),
    r!("FIN_007", Dusuk,  Quality, 1, &[], None, VS, Feed,
        "feed_version eksik"),
    r!("FIN_008", Dusuk,  Spec, 1, &[], None, VS, Feed,
        "feed_contact_email geçersiz"),
    r!("FIN_009", Dusuk,  Spec, 1, &[], None, VS, Feed,
        "feed_contact_url geçersiz"),
    r!("FIN_010", Yuksek, Analytics, 2, &[], None, VA, Feed,
        "Feed geçerlilik süresi dolmuş"),
    r!("FIN_012", Dusuk,  Quality, 1, &[], None, VS, Feed,
        "feed_start_date feed_end_date'den sonra"),
    r!("FIN_013", Bilgi,  Quality, 1, &[], None, VS, Feed,
        "fare_attributes.agency_id önerilen ama eksik"),
    r!("FIN_014", Dusuk,  Quality, 1, &[], None, VS, Feed,
        "Feed geçerlilik tarihleri (feed_start_date/feed_end_date) eksik"),
    r!("FIN_015", Orta,   Quality, 1, &[], None, VS, File,
        "Birden fazla feed_info kaydı"),
    r!("FIN_016", Dusuk,  Quality, 1, &[], None, VS, Feed,
        "feed_start_date gelecekte (feed henüz aktif değil)"),
    r!("FIN_017", Bilgi,  Quality, 1, &[], None, VS, Feed,
        "Feed çok uzak gelecekte sona eriyor"),
    r!("FIN_018", Dusuk,  Quality, 1, &[], None, VS, Feed,
        "feed_contact_email ve feed_contact_url ikisi de eksik"),
    r!("FIN_019", Dusuk,  Quality, 1, &[], None, VS, Feed,
        "Feed'in geçerlilik süresi 7 gün içinde dolacak"),
    r!("FIN_020", Orta,   Quality, 1, &[], None, VS, Feed,
        "Feed geçerlilik penceresi 7 günden kısa — operasyonel kullanım için çok kısa"),

    // ── TRN: Translations ──────────────────────────────────────────────────────
    r!("TRN_001", Kritik, Spec, 1, &[], None, VS_K, Row,
        "table_name geçersiz değer"),
    r!("TRN_002", Kritik, Spec, 1, &[], None, VS_K, Row,
        "field_name bu tablo için geçersiz"),
    r!("TRN_003", Orta,   Spec, 1, &[], None, VS, Row,
        "language geçersiz"),
    r!("TRN_004", Yuksek, Spec, 1, &[], Some("record_id"), VS, Row,
        "record_id bulunamadı"),
    r!("TRN_005", Kritik, Spec, 1, &[], Some("record_id"), VS_K, Row,
        "Çeviri yineleniyor"),
    r!("TRN_006", Kritik, Spec, 1, &[], Some("record_id"), VS_K, Row,
        "Çeviri kaydı çelişkili"),
    r!("TRN_007", Dusuk,  Quality, 1, &[], None, VS, Row,
        "Çeviri feed_lang ile aynı dilde"),
    r!("TRN_008", Bilgi,  Quality, 1, &[], None, VS, Row,
        "translation değeri boş"),
    r!("TRN_009", Yuksek, Spec, 1, &[], Some("record_id"), VS, Row,
        "record_id ve field_value aynı anda kullanılamaz"),
    r!("TRN_010", Yuksek, Spec, 1, &[], Some("record_id"), VS, Row,
        "record_sub_id geçersiz"),
    r!("TRN_011", Yuksek, Spec, 1, &[], None, VS, Row,
        "field_name çevrilebilir değil"),
    r!("TRN_013", Yuksek, Spec, 1, &[], None, VS, Row,
        "feed_info çevirisinde kimlik alanı kullanılamaz"),
    r!("TRN_014", Yuksek, Spec, 1, &[], Some("record_id"), VS, Row,
        "record_sub_id yalnızca stop_times için geçerli"),

    // ── ATR: Attributions ──────────────────────────────────────────────────────
    r!("ATR_001", Yuksek, Quality, 1, &[], Some("attribution_id"), VS, Entity,
        "attribution_id eksik"),
    r!("ATR_002", Kritik, Spec, 1, &[], Some("attribution_id"), VS_K, Entity,
        "organization_name eksik"),
    r!("ATR_003", Yuksek, Spec, 1, &[], Some("attribution_id"), VS, Entity,
        "Attribution rolü tanımlanmamış"),
    r!("ATR_004", Kritik, Spec, 1, &[], Some("attribution_id"), VS_K, Entity,
        "is_producer geçersiz"),
    r!("ATR_005", Kritik, Spec, 1, &[], Some("attribution_id"), VS_K, Entity,
        "is_operator geçersiz"),
    r!("ATR_006", Kritik, Spec, 1, &[], Some("attribution_id"), VS_K, Entity,
        "is_authority geçersiz"),
    r!("ATR_007", Kritik, Spec, 1, &[], Some("attribution_id"), VS_K, Entity,
        "attribution_url geçersiz"),
    r!("ATR_008", Dusuk,  Spec, 1, &[], Some("attribution_id"), VS, Entity,
        "attribution_email geçersiz"),
    r!("ATR_009", Yuksek, Quality, 1, &[], Some("attribution_id"), VS, Entity,
        "attribution_phone geçersiz"),
    r!("ATR_010", Dusuk,  Spec, 1, &[], Some("attribution_id"), VS, Entity,
        "agency_id bulunamadı"),

    // ── XFL: Çapraz Dosya / Semantik ───────────────────────────────────────────
    r!("XFL_001", Kritik, Spec, 1,
        &["CAL_009","DQ_005","OPR_011","OPR_016"],
        Some("service_id"), VS_K, Entity,
        "calendar ve calendar_dates'te service_id yok"),
    r!("XFL_002", Yuksek, Spec, 1, &[], Some("trip_id"), VS, Entity,
        "Seferin stop_times kaydı yok"),
    r!("XFL_003", Yuksek, Spec, 1, &[], Some("trip_id"), VS, Entity,
        "shape_id tanımsız"),
    r!("XFL_004", Kritik, Spec, 1, &[], Some("route_id"), VS_K, Entity,
        "fare_rules'ta tanımsız route_id"),
    r!("XFL_005", Kritik, Spec, 1,
        &["STP_012","DQ_005c"],
        Some("stop_id"), VS_K, Entity,
        "stop_times'ta tanımsız stop_id"),
    r!("XFL_006", Orta,   Analytics, 2, &[], Some("service_id"), VA, Entity,
        "service_id yalnızca iptal istisnası içeriyor (aktif gün yok)"),
    r!("XFL_007", Kritik, Spec, 1, &[], Some("agency_id"), VS_K, Entity,
        "agency_id bulunamadı"),
    r!("XFL_009", Kritik, Spec, 1, &[], Some("level_id"), VS_K, Entity,
        "level_id geçersiz"),
    r!("XFL_010", Kritik, Spec, 1, &[], Some("trip_id"), VS_K, Entity,
        "frequencies'te tanımsız trip_id"),
    // XFL_011 (Interop, iki feed tarihi de zorunlu) ile CAL_019 (Quality) aynı
    // ham calendar–feed_info karşılaştırmasını yapar. XFL_011 tetiklendiğinde
    // aynı service_id scope'undaki CAL_019 semptom olarak bastırılır (çift rapor önlenir).
    r!("XFL_011", Orta,   Interop, 2, &["CAL_019"], None, VI, Feed,
        "Takvim tarihleri feed_info aralığı dışında"),
    r!("XFL_012", Yuksek, Quality, 2, &[], Some("route_id"), VS, Entity,
        "Çalıştırılabilir seferi olmayan hat (stop_times veya aktif servis bağlamı eksik)"),
    r!("XFL_013", Yuksek, Interop, 2,
        &["SHP_017","STM_017"],
        None, VI_K, Feed,
        "shape_id birden fazla yönde kullanılıyor"),
    r!("XFL_014", Orta,   Quality, 1, &[], None, VS, Feed,
        "Geçersiz çeviri referansı (kaynak kayıt bulunamadı)"),
    r!("XFL_015", Kritik, Spec, 1, &[], None, VS_K, Feed,
        "Attribution'da geçersiz referans"),
    r!("XFL_016", Yuksek, Spec, 1, &[], None, VS, Feed,
        "Çeviri feed_info'ya referans veriyor ama feed_info.txt eksik"),
    r!("XFL_017", Dusuk,  Quality, 1, &[], None, VS, Feed,
        "route_cemv_support ile agency_cemv_support çelişiyor"),
    r!("XFL_019", Orta,   Spec, 2, &[], None, VS, Feed,
        "Ağ tanımı iki ayrı dosyada (routes.network_id + route_networks.txt)"),
    r!("XFL_020", Yuksek, Spec, 2, &[], None, VS, Row,
        "Transfers'de geçersiz (from_trip_id/to_trip_id, route_id) çifti"),
    r!("XFL_021", Yuksek, Spec, 2, &[], None, VS, Row,
        "Transfers'de geçersiz (from_trip_id/to_trip_id, stop_id) çifti"),
    r!("XFL_022", Kritik, Spec, 1, &[], Some("location_group_id"), VS_K, Row,
        "location_group_id bulunamadı (location_group_stops)"),
    r!("XFL_023", Kritik, Spec, 1, &[], Some("stop_id"), VS_K, Row,
        "stop_id bulunamadı (location_group_stops)"),
    r!("XFL_024", Kritik, Spec, 1, &[], Some("location_group_id"), VS_K, Row,
        "location_group_id bulunamadı (stop_times)"),
    r!("XFL_025", Kritik, Spec, 1, &[], Some("location_id"), VS_K, Row,
        "location_id bulunamadı (locations.geojson)"),
    r!("XFL_026", Orta,  Interop, 2, &[], Some("route_id"), VI, Entity,
        "route cemv_support=1 ama uygulanabilir contactless fare product yok"),
    r!("XFL_027", Orta,  Interop, 2, &[], Some("route_id"), VI, Entity,
        "route cemv_support=2 ama uygulanabilir contactless fare product var"),
    r!("XFL_028", Bilgi, Quality, 1, &[], None, VS, Feed,
        "agency cemv_support=1 ama Fares v2'de contactless media yok"),
    r!("XFL_029", Bilgi, Quality, 1, &[], None, VS, Feed,
        "route cemv_support=1 ama Fares v2'de contactless media yok"),
    r!("XFL_030", Bilgi, Quality, 1, &[], None, VS, Feed,
        "contactless fare media var ama hiç cemv_support=1 yok"),

    // ── OPR: Operasyonel Tutarlılık (tümü ANALYTICS) ───────────────────────────
    r!("OPR_001", Orta,   Analytics, 3, &[], Some("route_id"), VA, Entity,
        "Hat sefer sıklığı düşük"),
    r!("OPR_003", Dusuk,  Analytics, 2, &[], Some("route_id"), VA, Entity,
        "Sefer sıkışması (minimum aralık çok küçük)"),
    r!("OPR_004", Bilgi,  Analytics, 1, &[], Some("route_id"), VA, Entity,
        "Hafta sonu sefer yok"),
    r!("OPR_005", Bilgi,  Analytics, 2, &[], Some("route_id"), VA, Entity,
        "Sıradışı sefer sıklığı"),
    r!("OPR_006", Yuksek, Analytics, 3, &[], Some("trip_id"), VA, Entity,
        "Seferde çok az durak (işlevsel değil)"),
    r!("OPR_007", Bilgi,  Analytics, 3, &[], Some("trip_id"), VA, Entity,
        "Sefer içinde tekrarlayan durak deseni"),
    r!("OPR_008", Yuksek, Analytics, 3, &[], Some("trip_id"), VA, Entity,
        "Birden fazla segmentte aşırı hız"),
    r!("OPR_009", Bilgi,  Analytics, 2, &[], Some("route_id"), VA, Entity,
        "Gece seferi başlangıç saati çok geç"),
    r!("OPR_010", Orta,   Analytics, 2, &[], Some("route_id"), VA, Entity,
        "Hatta erişilebilirlik veya bisiklet politikası çelişiyor"),
    r!("OPR_011", Yuksek, Analytics, 2, &[], Some("service_id"), VA, Entity,
        "Serviste aktif gün yok"),
    r!("OPR_012", Orta,   Analytics, 2, &[], Some("service_id"), VA, Entity,
        "Servis boşluğu"),
    r!("OPR_013", Bilgi,  Analytics, 2, &[], Some("route_id"), VA, Entity,
        "Hat tek yönde işliyor (karşı yön tanımlı değil)"),
    r!("OPR_014", Orta,   Analytics, 2, &[], None, VA, Feed,
        "Ortalama aktarma süresi uzun"),
    r!("OPR_015", Bilgi,  Analytics, 1, &[], Some("route_id"), VA, Entity,
        "Hat yalnızca tek güzergahla işliyor"),
    r!("OPR_016", Bilgi,  Analytics, 1, &[], None, VA, Feed,
        "Feed genelinde aktif servis yok"),
    r!("OPR_017", Orta,   Analytics, 2, &[], Some("trip_id"), VA, Entity,
        "Sefer çok kısa mesafe"),
    r!("OPR_018", Orta,   Analytics, 2, &[], Some("service_id"), VA, Entity,
        "Servis dönemi çok kısa"),
    r!("OPR_019", Bilgi,  Analytics, 2, &[], Some("route_id"),   VA, Entity,
        "Rota takvim çakışması (aynı günde birden fazla servis)"),
    r!("OPR_020", Yuksek, Analytics, 2, &[], Some("route_id"),   VA, Entity,
        "Rota exception günü çakışması"),
    r!("OPR_021", Yuksek, Analytics, 3, &[], Some("route_id"),   VA, Entity,
        "Takvim override çakışması: override ve base eş zamanlı aktif"),
    r!("OPR_022", Yuksek, Analytics, 3, &[], Some("route_id"),   VA, Entity,
        "Takvim override uygulanmamış: override gününde base servis çalışıyor"),
    r!("OPR_023", Orta,   Analytics, 3, &[], Some("route_id"),   VA, Entity,
        "Takvim override boşluğu: pencere içinde hiçbir servis aktif değil"),
    r!("OPR_024", Bilgi,  Analytics, 1, &[], Some("route_id"),   VA, Entity,
        "Hat çok fazla sefer içeriyor — olası veri birleştirme sorunu"),
    r!("OPR_025", Yuksek, Analytics, 2, &[], None, VA, Feed,
        "Feed genelinde ortalama sefer süresi 60 saniyeden kısa — veri kalitesi sorunu"),

    // ── GEO: Coğrafi / Uzamsal (canonical kurallar — GEO_008/010/011 hariç) ───
    r!("GEO_002", Yuksek, Analytics, 2, &[], Some("stop_id"), VA_GEO, Entity,
        "Durak feed medianından çok uzakta"),
    r!("GEO_006", Yuksek, Analytics, 3, &[], Some("shape_id"), VA_GEO, Entity,
        "Güzergah şeklinde büyük atlama"),
    r!("GEO_007", Yuksek, Analytics, 3, &[], Some("shape_id"), VA_GEO, Entity,
        "Güzergah şeklinde kritik atlama (3× eşik)"),
    r!("GEO_009", Yuksek, Quality,   3, &[], Some("stop_id"), VI_K_GEO, Entity,
        "Durak shape güzergahından çok uzakta"),
    r!("GEO_012", Orta,   Analytics, 2, &[], Some("stop_id"), VA_GEO, Entity,
        "Duraksallar kümelenmesi (çok yakın duraklar)"),
    r!("GEO_013", Bilgi,  Analytics, 2, &[], None, VA_GEO, Feed,
        "Feed coğrafi kapsam özeti"),
    r!("GEO_014", Bilgi,  Analytics, 1, &[], None, VA_GEO, Feed,
        "Feed coğrafi kapsamı çok geniş"),
    r!("GEO_015", Orta,   Quality,   1, &[], Some("stop_id"), VS, Entity,
        "Durak koordinatları Japonya sınırları dışında (feed_lang: ja)"),
    r!("GEO_016", Yuksek, Quality,   1, &[], Some("stop_id"), VA_GEO, Entity,
        "Durak Null Island yakınında (|lat|<1 VE |lon|<1) — olası koordinat hatası"),
    r!("GEO_017", Yuksek, Quality,   1, &[], Some("shape_id"), VA_GEO, Entity,
        "Shape noktası Null Island yakınında — GPS verisi hatası"),
    r!("GEO_018", Yuksek, Analytics, 2, &[], None, VA_GEO, Feed,
        "Tüm feed durağları 200m yarıçap içinde — test/yer tutucu veri"),
    r!("GEO_019", Orta,   Quality,   1, &[], Some("stop_id"), VS, Entity,
        "Durak koordinatları tam sayı (ondalık basamak yok) — düşük hassasiyetli veya yer tutucu"),
    r!("GEO_020", Yuksek, Quality,   1, &[], Some("shape_id"), VA_GEO, Entity,
        "Shape'in tüm noktaları aynı koordinatta — dejenere geometri"),
    r!("GEO_021", Yuksek, Analytics, 2, &[], None, VA_GEO, Feed,
        "Durakların %30'undan fazlası koordinatlarını başka bir durakla paylaşıyor — sistematik hata"),
    r!("GEO_022", Yuksek, Quality,   1, &[], Some("stop_id"), VA_GEO, Entity,
        "Durak enlemi kutba aşırı yakın (|lat|>89) — olası koordinat hatası"),

    // ── DQ: Veri Kalitesi / Kullanıcı Deneyimi ─────────────────────────────────
    // DQ_001/DQ_002 (feed_publisher_name/url eksik) kaldırıldı: ARC_020 (dosya yok)
    // + FIN_001/002 (değer boş) + ARC_025 (sütun yok) zaten kapsıyor.
    r!("DQ_003",  Bilgi,  Quality,  1, &[], Some("route_id"), VS, Entity,
        "Hat açıklaması eksik"),
    r!("DQ_004",  Bilgi,  Quality,  1, &[], Some("route_id"), VS, Entity,
        "Hat URL'si eksik"),
    r!("DQ_005",  Yuksek, Interop,  2, &[], None, VI_K, Feed,
        "Geçerli servis dönemi yok"),
    r!("DQ_005b", Yuksek, Interop,  2, &["DQ_009"], None, VI_K, Feed,
        "Hiçbir seferin durak zamanı yok"),
    r!("DQ_005c", Yuksek, Interop,  2, &[], None, VI_K, Feed,
        "Koordinatsız durak oranı çok yüksek"),
    r!("DQ_006",  Yuksek, Quality,  2, &[], None, VS, Feed,
        "Şekil olmayan sefer oranı çok yüksek"),
    r!("DQ_009",  Bilgi,  Quality,  1, &[], None, VS, Feed,
        "Seferlerde durak zamanı yok"),
    r!("DQ_010",  Bilgi,  Quality,  1, &[], None, VS, Feed,
        "Acente hiçbir hatta kullanılmıyor"),
    r!("DQ_011",  Dusuk,  Quality,  1, &[], None, VS, Feed,
        "Yalnızca bir durak var"),
    r!("DQ_012",  Dusuk,  Quality,  1, &[], None, VS, Feed,
        "Çok fazla acente, agency_id kullanılmıyor"),
    r!("DQ_013",  Orta,   Quality,  1, &[], None, VS, Feed,
        "Çok az sefer"),
    r!("DQ_016",  Orta,   Quality,  1, &[], None, VS, Row,
        "Değerde fazladan boşluk karakteri"),
    r!("DQ_017",  Bilgi,  Quality,  1, &[], None, VS, Feed,
        "Şüpheli koordinat değeri"),
    r!("DQ_018",  Orta,   Quality,  1, &[], Some("stop_id"), VS, Entity,
        "Önerilen alanda tamamen büyük harf (all-caps)"),
    r!("DQ_019",  Orta,   Quality,  1, &[], Some("file"), VS, Field,
        "Önerilen alanda tamamen küçük harf (all-lowercase)"),
    r!("DQ_020",  Dusuk,  Quality,  1, &[], Some("file"), VS, Field,
        "Önerilen alan eksik veya boş"),
    r!("DQ_021",  Yuksek, Spec,     1, &[], Some("file"), VS_K, Entity,
        "Birincil anahtar yineleniyor — genel ikincil sinyal (STP_001/RTS_001 gibi entity-level kurallarla örtüşebilir)"),
    r!("DQ_022",  Yuksek, Quality,  2, &[], None, VS, Feed,
        "Durakların %80'inden fazlası aynı stop_name değerini paylaşıyor — yer tutucu/test verisi"),

    // ── VAT: Varlık Analitik Tespiti (tümü ANALYTICS) ──────────────────────────
    r!("VAT_001", Orta,   Analytics, 3, &[], Some("route_id"), VA, Entity,
        "Hat güzergah benzerliği (muhtemel kopya hat)"),
    r!("VAT_002", Bilgi,  Analytics, 3, &[], Some("stop_id"), VA, Entity,
        "Aktarma merkezi tanımsız — çok sayıda hat geçiyor ama aktarma yok"),
    r!("VAT_003", Dusuk,  Analytics, 3, &[], Some("trip_id"), VA, Entity,
        "Sefer süresi istatistiksel aykırı değer"),
    r!("VAT_004", Bilgi,  Analytics, 3, &[], Some("route_id"), VA, Entity,
        "Hat hizmet asimetrisi — hat yalnızca hafta içi çalışıyor"),
    r!("VAT_005", Orta,   Analytics, 3, &[], None, VA, Feed,
        "İzole durak kümesi — ağ grafiğinde ana bileşenden kopuk duraklar"),
    r!("VAT_006", Bilgi,  Analytics, 2, &[], Some("route_id"), VA, Entity,
        "Hizmet yoğunluğu dengesizliği — tek hat feed sefer sayısının büyük bölümünü oluşturuyor"),
    r!("VAT_007", Bilgi,  Analytics, 3, &[], Some("stop_id"), VA, Entity,
        "Terminus aktarma eksikliği — terminal durağa başka hat geliyor ama aktarma tanımlı değil"),
    r!("VAT_008", Bilgi,  Analytics, 2, &[], Some("shape_id"), VA_GEO, Entity,
        "Aynı shape feed hatlarının %30'undan fazlasında kullanılıyor — olası yanlış shape ataması"),

    // ── JPN — GTFS-JP (Japonya profili) kuralları; yalnız GTFS-JP feed'lerde ────
    r!("JPN_001", Orta,   Quality, 2, &[], Some("stop_id"), VS, Entity,
        "GTFS-JP: durak adının kana (ja-Hrkt) okuması eksik"),
    r!("JPN_002", Yuksek, Interop, 1, &[], Some("trip_id"), VI, Entity,
        "GTFS-JP: jp_office_id office_jp.txt'te tanımlı değil"),
    r!("JPN_003", Yuksek, Interop, 1, &[], Some("agency_id"), VI, Entity,
        "GTFS-JP: agency_jp.agency_id agency.txt'te tanımlı değil"),
    r!("JPN_004", Yuksek, Interop, 2, &[], None, VI, Feed,
        "GTFS-JP: translations.txt eksik (profil zorunlu kılar)"),
    r!("JPN_005", Yuksek, Interop, 1, &[], Some("office_id"), VI, Entity,
        "GTFS-JP: office_jp.office_name boş (zorunlu alan)"),
    r!("JPN_006", Orta,   Quality, 2, &[], None, VS, Feed,
        "GTFS-JP: fare_attributes/fare_rules eksik (profil zorunlu kılar)"),
    r!("JPN_007", Orta,   Quality, 2, &[], None, VS, Feed,
        "GTFS-JP: feed_info.txt eksik (profil zorunlu kılar)"),
    r!("JPN_008", Orta,   Quality, 2, &[], Some("route_id"), VS, Entity,
        "GTFS-JP: hat adının (route_long_name) kana (ja-Hrkt) okuması eksik"),
    r!("JPN_009", Orta,   Quality, 2, &[], Some("trip_id"), VS, Entity,
        "GTFS-JP: trip_headsign kana (ja-Hrkt) okuması eksik"),
    r!("JPN_010", Orta,   Quality, 2, &[], Some("agency_id"), VS, Entity,
        "GTFS-JP: işletici adının (agency_name) kana (ja-Hrkt) okuması eksik"),
    r!("JPN_011", Yuksek, Interop, 1, &[], None, VI, Feed,
        "GTFS-JP: tek işletici olsa bile agency_id zorunlu"),
];

/// `RULES` üzerinden id → metadata için tek seferlik kurulan O(1) arama tablosu.
/// `RULES` derleme-zamanı sabiti olduğundan ilk çağrıda bir kez kurulur; sonraki
/// çağrılar lineer tarama yerine hash-lookup yapar. `OnceLock` thread-safe →
/// `pkg-threads` (rayon) build'inde de güvenli. Çıktı/dönüş değeri lineer taramayla
/// BİREBİR aynıdır (ID'ler `no_duplicate_ids` testiyle benzersiz garantili).
fn rule_index() -> &'static std::collections::HashMap<&'static str, &'static RuleMeta> {
    static IDX: std::sync::OnceLock<std::collections::HashMap<&'static str, &'static RuleMeta>> =
        std::sync::OnceLock::new();
    IDX.get_or_init(|| RULES.iter().map(|r| (r.id, r)).collect())
}

/// Kural ID'sine göre metadata döndürür.
pub fn get_rule(id: &str) -> Option<&'static RuleMeta> {
    rule_index().get(id).copied()
}

/// Kural ID → otorite kaynağı (docs/audits/spec-authority-inventory-reconciled.csv'den üretildi).
/// Sınıf otorite bütünlüğü SSOT: `Spec` sınıfı YALNIZ `GtfsSpec` ile meşrudur. r!() çağrılarına
/// dokunmadan tutulur; kapsam/tekillik `authority_covers_all_rules` testiyle denetlenir.
static AUTHORITY: &[(&str, AuthoritySource)] = &[
    ("AGN_001", GtfsSpec),
    ("AGN_002", GtfsSpec),
    ("AGN_003", GtfsSpec),
    ("AGN_004", GtfsSpec),
    ("AGN_005", ProjectQuality),
    ("AGN_006", GtfsSpec),
    ("AGN_007", ProjectQuality),
    ("AGN_008", GtfsSpec),
    ("AGN_009", GtfsSpec),
    ("AGN_010", GtfsSpec),
    ("AGN_011", GtfsSpec),
    ("AGN_012", ProjectQuality),
    ("AGN_013", MobilitydataParity),
    ("AGN_014", GtfsSpec),
    ("AGN_015", ProjectQuality),
    ("AGN_016", ProjectQuality),
    ("AGN_017", MobilitydataParity),
    ("ARC_001", GtfsSpec),
    ("ARC_002", GtfsBestPractice),
    ("ARC_003", ProjectQuality),
    ("ARC_004", GtfsSpec),
    ("ARC_006", ProjectQuality),
    ("ARC_007", ProjectQuality),
    ("ARC_008", GtfsSpec),
    ("ARC_009", ProjectQuality),
    ("ARC_010", MobilitydataParity),
    ("ARC_011", ProjectAnalytics),
    ("ARC_012", GtfsSpec),
    ("ARC_013", GtfsSpec),
    ("ARC_014", ProjectQuality),
    ("ARC_015", ProjectQuality),
    ("ARC_017", ProjectQuality),
    ("ARC_018", ProjectQuality),
    ("ARC_019", ProjectQuality),
    ("ARC_020", ProjectQuality),
    ("ARC_021", ProjectQuality),
    ("ARC_022", ProjectQuality),
    ("ARC_023", ProjectQuality),
    ("ARC_024", GtfsSpec),
    ("ARC_025", GtfsSpec),
    ("ARC_026", MobilitydataParity),
    ("ARC_027", MobilitydataParity),
    ("ARC_028", ProjectQuality),
    ("ARC_029", ProjectQuality),
    ("ARS_001", GtfsSpec),
    ("ATR_001", ProjectQuality),
    ("ATR_002", GtfsSpec),
    ("ATR_003", GtfsSpec),
    ("ATR_004", GtfsSpec),
    ("ATR_005", GtfsSpec),
    ("ATR_006", GtfsSpec),
    ("ATR_007", GtfsSpec),
    ("ATR_008", GtfsSpec),
    ("ATR_009", ProjectQuality),
    ("ATR_010", GtfsSpec),
    ("BKR_001", GtfsSpec),
    ("BKR_002", GtfsSpec),
    ("BKR_003", GtfsSpec),
    ("BKR_004", GtfsSpec),
    ("BKR_005", GtfsSpec),
    ("BKR_006", GtfsSpec),
    ("BKR_007", GtfsSpec),
    ("BKR_008", GtfsSpec),
    ("BKR_009", GtfsSpec),
    ("BKR_010", GtfsSpec),
    ("BKR_011", MobilitydataParity),
    ("CAL_001", GtfsSpec),
    ("CAL_002", GtfsSpec),
    ("CAL_003", GtfsSpec),
    ("CAL_004", GtfsSpec),
    ("CAL_005", MobilitydataParity),
    ("CAL_006", ProjectQuality),
    ("CAL_007", ProjectAnalytics),
    ("CAL_008", ProjectAnalytics),
    ("CAL_009", MobilitydataParity),
    ("CAL_010", ProjectAnalytics),
    ("CAL_011", ProjectQuality),
    ("CAL_012", ProjectAnalytics),
    ("CAL_013", ProjectAnalytics),
    ("CAL_014", ProjectQuality),
    ("CAL_015", ProjectQuality),
    ("CAL_016", ProjectQuality),
    ("CAL_017", ProjectQuality),
    ("CAL_018", ProjectQuality),
    ("CAL_019", ProjectQuality),
    ("CAL_020", ProjectQuality),
    ("CAL_021", ProjectAnalytics),
    ("CAL_022", GtfsSpec),
    ("CAL_023", ProjectQuality),
    ("CAL_024", ProjectQuality),
    ("CLD_001", GtfsSpec),
    ("CLD_002", GtfsSpec),
    ("CLD_003", GtfsSpec),
    ("CLD_004", MobilitydataParity),
    ("CLD_005", ProjectQuality),
    ("CLD_006", ProjectQuality),
    ("CLD_007", ProjectAnalytics),
    ("DQ_003", ProjectQuality),
    ("DQ_004", ProjectQuality),
    ("DQ_005", MobilitydataParity),
    ("DQ_005b", MobilitydataParity),
    ("DQ_005c", MobilitydataParity),
    ("DQ_006", ProjectQuality),
    ("DQ_009", ProjectQuality),
    ("DQ_010", ProjectQuality),
    ("DQ_011", ProjectQuality),
    ("DQ_012", ProjectQuality),
    ("DQ_013", ProjectQuality),
    ("DQ_016", ProjectQuality),
    ("DQ_017", ProjectQuality),
    ("DQ_018", ProjectQuality),
    ("DQ_019", ProjectQuality),
    ("DQ_020", ProjectQuality),
    ("DQ_021", GtfsSpec),
    ("DQ_022", ProjectQuality),
    ("FAR_001", GtfsSpec),
    ("FAR_002", GtfsSpec),
    ("FAR_003", GtfsSpec),
    ("FAR_004", GtfsSpec),
    ("FAR_005", GtfsSpec),
    ("FAR_006", GtfsSpec),
    ("FAR_008", GtfsSpec),
    ("FAR_009", ProjectQuality),
    ("FAR_010", ProjectQuality),
    ("FAR_011", GtfsSpec),
    ("FAR_012", GtfsSpec),
    ("FIN_001", GtfsSpec),
    ("FIN_002", GtfsSpec),
    ("FIN_003", GtfsSpec),
    ("FIN_004", GtfsSpec),
    ("FIN_005", GtfsSpec),
    ("FIN_006", GtfsSpec),
    ("FIN_007", ProjectQuality),
    ("FIN_008", GtfsSpec),
    ("FIN_009", GtfsSpec),
    ("FIN_010", ProjectAnalytics),
    ("FIN_012", ProjectQuality),
    ("FIN_013", ProjectQuality),
    ("FIN_014", ProjectQuality),
    ("FIN_015", ProjectQuality),
    ("FIN_016", ProjectQuality),
    ("FIN_017", ProjectQuality),
    ("FIN_018", ProjectQuality),
    ("FIN_019", ProjectQuality),
    ("FIN_020", ProjectQuality),
    ("FLG_001", GtfsSpec),
    ("FLG_002", GtfsSpec),
    ("FLG_003", GtfsSpec),
    ("FLG_004", GtfsSpec),
    ("FLG_005", GtfsSpec),
    ("FLG_006", GtfsSpec),
    ("FLG_007", GtfsSpec),
    ("FMD_001", GtfsSpec),
    ("FMD_002", GtfsSpec),
    ("FMD_003", ProjectQuality),
    ("FPD_001", GtfsSpec),
    ("FPD_002", GtfsSpec),
    ("FPD_003", GtfsSpec),
    ("FPD_004", GtfsSpec),
    ("FPD_005", GtfsSpec),
    ("FPD_006", GtfsSpec),
    ("FRL_001", GtfsSpec),
    ("FRL_002", GtfsSpec),
    ("FRL_003", GtfsSpec),
    ("FRL_004", GtfsSpec),
    ("FRL_005", GtfsSpec),
    ("FRL_006", ProjectQuality),
    ("FRL_007", ProjectQuality),
    ("FRL_008", ProjectQuality),
    ("FRQ_001", GtfsSpec),
    ("FRQ_002", GtfsSpec),
    ("FRQ_003", GtfsSpec),
    ("FRQ_004", GtfsSpec),
    ("FRQ_005", ProjectQuality),
    ("FRQ_006", ProjectAnalytics),
    ("FRQ_007", GtfsSpec),
    ("FRQ_008", GtfsSpec),
    ("FRQ_009", ProjectQuality),
    ("FRQ_010", ProjectAnalytics),
    ("FRQ_011", MobilitydataParity),
    ("FTR_001", GtfsSpec),
    ("FTR_002", GtfsSpec),
    ("FTR_003", GtfsSpec),
    ("FTR_004", GtfsSpec),
    ("FTR_005", GtfsSpec),
    ("FTR_006", GtfsSpec),
    ("FTR_007", GtfsSpec),
    ("FTR_008", GtfsSpec),
    ("FTR_009", GtfsSpec),
    ("FTR_010", GtfsSpec),
    ("FTR_011", GtfsSpec),
    ("GEO_002", ProjectAnalytics),
    ("GEO_006", ProjectAnalytics),
    ("GEO_007", ProjectAnalytics),
    ("GEO_009", ProjectQuality),
    ("GEO_012", ProjectAnalytics),
    ("GEO_013", ProjectAnalytics),
    ("GEO_014", ProjectAnalytics),
    ("GEO_015", ProjectQuality),
    ("GEO_016", ProjectQuality),
    ("GEO_017", ProjectQuality),
    ("GEO_018", ProjectAnalytics),
    ("GEO_019", ProjectQuality),
    ("GEO_020", ProjectQuality),
    ("GEO_021", ProjectAnalytics),
    ("GEO_022", ProjectQuality),
    ("GGL_001", MobilitydataParity),
    ("GGL_002", MobilitydataParity),
    ("JPN_001", ProjectQuality),
    ("JPN_002", RegionalProfile),
    ("JPN_003", RegionalProfile),
    ("JPN_004", RegionalProfile),
    ("JPN_005", RegionalProfile),
    ("JPN_006", ProjectQuality),
    ("JPN_007", ProjectQuality),
    ("JPN_008", ProjectQuality),
    ("JPN_009", ProjectQuality),
    ("JPN_010", ProjectQuality),
    ("JPN_011", RegionalProfile),
    ("LOC_001", GtfsSpec),
    ("LOC_002", GtfsSpec),
    ("LOC_003", GtfsSpec),
    ("LOC_004", GtfsSpec),
    ("LOC_005", ProjectQuality),
    ("LOC_006", ProjectQuality),
    ("LOC_007", GtfsSpec),
    ("LVL_001", GtfsSpec),
    ("LVL_002", GtfsSpec),
    ("LVL_003", ProjectQuality),
    ("LVL_004", ProjectQuality),
    ("LVL_005", ProjectQuality),
    ("LVL_006", ProjectQuality),
    ("LVL_007", GtfsSpec),
    ("LVL_008", GtfsSpec),
    ("NET_001", GtfsSpec),
    ("OPR_001", ProjectAnalytics),
    ("OPR_003", ProjectAnalytics),
    ("OPR_004", ProjectAnalytics),
    ("OPR_005", ProjectAnalytics),
    ("OPR_006", ProjectAnalytics),
    ("OPR_007", ProjectAnalytics),
    ("OPR_008", ProjectAnalytics),
    ("OPR_009", ProjectAnalytics),
    ("OPR_010", ProjectAnalytics),
    ("OPR_011", ProjectAnalytics),
    ("OPR_012", ProjectAnalytics),
    ("OPR_013", ProjectAnalytics),
    ("OPR_014", ProjectAnalytics),
    ("OPR_015", ProjectAnalytics),
    ("OPR_016", ProjectAnalytics),
    ("OPR_017", ProjectAnalytics),
    ("OPR_018", ProjectAnalytics),
    ("OPR_019", ProjectAnalytics),
    ("OPR_020", ProjectAnalytics),
    ("OPR_021", ProjectAnalytics),
    ("OPR_022", ProjectAnalytics),
    ("OPR_023", ProjectAnalytics),
    ("OPR_024", ProjectAnalytics),
    ("OPR_025", ProjectAnalytics),
    ("PDW_006", ProjectAnalytics),
    ("PTH_001", GtfsSpec),
    ("PTH_002", GtfsSpec),
    ("PTH_003", GtfsSpec),
    ("PTH_004", GtfsSpec),
    ("PTH_005", GtfsSpec),
    ("PTH_006", GtfsSpec),
    ("PTH_007", GtfsSpec),
    ("PTH_008", ProjectQuality),
    ("PTH_009", ProjectQuality),
    ("PTH_010", GtfsSpec),
    ("PTH_011", ProjectQuality),
    ("PTH_012", MobilitydataParity),
    ("PTH_013", ProjectAnalytics),
    ("PTH_014", ProjectQuality),
    ("PTH_015", ProjectAnalytics),
    ("PTH_016", GtfsSpec),
    ("PTH_017", GtfsSpec),
    ("PTH_018", ProjectQuality),
    ("PTH_019", ProjectQuality),
    ("PTH_020", GtfsSpec),
    ("PTH_021", GtfsSpec),
    ("PTH_022", GtfsSpec),
    ("PTH_023", GtfsSpec),
    ("PTH_024", GtfsSpec),
    ("PTH_025", ProjectQuality),
    ("RCT_001", GtfsSpec),
    ("RCT_002", GtfsSpec),
    ("RCT_003", GtfsSpec),
    ("RCT_004", GtfsSpec),
    ("RCT_005", ProjectQuality),
    ("RCT_006", GtfsSpec),
    ("RTS_001", GtfsSpec),
    ("RTS_002", GtfsSpec),
    ("RTS_003", GtfsSpec),
    ("RTS_004", GtfsSpec),
    ("RTS_005", GtfsSpec),
    ("RTS_006", GtfsSpec),
    ("RTS_007", ProjectQuality),
    ("RTS_008", ProjectQuality),
    ("RTS_009", GtfsBestPractice),
    ("RTS_010", ProjectQuality),
    ("RTS_011", ProjectQuality),
    ("RTS_012", ProjectQuality),
    ("RTS_013", GtfsSpec),
    ("RTS_016", ProjectQuality),
    ("RTS_017", ProjectQuality),
    ("RTS_018", GtfsSpec),
    ("RTS_019", ProjectQuality),
    ("RTS_020", ProjectQuality),
    ("RTS_021", MobilitydataParity),
    ("RTS_022", ProjectQuality),
    ("RTS_023", ProjectQuality),
    ("RTS_024", ProjectQuality),
    ("RTS_025", ProjectQuality),
    ("RTS_026", ProjectQuality),
    ("RTS_027", ProjectQuality),
    ("SAR_001", GtfsSpec),
    ("SAR_002", GtfsSpec),
    ("SHP_001", GtfsSpec),
    ("SHP_002", GtfsSpec),
    ("SHP_003", GtfsSpec),
    ("SHP_004", GtfsSpec),
    ("SHP_005", GtfsSpec),
    ("SHP_006", ProjectQuality),
    ("SHP_008", GtfsSpec),
    ("SHP_009", ProjectAnalytics),
    ("SHP_010", ProjectQuality),
    ("SHP_011", ProjectAnalytics),
    ("SHP_012", ProjectAnalytics),
    ("SHP_014", ProjectAnalytics),
    ("SHP_015", ProjectQuality),
    ("SHP_016", MobilitydataParity),
    ("SHP_017", ProjectAnalytics),
    ("SHP_018", ProjectQuality),
    ("SHP_019", ProjectQuality),
    ("SHP_020", ProjectAnalytics),
    ("SHP_021", ProjectQuality),
    ("SHP_022", MobilitydataParity),
    ("SHP_023", ProjectQuality),
    ("SHP_024", ProjectQuality),
    ("SHP_025", ProjectQuality),
    ("SHP_026", ProjectAnalytics),
    ("SHP_027", ProjectAnalytics),
    ("SHP_028", ProjectQuality),
    ("SHP_029", ProjectQuality),
    ("STM_001", GtfsSpec),
    ("STM_002", GtfsSpec),
    ("STM_003", GtfsSpec),
    ("STM_004", GtfsSpec),
    ("STM_005", GtfsSpec),
    ("STM_006", GtfsSpec),
    ("STM_007", MobilitydataParity),
    ("STM_008", MobilitydataParity),
    ("STM_009", GtfsSpec),
    ("STM_010", GtfsSpec),
    ("STM_012", MobilitydataParity),
    ("STM_013", ProjectQuality),
    ("STM_014", ProjectAnalytics),
    ("STM_015", GtfsSpec),
    ("STM_016", GtfsSpec),
    ("STM_017", MobilitydataParity),
    ("STM_018", GtfsSpec),
    ("STM_019", GtfsSpec),
    ("STM_020", ProjectQuality),
    ("STM_021", ProjectQuality),
    ("STM_022", GtfsSpec),
    ("STM_023", ProjectQuality),
    ("STM_024", ProjectQuality),
    ("STM_025", ProjectAnalytics),
    ("STM_026", ProjectQuality),
    ("STM_027", MobilitydataParity),
    ("STM_028", ProjectAnalytics),
    ("STM_029", ProjectAnalytics),
    ("STM_030", GtfsSpec),
    ("STM_032", ProjectQuality),
    ("STM_033", MobilitydataParity),
    ("STM_034", MobilitydataParity),
    ("STM_035", ProjectAnalytics),
    ("STM_036", ProjectQuality),
    ("STM_037", GtfsSpec),
    ("STM_038", MobilitydataParity),
    ("STM_039", GtfsSpec),
    ("STM_040", GtfsSpec),
    ("STM_041", GtfsSpec),
    ("STM_042", MobilitydataParity),
    ("STM_043", ProjectAnalytics),
    ("STM_044", ProjectAnalytics),
    ("STM_045", ProjectQuality),
    ("STM_046", GtfsSpec),
    ("STM_047", GtfsSpec),
    ("STM_048", ProjectQuality),
    ("STM_049", ProjectQuality),
    ("STM_050", ProjectQuality),
    ("STM_051", GtfsSpec),
    ("STM_052", GtfsSpec),
    ("STM_053", ProjectQuality),
    ("STP_001", GtfsSpec),
    ("STP_002", GtfsSpec),
    ("STP_003", GtfsSpec),
    ("STP_004", GtfsSpec),
    ("STP_005", ProjectQuality),
    ("STP_006", GtfsSpec),
    ("STP_007", GtfsSpec),
    ("STP_008", GtfsSpec),
    ("STP_009", GtfsSpec),
    ("STP_010", GtfsSpec),
    ("STP_011", GtfsSpec),
    ("STP_012", GtfsSpec),
    ("STP_013", GtfsSpec),
    ("STP_014", GtfsSpec),
    ("STP_015", GtfsSpec),
    ("STP_016", ProjectQuality),
    ("STP_017", ProjectQuality),
    ("STP_018", GtfsSpec),
    ("STP_019", ProjectQuality),
    ("STP_020", ProjectAnalytics),
    ("STP_021", ProjectQuality),
    ("STP_022", ProjectQuality),
    ("STP_023", ProjectQuality),
    ("STP_024", ProjectQuality),
    ("STP_025", ProjectQuality),
    ("STP_026", GtfsSpec),
    ("STP_027", ProjectQuality),
    ("STP_028", ProjectQuality),
    ("STP_029", ProjectQuality),
    ("STP_030", ProjectQuality),
    ("STP_031", ProjectQuality),
    ("STP_032", ProjectQuality),
    ("STP_033", ProjectQuality),
    ("STP_034", ProjectQuality),
    ("STP_035", ProjectQuality),
    ("STP_036", GtfsSpec),
    ("STP_037", ProjectQuality),
    ("STP_038", ProjectQuality),
    ("STP_039", ProjectQuality),
    ("STP_040", ProjectQuality),
    ("STP_041", ProjectQuality),
    ("TFR_001", GtfsSpec),
    ("TFR_002", GtfsSpec),
    ("TFR_003", GtfsSpec),
    ("TFR_004", ProjectQuality),
    ("TFR_005", MobilitydataParity),
    ("TRF_001", GtfsSpec),
    ("TRF_002", GtfsSpec),
    ("TRF_003", GtfsSpec),
    ("TRF_004", GtfsSpec),
    ("TRF_005", GtfsSpec),
    ("TRF_006", GtfsSpec),
    ("TRF_007", GtfsSpec),
    ("TRF_008", GtfsSpec),
    ("TRF_009", GtfsSpec),
    ("TRF_010", ProjectAnalytics),
    ("TRF_011", ProjectQuality),
    ("TRF_012", ProjectQuality),
    ("TRF_013", MobilitydataParity),
    ("TRF_014", GtfsSpec),
    ("TRF_015", MobilitydataParity),
    ("TRF_016", MobilitydataParity),
    ("TRF_017", MobilitydataParity),
    ("TRF_018", ProjectQuality),
    ("TRF_019", MobilitydataParity),
    ("TRF_020", ProjectQuality),
    ("TRN_001", GtfsSpec),
    ("TRN_002", GtfsSpec),
    ("TRN_003", GtfsSpec),
    ("TRN_004", GtfsSpec),
    ("TRN_005", GtfsSpec),
    ("TRN_006", GtfsSpec),
    ("TRN_007", ProjectQuality),
    ("TRN_008", ProjectQuality),
    ("TRN_009", GtfsSpec),
    ("TRN_010", GtfsSpec),
    ("TRN_011", GtfsSpec),
    ("TRN_013", GtfsSpec),
    ("TRN_014", GtfsSpec),
    ("TRP_001", GtfsSpec),
    ("TRP_002", GtfsSpec),
    ("TRP_003", GtfsSpec),
    ("TRP_004", GtfsSpec),
    ("TRP_005", GtfsSpec),
    ("TRP_006", GtfsSpec),
    ("TRP_007", GtfsSpec),
    ("TRP_009", ProjectQuality),
    ("TRP_011", ProjectQuality),
    ("TRP_012", ProjectQuality),
    ("TRP_013", ProjectQuality),
    ("TRP_014", ProjectQuality),
    ("TRP_015", ProjectQuality),
    ("TRP_017", MobilitydataParity),
    ("TRP_019", ProjectQuality),
    ("TRP_020", ProjectAnalytics),
    ("TRP_021", ProjectQuality),
    ("TRP_022", MobilitydataParity),
    ("TRP_023", ProjectQuality),
    ("TRP_024", MobilitydataParity),
    ("TRP_025", ProjectQuality),
    ("TRP_026", ProjectAnalytics),
    ("TRP_028", ProjectQuality),
    ("TRP_029", ProjectQuality),
    ("TRP_031", GtfsSpec),
    ("TRP_032", GtfsSpec),
    ("VAT_001", ProjectAnalytics),
    ("VAT_002", ProjectAnalytics),
    ("VAT_003", ProjectAnalytics),
    ("VAT_004", ProjectAnalytics),
    ("VAT_005", ProjectAnalytics),
    ("VAT_006", ProjectAnalytics),
    ("VAT_007", ProjectAnalytics),
    ("VAT_008", ProjectAnalytics),
    ("XFL_001", GtfsSpec),
    ("XFL_002", MobilitydataParity),
    ("XFL_003", GtfsSpec),
    ("XFL_004", GtfsSpec),
    ("XFL_005", GtfsSpec),
    ("XFL_006", ProjectAnalytics),
    ("XFL_007", GtfsSpec),
    ("XFL_009", GtfsSpec),
    ("XFL_010", GtfsSpec),
    ("XFL_011", MobilitydataParity),
    ("XFL_012", ProjectQuality),
    ("XFL_013", MobilitydataParity),
    ("XFL_014", ProjectQuality),
    ("XFL_015", GtfsSpec),
    ("XFL_016", GtfsSpec),
    ("XFL_017", ProjectQuality),
    ("XFL_019", GtfsSpec),
    ("XFL_020", GtfsSpec),
    ("XFL_021", GtfsSpec),
    ("XFL_022", GtfsSpec),
    ("XFL_023", GtfsSpec),
    ("XFL_024", GtfsSpec),
    ("XFL_025", GtfsSpec),
    ("XFL_026", MobilitydataParity),
    ("XFL_027", MobilitydataParity),
    ("XFL_028", ProjectQuality),
    ("XFL_029", ProjectQuality),
    ("XFL_030", ProjectQuality),
];

/// `AUTHORITY` üzerinden id → AuthoritySource için O(1) arama (`rule_index` deseni).
fn authority_index() -> &'static std::collections::HashMap<&'static str, AuthoritySource> {
    static IDX: std::sync::OnceLock<std::collections::HashMap<&'static str, AuthoritySource>> =
        std::sync::OnceLock::new();
    IDX.get_or_init(|| AUTHORITY.iter().map(|&(k, v)| (k, v)).collect())
}

/// Kural ID'sinin otorite kaynağı. Bilinmiyorsa `Unknown`.
pub fn authority_source(id: &str) -> AuthoritySource {
    authority_index().get(id).copied().unwrap_or(AuthoritySource::Unknown)
}

impl RuleMeta {
    /// Bu kuralın otorite kaynağı (sınıfın meşruiyet dayanağı).
    pub fn authority_source(&self) -> AuthoritySource {
        authority_source(self.id)
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    /// Faz 2 warn-modu: `Sınıf=Spec` ama `authority≠GtfsSpec` olan MEVCUT kurallar
    /// (docs/audits/spec-authority-inventory-reconciled.csv — başlangıç 45; Faz 3 parti 1
    /// SHP_006/RTS_009/TRF_018 → 42; parti 2 STM_007/STM_008/CAL_005 → 39; parti 3
    /// FRQ_005/TFR_004/RCT_005/BKR_011/STM_034/STM_038 → 33; parti 4 (Analytics)
    /// FRQ_011/PDW_006/TFR_005/TRP_022/XFL_006 → 28; parti 5
    /// ARC_002/ARC_009/ARC_015/ARC_019/ARC_023 → 23; parti 6
    /// CLD_005/PTH_011/PTH_014/SHP_028/STM_023/TRP_019 → 17; parti 7
    /// JPN_002/JPN_003/JPN_004/JPN_005/JPN_011 → 12; parti 8
    /// ATR_001/ATR_009/STP_027 → 9). Faz 3 bu
    /// kuralların sınıfını düzelttikçe `rule_class==Spec` filtresi onları dışlar ve
    /// listeden çıkarılır; Faz 4'te liste BOŞALIR (hard-fail). Yeni ekleme YAPILMAZ.
    const SPEC_AUTHORITY_ALLOWLIST: &[&str] = &[
        "ARC_029", "STM_033",
        "TRF_013", "TRF_015", "TRF_016", "TRF_017", "TRF_019",
        "TRP_017", "XFL_002",
    ];

    #[test]
    fn no_duplicate_ids() {
        let mut ids: Vec<&str> = RULES.iter().map(|r| r.id).collect();
        ids.sort_unstable();
        let before = ids.len();
        ids.dedup();
        assert_eq!(before, ids.len(), "Tekrar eden kural ID'si var");
    }

    /// AUTHORITY tablosu her RULES kuralını birebir kapsamalı (drift yok):
    /// eksik yok, yetim yok, mükerrer yok. Otorite SSOT bütünlüğünün temeli.
    #[test]
    fn authority_covers_all_rules() {
        use std::collections::HashSet;
        let rule_ids: HashSet<&str> = RULES.iter().map(|r| r.id).collect();
        let auth_ids: HashSet<&str> = AUTHORITY.iter().map(|&(k, _)| k).collect();
        assert_eq!(AUTHORITY.len(), auth_ids.len(), "AUTHORITY'de mükerrer id");
        let missing: Vec<&str> = rule_ids.difference(&auth_ids).copied().collect();
        let orphan: Vec<&str> = auth_ids.difference(&rule_ids).copied().collect();
        assert!(missing.is_empty(), "AUTHORITY'de eksik kural(lar): {missing:?}");
        assert!(orphan.is_empty(), "AUTHORITY'de yetim giriş(ler): {orphan:?}");
    }

    /// Otorite bütünlüğü çekirdek değişmezi: hiçbir kural `Spec` sınıfındayken
    /// authority_source ≠ GtfsSpec olamaz. Faz 3 sınıfları düzeltene dek mevcut
    /// ihlaller `SPEC_AUTHORITY_ALLOWLIST`'te tutulur (warn-modu); liste Faz 4'te boşalır.
    #[test]
    fn spec_class_requires_gtfs_spec_authority() {
        let violations: Vec<&str> = RULES
            .iter()
            .filter(|r| r.rule_class == RuleClass::Spec)
            .filter(|r| authority_source(r.id) != AuthoritySource::GtfsSpec)
            .map(|r| r.id)
            .filter(|id| !SPEC_AUTHORITY_ALLOWLIST.contains(id))
            .collect();
        assert!(
            violations.is_empty(),
            "Spec sınıfı ama authority≠GtfsSpec ve allowlist'te değil: {violations:?}"
        );
    }

    #[test]
    fn geo_view_ids_absent() {
        assert!(get_rule("GEO_008").is_none(), "GEO_008 registry'de olmamalı");
        assert!(get_rule("GEO_010").is_none(), "GEO_010 registry'de olmamalı");
        assert!(get_rule("GEO_011").is_none(), "GEO_011 registry'de olmamalı");
    }

    #[test]
    fn removed_ids_absent() {
        assert!(get_rule("STM_011").is_none());
        assert!(get_rule("TRP_010").is_none());
        assert!(get_rule("GEO_001").is_none());
        assert!(get_rule("GEO_005").is_none());
        assert!(get_rule("DQ_007").is_none());
        assert!(get_rule("DQ_008").is_none());
        assert!(get_rule("DQ_015").is_none());
    }

    #[test]
    fn blocks_only_canonical_ids() {
        let view_ids = ["GEO_008", "GEO_010", "GEO_011"];
        let removed_ids = ["STM_011","TRP_010","GEO_001","GEO_005","DQ_007","DQ_008","DQ_015"];
        for rule in RULES {
            for &b in rule.blocks {
                assert!(!view_ids.contains(&b),
                    "{}: blocks[] içinde rapor görünüm ID'si var: {}", rule.id, b);
                assert!(!removed_ids.contains(&b),
                    "{}: blocks[] içinde kaldırılmış ID var: {}", rule.id, b);
                assert!(get_rule(b).is_some(),
                    "{}: blocks[] içinde bilinmeyen canonical ID: {}", rule.id, b);
            }
        }
    }

    #[test]
    fn get_rule_lookup() {
        assert!(get_rule("STP_003").is_some());
        assert!(get_rule("STM_014").is_some());
        assert!(get_rule("NONEXISTENT").is_none());
    }

    #[test]
    fn base_effort_valid() {
        for rule in RULES {
            assert!(
                matches!(rule.base_effort, 1 | 2 | 3),
                "{}: geçersiz base_effort = {}", rule.id, rule.base_effort
            );
        }
    }

    #[test]
    fn report_views_nonempty() {
        for rule in RULES {
            assert!(
                !rule.report_views.is_empty(),
                "{}: report_views boş olamaz", rule.id
            );
        }
    }

    #[test]
    fn interop_always_has_r8() {
        use gtfs_core::{RuleClass::Interop, ReportId::R8};
        for rule in RULES {
            if rule.rule_class == Interop {
                assert!(
                    rule.report_views.contains(&R8),
                    "{}: INTEROP kuralı R8'i içermeli", rule.id
                );
            }
        }
    }

    #[test]
    fn blocker_rules_have_r1() {
        use gtfs_core::{RuleClass::Spec, ReportId::R1, Severity::Kritik};
        // Otorite bütünlüğü (Faz 3+): R1 yayın-engeli yalnız `Spec` + `Kritik` kurallarda.
        // Interop artık R1 ÜRETMEZ (mandate: R1 = GtfsSpec + Spec + Kritik). Eski
        // "Kritik/Yüksek Interop → R1" konvansiyonu kaldırıldı; tam kod-düzeyi otorite
        // bağlaması (is_pub_relevant/build_r1) Faz 4'te yapılacak.
        for rule in RULES {
            if rule.severity == Kritik && rule.rule_class == Spec {
                assert!(
                    rule.report_views.contains(&R1),
                    "{}: Spec+Kritik kural R1'i içermeli", rule.id
                );
            }
        }
    }

    #[test]
    fn all_rules_have_title() {
        for rule in RULES {
            assert!(!rule.title.is_empty(), "{}: title boş olamaz", rule.id);
        }
    }
}
