//! ÜRETİLMİŞ DOSYA — elle düzenlemeyin (issue #79).
//!
//! Kaynak : https://html.spec.whatwg.org/multipage/indices.html
//! SHA-256: 96f70aa6a8461b19c8ae25e80370cce01523255a447dec1d583967a442237b87
//! Üretim : `python3 spec-audit/gen_html_elements.py`
//! Drift  : `python3 spec-audit/gen_html_elements.py --check`
//!
//! Küme = WHATWG eleman dizini (113) ∪ yabancı içerik kökleri
//! (2: math, svg) ∪ eskimiş elemanlar (15).
//! Toplam 130 ad. İki ek kümenin GEREKÇESİ üreticinin docstring'indedir:
//! `svg`/`math` dizinde yoktur ama HTML'de tanınan başlangıç etiketleridir; eskimiş
//! elemanlar yaşayan standarttan düşmüştür ama gerçek feed'lerde geçer.
//!
//! ⚠️ Liste KAPALI olmak zorunda: açılı ayraç içindeki her kelimeyi etiket saymak
//! `<TBD>`, `<Bilinmiyor>`, `<未定>` gibi gerçek metni işaretlerdi.

/// Alfabetik SIRALI — `binary_search` bunu varsayar.
pub(crate) const HTML_ELEMENTS: &[&str] = &[
    "a",
    "abbr",
    "acronym",
    "address",
    "applet",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "basefont",
    "bdi",
    "bdo",
    "big",
    "blink",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "center",
    "cite",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "dir",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "font",
    "footer",
    "form",
    "frame",
    "frameset",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "link",
    "main",
    "map",
    "mark",
    "marquee",
    "math",
    "menu",
    "meta",
    "meter",
    "nav",
    "noframes",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "picture",
    "pre",
    "progress",
    "q",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "script",
    "search",
    "section",
    "select",
    "selectedcontent",
    "slot",
    "small",
    "source",
    "span",
    "strike",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "svg",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "tt",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
];
